### ISSUE TITLE
R practice session -- 2:30pm 15 April -- BRC 224

### ISSUE THREAD

**Issue by aammd** [minisciencegirl/studyGroup#1]
Hello fellow R-users!
This Wednesday (15 April) I'll be doing a 1 hour practice lesson for the upcoming [Software Carpentry Workshop at Simon Fraser](http://ttimbers.github.io/2015-04-30-SFU/). I'd like to invite you to attend. I'd be so grateful to receive some feedback on my teaching!

The lesson will take place at **2:30 pm** in **room 224** at the [Biodiversity Research Centre (BRC) ](http://www.maps.ubc.ca/PROD/index_detail.php?locat1=314) on UBC campus. 

I'm going to cover _introductory R_ skills, following the [Software Carpentry Lesson plans](http://swcarpentry.github.io/r-novice-inflammation/)

See you then!
Andrew

**Comment by katieannemills** [comment]
Awesome, I'll be there!

**Comment by aammd** [comment]
Oh and reminder to everyone to bring laptops if you want! @BillMills I have stickies -- should we use them?

**Comment by minisciencegirl** [comment]
Hi Andrew,

Can you also please add a quick slide at the beginning of your talk to remind everyone to “WATCH” the R StudyGroup repo and join the group?

Thanks,

Amy

**Comment by jstaf** [comment]
Awesome, see you there!

**Comment by aammd** [comment]
In fact there won't be any visuals at all, other than me writing directly in R in front of everyone -- such is the software carpentry way. So I will do a live demo of how to watch a repository (we can even hook up the screen of somebody who is new and demonstrate the process)

**Comment by katieannemills** [comment]
@aammd solid plan - in that case, mind taking a couple of minutes at the start to introduce the Study Group and what we're up to? Things like the events we're planning (these type of lessons + co-working sessions), share the link to the website (http://minisciencegirl.github.io/studyGroup/) and demo setting up 'watching' the repo like you & @minisciencegirl describe?

**Comment by aammd** [comment]
Definitely!

**Comment by katieannemills** [comment]
Great, thanks! If GitHub had a like button I would totes click it for this.

**Comment by morien** [comment]
@minisciencegirl can you add me as a collaborator here? I'll be doing one of these R practice sessions next week and I'm happy to have the R study group attend.

**Comment by minisciencegirl** [comment]
Done. Please add your R practice sessions as a New Event to our group.

Instructions here: https://github.com/minisciencegirl/studyGroup#how-to-launch-a-new-event

Thanks!

**Comment by aammd** [comment]
Please have Rstudio installed on your laptop before you arrive! I just realized that I did not mention that earlier, sorry!
