### ISSUE TITLE
Link to http://minisciencegirl.github.io/studyGroup/ ?

### ISSUE THREAD

**Issue by rozdakin** [minisciencegirl/studyGroup#10]
Can we add a link to this site in the README? It's not obvious to me how to get there.

Apologies if there is already a link somewhere and I'm just missing it...

**Comment by katieannemills** [comment]
Great idea, thanks for the feedback! I just put a link into the first line of the README.md on the frontpage of the repo; @minisciencegirl, another good place to put it would be in the 'description' of this repo, right at the top.

**Comment by minisciencegirl** [comment]
Sounds good Bill. Will put that in.

Amy
