### ISSUE TITLE
Talks from Oliver Keyes and Rich Fitzjohn on April 4 (revised title)

### ISSUE THREAD

**Issue by jennybc** [minisciencegirl/studyGroup#100]
Hi all. Oliver Keyes will be in the area between 21 March and 8 April and is willing to give us a talk on
- the joys of Rcpp
- the nature of data science work in private industry (he works for the Wikimedia Foundation)
- data ethics

I'm would love to get the group's input on which topic(s) are of most interest and possible dates/times.

To learn more about Oliver:
- His website: http://ironholds.org
- GitHub: https://github.com/ironholds
- Twitter: https://twitter.com/quominus

**Comment by pssguy** [comment]
This is a great opportunity
- Personally, I know nothing about C++ and am just glad other people are using the package. Why does he not give talk on one or more of his own R packages (perhaps alluding to Rcpp if appropriate)
- Yes. Plus I have a chance to chase him up on a WikipediR issue
- Possibly could include in post-talk discussion rather than make focus of presentation

**Comment by Ironholds** [comment]
Because my packages are boring and pointless!

Okay they're not pointless but they have a narrow range of application, specifically to web analytics. Most of them, anyway. Teach a person to fish, on the other hand...

**Comment by SimonGoring** [comment]
I think this would be a great opportunity to talk about ethics.  Both data & computing in general.  Oliver's got a great recent post about his choice to stop releasing packages through CRAN.  I think he's right to do it, but I'm not sure if I can do it.

What are our responsibilities as coders and developers?  How do we exercise them and what can we do when we believe people are acting unethically?

I think we tend to avoid these issues in favour of learning new skills (!) but I think it's critical & @ironholds has an excellent perspective on multiple fronts.  He could teach us to fish ethically.

**Comment by SimonGoring** [comment]
Here is the post I was talking about:
http://ironholds.org/blog/down-and-out-in-statistical-computing/

**Comment by katieannemills** [comment]
Yes to all of the above! I am particularly interested in point #2 (pure self interest, currently looking for data science work : ), but all points would be interesting. Would ethics work best in a more conversational (that means 'beers') setting? Happy with whatever people want to do, and huge thanks to @Ironholds!

**Comment by Ironholds** [comment]
Good question. Usually I've handled ethics as part of a wider talk about the nature of applied data science - broad job advice and notes to the wise about ethics. I do have a template for a talk dedicated to ethics but since I won't give it until 9 March I have no idea if it sucks or not ;p

**Comment by katieannemills** [comment]
Sounds awesome! We're still looking for a speaker for April 4, and that sounds like a great fit. Let us know!

**Comment by Ironholds** [comment]
April 4 would totally work for me, I think! Ethics or the broader working-in-data-science talk?

**Comment by radaniba** [comment]
These topics sound excellent. I think # 2 would be a very insightful one, for lots of reasons : 
- Usually, in industry, there is a mix of data science and data engineering, most of data science efforts are conducted in a distributed manner, which makes data scientists 'forced ?' to have the big data component as a major skill.
- In academia, because of funding issues and other reasons, this (data engineering) is not a must, I would describe this as a small scale data science applications, data sets are usually smaller, the questions mostly on a pilot scale

May be it is a too personal point of view, @Ironholds can confirm :)

Looking forward to this talk

**Comment by jennybc** [comment]
@BillMills @minisciencegirl Who's actually in charge here? 😁 Can we consider the April 4th date "booked"? If so, what time?

@Ironholds Can we confirm the votes for topic #2 as the main focus of official talk (and to discuss the subject your recent blog posts afterwards over beer)? I would look forward to hearing and talking more about both.

**Comment by minisciencegirl** [comment]
Could we do 3 or 4 pm so that we can go for beer right after?? If we are happy with the time, I will post the event and put it in the calendar. So excited to meet @Ironholds in person!

**Comment by jennybc** [comment]
We might also have another special guest in town (@richfitz) so let's book it for 3:30pm in case I can persuade him to give us a talk (I make no promises!). But if the planets aligned, a 3:30pm start gives a chance to have two ~40 min slots and still go out after around 5pm.

**Comment by minisciencegirl** [comment]
@jennybc: You are amazing! :heart_eyes: Thank you for bringing in awesome guest speakers.

**Comment by richfitz** [comment]
I'm happy to do a talk on the 4th if people have the stomach for back to back talks.  I don't have a talk on the go at the moment so this is a good opportunity to write one.  Some possibilities:
- Something something reproducible research (picking over the same ground as [this talk](https://github.com/richfitz/reproducibility-2014) but showing how [remake](https://github.com/richfitz/remake) solved most of the problems.
- Tools for collaborative data use: data versioning and archiving with [datastorr](https://github.com/richfitz/datastorr) and simple encryption with [cyphr](https://github.com/richfitz/cyphr).
- Beyond `mclapply`; job queues and HPC for R (I have a set of packages for dealing with clusters/queuing in both "cloud" and HPC contexts: [rrqueue](https://github.com/richfitz/rrqueue), [dockertest](https://github.com/traitecoevo/dockertest), [queuer](https://github.com/richfitz/queuer), [context](https://github.com/dide-tools/context), [didewin](https://github.com/dide-tools/didewin). Include intractables such as how to recreate your local environment on a remote machine, deal with intermittent network connections, and make progress when only 90% of your jobs have finished.

**Comment by Ironholds** [comment]
Clearly Rich is following me around ;p.

To be totally clear; with 2 we wouldn't be talking about data engineering. More not letting recruiters screw you on salary, and the ethical factors in data collection in those spaces. I'm not sure if that changes the votes.

**Comment by richfitz** [comment]
> Clearly Rich is following me around ;p.

The things I do to repay a lunch.

**Comment by jooolia** [comment]
Sounds like a cool day. :)

My vote for a talk topic from @richfitz https://github.com/richfitz would
be "Tools for collaborative data use". But the other ones sound interesting
as well. :)

**Comment by SimonGoring** [comment]
Can we propose more talks for the same day?

Like a mini-conference?

**Comment by katieannemills** [comment]
@jennybc: @minisciencegirl runs the show, I just answer the phone :)

@richfitz: thanks! Those topics are a three-way photo finish for me, but I think collaborative data use might win out for sheer novelty.

@SimonGoring: what did you have in mind? We could do, but then again we're always looking for sessions to fill upcoming slots!

**Comment by SimonGoring** [comment]
I thought given @Ironholds & @richfitz are presenting we might be able to reach out to other data sci folks in Vancouver, like Tableau or something.  

My understanding (?) from @Ironholds & @richfitz's ideas is that they'll be less hands-on workshops and more presentations (but maybe I'm wrong?).  If that's the case I could do a run-through of my [EarthCube](http://earthcube.org)  talk about connected data in the Earth Sciences (but only if people are interested).

I wouldn't neccessarily be able to coordinate all the facilities stuff at UBC (since I have no standing there!) but I could see who I could wrangle if other people are interested in helping to set this up.

EDIT:  We might be able to talk the SFU folks into joining us too. I don't know who coordinates, but maybe @minisciencegirl could tag them in on this conversation?

**Comment by minisciencegirl** [comment]
Great ideas @SimonGoring! I am tagging @ttimbers @tinyheero to bring together SFU/BCCA folks. 

@BillMills: This could be a great event to host at the Library Commons.

**Comment by katieannemills** [comment]
Alright, I like it - a little mini Vancouver Data Con could be fun, I might be able to pull in some industry folks, too. @ttimbers @brunogrande @theavanrossum @aliojjati - does sfu want in on this?

**Comment by ttimbers** [comment]
@minisciencegirl @BillMills a big YES to either the two talks or a mini Vancouver Data Con, I am certain the group at SFU would be happy to participate. Let us know if there is anything we can do to help! Apr 4?

**Comment by katieannemills** [comment]
@minisciencegirl yes! To the library! Can you coordinate with them while we wrangle speakers? Do we want to shoot for an all day thing, say 10-4 + pub following?

**Comment by SimonGoring** [comment]
This is great!  I think 10 - 4 works well.  It's not too long, but long enough to have some good talks.

What do we want to do as far as coffee/lunch goes?  Can we wrangle funding from UBC?  Should we set up a small planning committee and sketch out options?

@ttimbers @BillMills @minisciencegirl @jennybc (as a faculty contact) & myself? Anyone else?

**Comment by katieannemills** [comment]
@SimonGoring nominally sounds good, but let's keep it simple for now - maybe a lecture track in the afternoon, a workshop track in the morning, and coffee if someone wants to sponsor. Let's all see who we can pull in and go from there!

**Comment by SimonGoring** [comment]
@BillMills sure, just wanted to see what people wanted to do & see what kinds of options we wanted to present.

**Comment by jennybc** [comment]
FWIW @richfitz and I can't necessarily commit beyond the original timeframe discussed way above, as one of the reasons he'll be in town is for us to work on something. But that's great if these two guest talks catalyze something larger.

**Comment by katieannemills** [comment]
@jennybc @richfitz no problem! Whatever time slot you want works for us :)

**Comment by pssguy** [comment]
Just a reminder if you are going the miniconference route [issue 81](https://github.com/minisciencegirl/studyGroup/issues/81)

**Comment by katieannemills** [comment]
@pssguy yes, good idea! Let's see what other talks emerge in the next two weeks before we decide if we want to make this an R exclusive event; if those are the sessions people want to give, then by all means.

**Comment by pssguy** [comment]
Yes. I guess the subjects would be stretching the R connection a bit

**Comment by radaniba** [comment]
Aouch, guys it's centered around data science why making it exclusive ? (I don't mind what prog.lang will be used, but you might lose people down the road, no ? )

**Comment by pssguy** [comment]
@radaniba The miniconference is a way for getting small conferences related to R funded so would prob only be appropriate if the whole session was R related

**Comment by dhavide** [comment]
I can possibly contribute as a rep from Continuum Analytics (I need to check a few things first). We are primarily a Python shop, but part of the intention of conda and Anaconda is to support data science in any language.

Is there any chance of hosting the event _off-campus_? I do think a conference with industry-academia data science themes takes on a different flavour on a university campus. I will see if I can help arrange something.

**Comment by katieannemills** [comment]
Hi @dhavide,

No problem on being a python shop - we do tons of Python at Study Group (despite 'R' in our chapter name), so this is a perfect fit.

Off campus could work, too, since we're pulling in the SFU and BCCA teams as well - perhaps downtown somewhere? Open to suggestions, let us know!

**Comment by Ironholds** [comment]
This event spiralled somewhat :D.

What's wrong with hosting on-campus? I don't know what "different flavour" means.

**Comment by jennybc** [comment]
FWIW @richfitz (and I) are much more able to attend if this happens on campus, late on Monday, as per the original plan.

It's beginning to feel like there's a groundswell for something much more ambitious in the medium future that can be multi-language, UBC/SFU, off-campus, etc. Maybe we should decouple these two things?

**Comment by Ironholds** [comment]
I would support decoupling them, yeah. On-campus would work a bit better for me too.

**Comment by katieannemills** [comment]
@jennybc @Ironholds sure, no problem - we can definitely keep this low-key and on campus for our guests. @SimonGoring @dhavide, we'd still be delighted to hear from you earlier in the afternoon, if you're interested to come out!

**Comment by dhavide** [comment]
Okay, I retract my earlier suggestion; let's keep it on campus :)

I'll get back when I know I can commit to coming...

**Comment by daisieh** [comment]
I am in for this event whatever it is, but obviously I would love for it to be bigger than R.

**Comment by katieannemills** [comment]
Alright, research commons at Koerner library is in! We've got a room for about 35, so should be good. So, for a schedule, here is a totally unofficial, not-finalized proposal:
- 1:00 @rtanglao (Mozilla) - "Visualizing Vancouver Visuals"
- 1:20 Tommy Levi (Unbounce) - "Using natural language processing to categorize and find similar web pages"
- 1:55 @stephhazlitt & @ateucher - "Using R for transparent, repeatable environmental reporting"
- 2:25: :coffee: :coffee: :coffee:
- 2:45 @SimonGoring - "Transformative Earth Sciences through Data: EarthCube, Neotoma & Flyover Country"
- 3:20 @richfitz - "Tools for collaborative data use"
- 4:10 @Ironholds - "Data Science for Fun and Non-Profit (how I learned to stop worrying and hate capitalism)"
- to the pub!

With like 5 min breaks in between. I know @jennybc @richfitz @Ironholds are busy most of the day, so of course feel free to drop in only for your talk.

Any comments or requests for the schedule? The library is going to help us promote to try and bring some new people in, so speakers please post a (flexible, totally non-committal) talk title asap so I can get that out to them.

**Comment by ttimbers** [comment]
This looks awesome! Can't wait!

On Wed, Mar 2, 2016 at 1:40 PM, Bill Mills notifications@github.com wrote:

> Alright, research commons at Koerner library is in! We've got a room for
> about 35, so should be good. So, for a schedule, here is a totally
> unofficial, not-finalized proposal:
> - 1:00 Mozilla guest speaker
> - 1:35 Unbounce guest speaker
> - 2:10 @SimonGoring https://github.com/SimonGoring's colleague
> - 2:45 @SimonGoring https://github.com/SimonGoring
> - 3:20 @richfitz https://github.com/richfitz
> - 4:10 @Ironholds https://github.com/Ironholds
> - to the pub!
> 
> With like 5 min breaks in between. I think the Mozilla speaker might
> actually be a lightning talk, so we could wedge a coffee in the middle too.
> I know @jennybc https://github.com/jennybc @richfitz
> https://github.com/richfitz @Ironholds https://github.com/Ironholds
> are busy most of the day, so of course feel free to drop in only for your
> talk.
> 
> Any comments or requests for the schedule? The library is going to help us
> promote to try and bring some new people in, so speakers please post a
> (flexible, totally non-committal) talk title asap so I can get that out to
> them.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/minisciencegirl/studyGroup/issues/100#issuecomment-191444765
> .

## 

Tiffany A. Timbers, PhD
Banting Postdoctoral fellow, Leroux Lab
Department of Molecular Biology and Biochemistry
Simon Fraser University
8888 University Drive
Burnaby, BC, V5A 1S6

604-803-4962

tiffany.timbers@gmail.com
tiffanytimbers.com
@TiffanyTimbers

**Comment by jennybc** [comment]
Thanks @BillMills for organizing us!

**Comment by Ironholds** [comment]
I'm busy? I've got literally nothing to do in Vancouver except the talk. Well, and maybe a mashup festival.

Looks good!

**Comment by SimonGoring** [comment]
Ha, this list makes me nervous about presenting :)  I think I've got something cool to show though. . .

**Comment by katieannemills** [comment]
@SimonGoring, I'm psyched! let me know when your colleague is firmed up - thanks!

**Comment by SimonGoring** [comment]
I think we ought to know by Wednesday.

**Comment by minisciencegirl** [comment]
Thanks @BillMills!!

**Comment by SimonGoring** [comment]
Hi all, I've been in contact with @ateucher and @stephhazlitt from DataBC and they're going to fill the spot reserved for "Simon's Colleague".

They're going to give an overview of state of open science & data science in the BC Government and then @ateucher will highlight the tools & products available in the BC Government sphere.

Sound good?  I'm super excited about it :)

**Comment by ateucher** [comment]
Thanks so much for the invite @SimonGoring! I'm super excited (and more than a little intimidated).  Just to clarify, we're from [Environmental Reporting BC](http://www.env.gov.bc.ca/soe/), not from DataBC (though we do work pretty closely with them)

**Comment by katieannemills** [comment]
@ateucher and @stephhazlitt are coming to town?! Huzzah, welcome back folks! Get me a talk title ASAP (that goes for all our speakers NUDGE) and I'll get the agenda out to the library. Looking forward to it!

**Comment by SimonGoring** [comment]
Sorry @ateucher, I was trying to get my Shiny/Leaflet thing ready for Monday so I was a bit distracted.  
@BillMills I'm going to call my talk "Transformative Earth Sciences through Data: EarthCube, Neotoma & Flyover Country"

**Comment by SimonGoring** [comment]
Should I stick with the standard CRAN theme and capitalize every R?

**Comment by minisciencegirl** [comment]
So excited to see @ateucher and @stephhazlitt again! Thanks @SimonGoring for organizing!!

**Comment by katieannemills** [comment]
hey team - still looking for talk titles from @stephhazlitt @ateucher @Ironholds @richfitz - would like to get this in by Friday, so let me know.

**Comment by stephhazlitt** [comment]
@BillMills "Using R for transparent, repeatable environmental reporting"

**Comment by Ironholds** [comment]
In that case, assuming we're going with number 2, the talk will be titled "Data Science for Fun and Non-Profit", subtitle "how I learned to stop worrying and hate capitalism".

**Comment by richfitz** [comment]
I'll go with "Tools for collaborative data use"

**Comment by katieannemills** [comment]
Awesome, thanks all! Nominally final schedule is above (no changes recently) - I'll get this off to the library and we should be good to go. Let us know if there's anything we can help out with before the date!

**Comment by minisciencegirl** [comment]
If you are interested in attending this half-day seminar, please register here: https://events.library.ubc.ca/dashboard/view/6172

This is to help the library keep track of attendance.

**Comment by richfitz** [comment]
Could you please update my affiliation to "Imperial College London"?  Thanks!

**Comment by SimonGoring** [comment]
Can you make sure my affiliation is University of Wisconsin. It's not UBC as stated on the Library page.

**Comment by Ironholds** [comment]
If we're all updating our affiliations can I be Imperial College too? I don't work there it'd just look fancy.

(okay, going, going)

**Comment by katieannemills** [comment]
hey folks - people have been asking if these talks will be webcast - standard Study Group rules apply:
- To webcast or not to webcast is speaker's choice (& speaker's responsibility to facilitate if you go that route)
- tool / service for making your webcast (if you choose to do so) is also up to each speaker; google hangouts on air has been the least painful previously, but feel free to do it your way.

@Ironholds @richfitz @SimonGoring @rtanglao @stephhazlitt @ateucher, if you want to set up a webcast + url beforehand, let me know and I'll make sure it gets tweeted around; otherwise we can just wing it on the day. Looking forward to it!

**Comment by Ironholds** [comment]
I'd love to webcast it. Questions:
1. Will it be recorded and redistributed;
2. Under what license?

I probably can't set it up myself on account of losing my laptop 😑

On Tuesday, 29 March 2016, Bill Mills notifications@github.com wrote:

> hey folks - people have been asking if these talks will be webcast -
> standard Study Group rules apply:
> - To webcast or not to webcast is speaker's choice (& speaker's
>   responsibility to facilitate if you go that route)
> - tool / service for making your webcast (if you choose to do so) is
>   also up to each speaker; google hangouts on air has been the least painful
>   previously, but feel free to do it your way.
> 
> @Ironholds https://github.com/Ironholds @richfitz
> https://github.com/richfitz @SimonGoring
> https://github.com/SimonGoring @rtanglao https://github.com/rtanglao
> @stephhazlitt https://github.com/stephhazlitt @ateucher
> https://github.com/ateucher, if you want to set up a webcast + url
> beforehand, let me know and I'll make sure it gets tweeted around;
> otherwise we can just wing it on the day. Looking forward to it!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/minisciencegirl/studyGroup/issues/100#issuecomment-203139999

## 

Sent from my mobile computing device of Lovecraftian complexity and horror.

**Comment by katieannemills** [comment]
Thanks, @Ironholds - to your questions:
1. It's up to you
2. It's also up to you

Let me know how you want to do it and we'll make it happen; we can webcast from my laptop, though that means anything you want to show will have to be able to fly there, for screen sharing purposes.

**Comment by Ironholds** [comment]
I have everything on GitHub, so we're cool! And: yes please and Cc-0 or
CC-BY-SA if possible :)

On Wednesday, 30 March 2016, Bill Mills notifications@github.com wrote:

> Thanks, @Ironholds https://github.com/Ironholds - to your questions:
> 1. It's up to you
> 2. It's also up to you
> 
> Let me know how you want to do it and we'll make it happen; we can webcast
> from my laptop, though that means anything you want to show will have to be
> able to fly there, for screen sharing purposes.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/minisciencegirl/studyGroup/issues/100#issuecomment-203653018

## 

Sent from my mobile computing device of Lovecraftian complexity and horror.

**Comment by katieannemills** [comment]
@Ironholds is CC-BY acceptable? The easiest way to webcast something (that I know of) is via 'Google hangouts on air', which leaves the video on YouTube afterwards: YouTube, subsequently, has a [CC-BY option](https://support.google.com/youtube/answer/2797468?hl=en) - and only a CC-BY option (weird but true).

If this is acceptable, can you schedule the hangout on air? Having you record and upload it on your own account allows us to avoid any recording release issues (and leaves you in control of your own content) - better for everyone. If not, let me know and we'll figure something else out!

**Comment by Ironholds** [comment]
Sounds good! And, not really: see the 'no laptop'

On Wednesday, 30 March 2016, Bill Mills notifications@github.com wrote:

> @Ironholds https://github.com/Ironholds is CC-BY acceptable? The
> easiest way to webcast something (that I know of) is via 'Google hangouts
> on air', which leaves the video on YouTube afterwards: YouTube,
> subsequently, has a CC-BY option
> https://support.google.com/youtube/answer/2797468?hl=en - and only a
> CC-BY option (weird but true).
> 
> If this is acceptable, can you schedule the hangout on air? Having you
> record and upload it on your own account allows us to avoid any recording
> release issues (and leaves you in control of your own content) - better for
> everyone. If not, let me know and we'll figure something else out!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/minisciencegirl/studyGroup/issues/100#issuecomment-203756033

## 

Sent from my mobile computing device of Lovecraftian complexity and horror.

**Comment by katieannemills** [comment]
@Ironholds right, sorry - it's ok, we can get set up during coffee break on my machine. See you then!
