### ISSUE TITLE
SWC Python workshop at UBC library - instructors & helpers needed!

### ISSUE THREAD

**Issue by katieannemills** [minisciencegirl/studyGroup#106]
Hi team,

Research Commons at UBC Library is keen for a SWC-Python workshop sometime the week of May 16; anyone interested in getting some teaching practice or helpering? Don't worry if you haven't taught SWC before or finished your SWC teacher's badge yet - everyone I've seen teach at Study Group is more than ready. We need instructors for:
- [x] Shell (thanks @lmguzman) 
- [x] Python I (loops, conditions, functions) (thanks @jieliu920608) 
- [x] Python II (testing, debugging) (thanks @jrebane)
- [x] Git (thanks @daisieh) 

If you aren't quite up for teaching but are curious about SWC, being a helper (just answering student questions 1:1, no lecturing) is a good way to see what it's all about - let me know if you want to jump in!

**Comment by lmguzman** [comment]
I think I will be around, so I will be happy to help

**Comment by katieannemills** [comment]
Thanks, @lmguzman! Any preference on session?

**Comment by daisieh** [comment]
I replied in email but will reiterate here: I am in for Git fun.

**Comment by katieannemills** [comment]
Thanks @daisieh! Everyone else: still need 1-2 more instructors + helpers, let us know!

**Comment by lmguzman** [comment]
I can do python 1 and/or the shell

**Comment by katieannemills** [comment]
Thanks @lmguzman! If you're cool to float between those two, I'll wait to mark them off in case someone has a burning passion to do one or the other.

**Comment by katieannemills** [comment]
@lmguzman can I put you down for shell? We've got a new instructor joining us who is keen to do the first half of python. Thanks!

**Comment by patrickwalls** [comment]
@BillMills I'd be happy to be a helper.

**Comment by katieannemills** [comment]
Fantastic, thanks @patrickwalls! I'll post details here as they are finalized shortly.

**Comment by jrebane** [comment]
Still need someone for part II of python? I should be around :)

**Comment by katieannemills** [comment]
@jrebane fantastic! Have you had a chance to teach the second half of Python before? No worries if not, but I'm meeting up with @jieliu920608 (who is doing Python I) to go over the material and talk strategy this coming Friday - care to join? Have a read of sections 5-10 under 'Topics' [here](http://swcarpentry.github.io/python-novice-inflammation/) - Jie will likely be covering through 6, but I like to have a bit of overlap in case the class needs to go extra carefully. Let me know here or hit me up at mills.wj@gmail.com - looking forward to it!

**Comment by jrebane** [comment]
@BillMills: I haven't taught the second half of Python before, but am pretty familiar with the content. Would love to join you and @jieliu920608 on Friday if you'll have me! Let me know when and where and I'll make myself available. Looking forward to it as well.

**Comment by jieliu920608** [comment]
Hey @jrebane https://github.com/jrebane, the location and time for us
discussion is at ESB 3064 at noon this Friday! See you there!
Jie

**Comment by katieannemills** [comment]
@jrebane @jieliu920608 that's fantastic, let's do that. We'll talk about the material a bit, answer any questions you have, and share some tips on teaching SWC. If any other SWC instructors are on campus and available to join in to offer more perspectives, the more the merrier!

**Comment by lmguzman** [comment]
@BillMills Ill join you guys :)

**Comment by katieannemills** [comment]
@lmguzman awesome, see you then!

**Comment by katieannemills** [comment]
Alright, we are live and accepting registrations: http://billmills.github.io/2016-05-17-UBC/

Do please have a look and see that I spelt everything kind of correctly, the links work etc, and help spread the link around to everyone you think might be interested - and if anyone still wants to jump in as a helper, it's never too late!
