### ISSUE TITLE
Tags for tips and snippets

### ISSUE THREAD

**Issue by radaniba** [minisciencegirl/studyGroup#108]
It would be great to add a tag to be used in the issues for small things that do not need a talk or a session to be presented (I have plenty of little things that can be shared). This can be a simple technique, a hint, a trick, to be shared and discussed. People adding these issues can close them right away, but the discussion can continue as it raises interest.

what do you think ?

**Comment by radaniba** [comment]
to distinguish these tasks from general issues, we can add **[tips]** in the title for example. I know that @BillMills created a repo for tutorials but this do not fit, these are simply small tricks

**Comment by katieannemills** [comment]
looks like a magic github elf beat me to it, 'tips' tag is now available - good idea!

**Comment by radaniba** [comment]
awesome !
