### ISSUE TITLE
How to loop, not loop, and speed loops up - Wed May 27 3PM in Biodiv 224

### ISSUE THREAD

**Issue by rozdakin** [minisciencegirl/studyGroup#11]
I could do a workshop on this. Any interest?

**Comment by minisciencegirl** [comment]
Yes totally!

**Comment by ksamuk** [comment]
I am very interested in this.

**Comment by katieannemills** [comment]
plus a million, I'm in :)

**Comment by morien** [comment]
Same. Definitely interested in this.

**Comment by ahippman** [comment]
Yes! Yes! Yes!!!

**Comment by jkbooth** [comment]
Also yes!

**Comment by mattjbayly** [comment]
Should be called: "How to change your life with loops": assign, paste, get, ifelse, save, object[j]...

**Comment by rozdakin** [comment]
Hi folks,
Packages you'll need for today's workshop:
gapminder
dplyr
microbenchmark
...& their dependencies

**Comment by Lauramorillas** [comment]
Hi all, 

I am new in GITHUB but I was in today's meeting.Very useful staff, thanks! Is the code we were working on today available somewhere?I couldn't bring my laptop today so no notes.... Thanks!

**Comment by katieannemills** [comment]
Hi @Lauramorillas - thanks for coming out, it was great to have you join in! The notes or a link to them will be going into [this directory](https://github.com/minisciencegirl/studyGroup/tree/gh-pages/lessons) here on GitHub if @rozdakin would indulge us. Thanks Roz for a really useful lesson!

**Comment by rozdakin** [comment]
Will do, tomorrow I think. Apologies for the delay. Stay tuned!

**Comment by ksamuk** [comment]
This was a really great tutorial, Roz! Thanks for putting it together.

**Comment by minisciencegirl** [comment]
No worries Roz!! Fantastic tutorial today - I am really excited to apply your tips on speeding up the loops. Thanks again!!

**Comment by rozdakin** [comment]
Alright, notes are up!
Here's an example I didn't get to, on how to use loops to animate time series: http://roslyndakin.com/archives/5730

**Comment by Lauramorillas** [comment]
Thank you very much! this is great!!

Laura Morillas
Postdoctoral fellow, 
Department of Earth, Ocean and Atmospheric Sciences,
University of British Columbia

**Comment by ksamuk** [comment]
Those animated time series are extremely cool, Roz. Would love to see this in more papers e.g. simulations, pop gen models, etc.

**Comment by katieannemills** [comment]
wicked cool, thanks @rozdakin - linked your lessons from the [Study Group Handbook](http://mozillascience.github.io/studyGroupHandbook/lessons.html), thanks again!
