### ISSUE TITLE
[tips] Monitor jobs on SGE cluster

### ISSUE THREAD

**Issue by radaniba** [minisciencegirl/studyGroup#110]
If you're using an HPC to run some heavy computation, you need to keep an eye on your jobs, you can do that by opening a terminal from time to time and typing something similar to `qstat` command to pull your running jobs with their ids on the cluster.

I added this function on my ~/.bashrc file in order to avoid doing that everytime, I just open one terminal put it in a corner of my monitor and just keep an eye on it from time to time

``` shell
function qloop()
{
    while true;
      do qstat -u <your username here> | head -n $1 ;
      echo total: `qstat -u raniba | tail -n+3 | wc -l`;
      sleep 1;
    done
}
```

You can call it by using the command `qloop N` , with N being the number of jobs you want to display per loop

Hope that helps

Rad

![qloop](https://cloud.githubusercontent.com/assets/1666443/14689683/41cbaf7a-06fd-11e6-8156-4cebe44c2ada.gif)

**Comment by jstaf** [comment]
You may be interested in the `watch` command. It runs any command and displays the output every 2 seconds until you Ctrl-C it, and it clears the screen between runs. So `watch qstat -u <yourUserName>` does the same thing.

Also another fun SGE one-liner is `qdel -f $(qstat -u XXXXXX | awk '{print $1}' | tail -n +3)` (where XXXXX is a username). This instantly kills all of XXXXX's jobs in one go.

**Comment by radaniba** [comment]
Sweet ! Didn't know about `watch` will test that thanks @kazi11

**[update]** : 👍
