### ISSUE TITLE
Summer Schedule

### ISSUE THREAD

**Issue by katieannemills** [minisciencegirl/studyGroup#111]
per @radaniba's suggestion, here's a new issue for filling out our summer schedule, for our sessions **Fridays at 1** which currently looks like:

May 20 - Intro to Pandas / @BillMills #112 
May 27 - R Utility Belt: ggplot / @lmguzman #113
June 3 - Coworking #114 
June 10 - R Utility Belt: stringr + lubridate / @aammd #115 
June 17 - Network Analysis / @gvdr #126 
June 24 - R Utility Belt: Linear Regression Theory / @patrickwalls #120 
~~July 1 - Canada Day Holiday~~
July 8 - R Utility Belt: lm & glm / @ttimbers #121
July 15 - Dealing with Numerical Errors / @mgelbart #119 
July 22 - R Utility Belt: Rmd & knitr / **instructor tbd** #122
July 29 - ______________ or Coworking
August 5 - R Utility Belt: dplyr & magrittr / @JoeyBernhardt #123
August 12 - R `purrr` / @jennybc 
August 19 - R Utility Belt: `tidyr` / @wmhall #124
August 26 - ______________ or Coworking

@wmhall @radaniba @markjohnsonubc @SimonGoring @jrebane @jennybc (and anyone else), y'all had good ideas for sessions over in #107 - pick a _______ spot and let us know! Also team R, @JoeyBernhardt is helping organize a runthrough of the [R Utility Belt](https://github.com/minisciencegirl/studyGroup/issues/29) for beginners this summer - feel free to jump in there too.

**Comment by katieannemills** [comment]
So how about that May 20 ______? Anyone keen to jump in? There's a Python SWC just a couple of days before, so it might be cool do do something python that the new students can jump in with; maybe pandas? @ttimbers do you still have the notes from your pandas lesson you did at vanpyday last year? I could do that unless someone else wants the spot.

**Comment by wmhall** [comment]
@BillMills could i grab one of the dates in August? @jennybc and i had talked about coordinating so that her `purrr` session comes before my lesson, hopefully we can still work that out.

**Comment by katieannemills** [comment]
@wmhall absolutely, how about August 12?

**Comment by wmhall** [comment]
@BillMills August 12th, works great!

**Comment by katieannemills** [comment]
Hi @wmhall - sorry, I just noticed (duh), the `tidyr` lesson you want to teach overlaps with the R Utility Belt content @JoeyBernhardt is organizing; can I move you to August 19, since we have that as an R Utility Belt day? Then (possibly if convenient for her) @jennybc could do `purrr` August 12, so y'all are back-to-back? Happy to accommodate anything you want, let me know.

**Comment by jennybc** [comment]
Sure you can put me down for `purrr` on Fri Aug 12. We have yet to plan summer vacation, so there's slight caveat I might need to move. But I would know with plenty of advance notice.

**Comment by lmguzman** [comment]
@jennybc is it possible for you to broadcast/ record your purrr lesson?

**Comment by jennybc** [comment]
@lmguzman Way to raise the stakes 😁! But sure I'm happy to do so. I know @BillMills has helped other speakers do similar, so I imagine we can find a way to make it watchable after the fact or from somewhere else.

**Comment by wmhall** [comment]
@BillMills @JoeyBernhardt that sounds good to me. Given that the lesson is now part of the R Utiility Belt series, is there specific `tidyr` content that I need to cover? I was planning on focusing in on a couple of specific functions but happy to broaden if need be.

**Comment by katieannemills** [comment]
@jennybc @lmguzman no problem, happy to help - we usually google hangouts on air it. Jenny, have you ever done one of these before? I usually like to get the speaker to [set it up through their own account](https://support.google.com/plus/answer/4386744?hl=en), so they retain ownership of their own video; there's some account setup-y type of stuff to do the first time, so it helps to do so before the talk if possible. Or, we'll sort it out then!

@wmhall nope! You should teach the lesson you want to teach. As long as it's pretty much mostly about `tidyr`, that's all we need for the Utility Belt series; the details are totally up to you. There's [some stuff](http://remi-daigle.github.io/tidyr_reshape2_lesson/) here you can borrow from if you want, but it's by no means necessary.

**Comment by gvdr** [comment]
So, I'll be happy to lead a short introductory crash session on complex network exploration and analysis in R either June 17 or July 29. The idea would be to (1) introduce the basic "flow" of how network studies are done, (2) touch some maths and (3) present the basic libraries out there (igraph, ggraph, networkx). If people bring their own problem would be wonderful.

**Comment by katieannemills** [comment]
@gvdr sounds great! Can I put you down for the June 17 slot? Would definitely help to have a demo problem for folks who are curious but don't have their own problem to bring.

**Comment by gvdr** [comment]
Perfect for me.

Yeah, pet problems are only to have some bonus material that we _may_ get
to see during the workshop. :-)

Best,

Giulio

Bill Mills wrote:

> @gvdr sounds great! Can I put you down for the June 17 slot? Would
> definitely help to have a demo problem for folks who are curious but don't
> have their own problem to bring.
> 
> ---
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/minisciencegirl/studyGroup/issues/111#issuecomment-223826764

## 

Giulio Valentino Dalla Riva

Beaty Biodiversiyt Reseach Centre
University of British Columbia
Vancouver, Canada

**Comment by jennybc** [comment]
How does a precise time and place get settled for, say, the purrr session I've agreed to teach on Friday Aug 12?

**Comment by katieannemills** [comment]
@jennybc: 1PM, Koerner Library room 153 is the nominal coordinates - but if you need something different, let us know!
