### ISSUE TITLE
R Utility Belt: intro to ggplot2

### ISSUE THREAD

**Issue by katieannemills** [minisciencegirl/studyGroup#113]
**What**: Introduction to plotting data using [ggplot2](http://ggplot2.org/) package in R.
**Who**: Everyone! This lesson will be suitable for R beginners.
**When**: Friday, May 27, 1 PM - 2 PM
**Where**: Koerner Library, room 153; [map](https://www.google.ca/maps?q=koerner+library&oe=utf-8&gws_rd=cr&um=1&ie=UTF-8&sa=X&ved=0ahUKEwif7-vqnNrMAhUK2GMKHeQJC2EQ_AUIBygB).
**Before you come**: You'll need the free version of [R Studio](https://www.rstudio.com/) installed; install ggplot2 by doing `install.packages("ggplot2")` at the terminal in R Studio (if you're not sure how to do this, we'll get you set up at the start of the lesson).

@lmguzman is kicking off the R Utility Belt, our summer series on core packages every R user should know, with plotting in ggplot2. This lesson is suitable for beginners - all are welcome, bring your friends!

**Comment by smbrodie** [comment]
How long is it?
And do you need to RSVP?

**Comment by katieannemills** [comment]
Hi @smbrodie,

Our sessions are usually 1 hour, and no RSVP necessary - feel free to drop in, and bring your friends!

**Comment by BrunoGrandePhD** [comment]
@BillMills Where can I find the lesson notes for the R utility belt? I looked [here](https://github.com/minisciencegirl/studyGroup/blob/gh-pages/lessons/ggplot2/lesson.md), but the link is dead.

**Comment by katieannemills** [comment]
@brunogrande the topic list has links to about half the lessons: https://github.com/minisciencegirl/studyGroup/issues/29

@JoeyBernhardt is pulling together links to material as it is taught at UBC for all the lessons, but if you beat us to one of them, by all means post the notes and we'll link them!

**Comment by JoeyBernhardt** [comment]
Hey @brunogrande, yes, I'm pulling them together as we go. So far we've only covered ggplot and for that @lmguzman used the SWC `ggplot2` lesson, without any major modifications.
