### ISSUE TITLE
Tutorial: Using Git and GitHub with R, RStudio, and R Markdown

### ISSUE THREAD

**Issue by jennybc** [minisciencegirl/studyGroup#118]
I'm giving a tutorial at useR! in about a month, with the welcome support of @daattali and @BernhardKonrad:

Using Git and GitHub with R, RStudio, and R Markdown
http://user2016.org/tutorials/01.html

I figure I should practice! And give myself a soft deadline for making a big push on getting organized.

Would you like to be a test subject? Then vote on a time!

I want this to remain a low-key dry-run, so please don't post this elsewhere.

I've already polled the Stat dept and thought I'd open it up here too:

http://whenisgood.net/j7mmp5g

Warning: the stat folks have incredibly incompatible schedules already, so I expect no time is good for everyone 😟.

**Comment by katieannemills** [comment]
June 17 / 1PM would be perfect for Study Group, that's supposed to be a special topics day in any event :)

**Comment by jennybc** [comment]
Schedules are very incompatible, so here is the least of all evils:

Wednesday June 15

Apologies to those who can't make it :(

12pm - 1pm: troubleshoot Git and GitHub set up
(you can skip this if you are able to use our instructions to get set up and PROVE your are set up)

_I already know @daattali can't make it, so I could REALLY use a couple helpers from 12pm - 1pm!!! Especially anyone who is good with Windows._

1pm - 4pm The Actual workshop!!!

Location TBD but probably in ESB

PLEASE send me an email if you want to keep receiving email:
jenny@stat.ubc.ca

Here's who I expect interest from, based on whenigood. Note: It's a mix of people I reached via the Stat dept and here:

Bill Mills
Carolyn T
Conan Phelan
Giulio Dalla Riva
Joey
Matias
Mike M
Natalia N
Patrick
Paul G
Vincenzo

Thanks for your interest!
Jenny

**Comment by jennybc** [comment]
I need a couple email addresses, I have a workshop location, I have set up a repo:

I feel like I have email address from everyone I recruited here except for: **Giulio, Patrick**. Email me if you're in: jenny@stat.ubc.ca. Anyone can email me, for that matter, to sign up or let me know you can lend a hand 12 - 1pm.

Location:
Earth Sciences Building (ESB) 4192
a.k.a. the usual Statistics seminar and grad classroom
https://goo.gl/maps/DuZmUS3c6oP2

12pm - 1pm: troubleshoot Git and GitHub set up _learners can skip if install goes well; but I desperately need some help from people who can install/config git, esp. on Windows!_

1pm - 4pm The Actual workshop!!!

I will start to develop the materials here, if you want to star or watch or bookmark or whatever you do to flag things on github:

https://github.com/jennybc/happy-git-with-r

Currently that is truly a placeholder, but it will develop over next 10 days.

**Comment by katieannemills** [comment]
Awesome! Thanks @jennybc, looking forward to it. I will show up at noon (but sadly am not the windows pro you're looking for).
