### ISSUE TITLE
Tutorial on numerical errors

### ISSUE THREAD

**Issue by mgelbart** [minisciencegirl/studyGroup#119]
**What**: Introduction to numerical errors and strategies to avoid them in any language (session will be led in R, but there's actually nothing specific to R about this topic - come one come all!)
**Who**: Everyone! This lesson is suitable for beginners.
**When**: Friday, July 15, 1 PM - 2 PM
**Where**: Koerner Library, room 153; [map](https://www.google.ca/maps?q=koerner+library&oe=utf-8&gws_rd=cr&um=1&ie=UTF-8&sa=X&ved=0ahUKEwif7-vqnNrMAhUK2GMKHeQJC2EQ_AUIBygB).
**Before you come**: This lesson applies to _all_ programming languages, so feel free to follow along in any language you like. The session will be led in R, so if you'd like to follow along with the presentation exactly, you'll need the free version of [R Studio](https://www.rstudio.com/) installed.

Does it bother you that `1e20 + 1 == 1e20` returns True or that `0.3 - 0.2 - 0.1` returns some weird number that is not zero... in any language? I can talk about common floating point errors (roundoff, overflow, etc.) and some strategies for avoiding them.

**Comment by katieannemills** [comment]
Thanks, @mgelbart! This looks great - I added the usual boilerplate to the top post, feel free to correct anything you like. Thanks again!
