### ISSUE TITLE
Introduction to Version Control with Git

### ISSUE THREAD

**Issue by katieannemills** [minisciencegirl/studyGroup#12]
We'll cover basic Git usage on your local machine, and maybe pushing up to GitHub if there's time. **This lesson is suitable for people who have never used Git or version control before!**
- When: Wednesday, April 29, 2:30 PM
- Where: [UBC Biodiversity Research Center](https://www.google.ca/maps/place/Beaty+Biodiversity+Museum,+The+University+of+British+Columbia,+Vancouver,+BC+V6T+1Z4/@49.263446,-123.2499992,18z/data=!4m5!1m2!2m1!1subc+near+Beaty+Biodiversity+Museum,+Vancouver,+BC!3m1!1s0x548672c9f84be123:0x1c431143106eb830), room 224
- Before you come: please [install Git](http://git-scm.com/book/en/v2/Getting-Started-Installing-Git) on your laptop (windows users, pls follow the link in the comment below instead). If you have trouble, ask questions in this thread or contact me directly at bill@mozillafoundation.org

**Comment by katieannemills** [comment]
It occurs to me that **Windows users will need to install Git Bash** as well as Git - if you're on a windows machine, pls follow the [download and install instructions here](http://msysgit.github.io/). See you on Wednesday!

**Comment by rozdakin** [comment]
Hey Bill, can you confirm the time? I see 2:30PM here, but for some reason the email notification I got says 3PM.

**Comment by ksamuk** [comment]
224 is booked (for us) from 2:30-4:30.

**Comment by katieannemills** [comment]
Yep, definitely 2.30 - sorry, some of these sessions have been 3, some 2.30 - we are definitely doing git on Wednesday at 2.30.

**Comment by katieannemills** [comment]
ping! our git lesson is today at 2.30; try and have a go at getting git installed beforehand per the instructions in the first couple comments; I will show up around 2 to help troubleshoot, if anyone has problems. See you this afternoon!
