### ISSUE TITLE
R Utility Belt: Linear Regression

### ISSUE THREAD

**Issue by katieannemills** [minisciencegirl/studyGroup#120]
**What**: Introduction to linear regressions (by hand!) in R.
**Who**: Everyone! This lesson will be suitable for R beginners.
**When**: Friday, June 24, 1 PM - 2 PM
**Where**: Koerner Library, room 153; [map](https://www.google.ca/maps?q=koerner+library&oe=utf-8&gws_rd=cr&um=1&ie=UTF-8&sa=X&ved=0ahUKEwif7-vqnNrMAhUK2GMKHeQJC2EQ_AUIBygB).
**Before you come**: You'll need the free version of [R Studio](https://www.rstudio.com/) installed.

@patrickwalls will be walking us through how to perform linear regressions by hand in R for round 3 of the R Utility Belt, with a gentle review of the theory behind how data fitting works. This lesson is suitable for beginners - all are welcome, bring your friends!

**Comment by katieannemills** [comment]
Thanks for doing this, @patrickwalls! Let me know if there are any dependencies or details for the description you'd like to update.

**Comment by patrickwalls** [comment]
The plan for tomorrow is to explore some linear algebra concepts in R with applications to linear regression. We'll talk about vectors, matrices, matrix operations and linear regression. We'll be using built-in R functions and so there are no dependencies to worry about. See you tomorrow!

**Comment by katieannemills** [comment]
@patrickwalls psyched for this, thanks again!

**Comment by patrickwalls** [comment]
Hey gang, I put my notes from today in a repo. You can find it here: https://github.com/patrickwalls/R-examples

**Comment by JoeyBernhardt** [comment]
thanks a lot @patrickwalls! This was so great -- I use `lm` pretty much every day, so being able to recreate it our own function was amazing! I learned a ton.
