### ISSUE TITLE
R Utility Belt: Fitting Data with lm and glm

### ISSUE THREAD

**Issue by katieannemills** [minisciencegirl/studyGroup#121]
**What**: Introduction to `lm` and `glm` data fitting in R.
**Who**: Everyone! This lesson will be suitable for R beginners.
**When**: Friday, July 8, 1 PM - 2 PM
**Where**: Koerner Library, room 153; [map](https://www.google.ca/maps?q=koerner+library&oe=utf-8&gws_rd=cr&um=1&ie=UTF-8&sa=X&ved=0ahUKEwif7-vqnNrMAhUK2GMKHeQJC2EQ_AUIBygB).
**Before you come**: You'll need the free version of [R Studio](https://www.rstudio.com/) installed.

@ttimbers will be showing us how to use R's `lm` (linear models) and `glm` (generalized linear models) to fit our data in round 4 of our summer series on the R Utility Belt. This lesson is suitable for beginners - all are welcome, bring your friends!

**Comment by ttimbers** [comment]
The notes for this lesson are here: https://github.com/ttimbers/lm_and_glm/blob/master/lm_and_glm.Rmd

Also, you will need to have the following R packages installed:

```
MASS
titanic
ggplot2
broom
```
