### ISSUE TITLE
R Utility Belt: Making Beautiful Documents with Rmd & knitr

### ISSUE THREAD

**Issue by katieannemills** [minisciencegirl/studyGroup#122]
**What**: Introduction to making high-quality reports and documents in R using Rmd and `knitr`.
**Who**: Everyone! This lesson will be suitable for R beginners.
**When**: Friday, July 22, 1 PM - 2 PM
**Where**: Koerner Library, room 153; [map](https://www.google.ca/maps?q=koerner+library&oe=utf-8&gws_rd=cr&um=1&ie=UTF-8&sa=X&ved=0ahUKEwif7-vqnNrMAhUK2GMKHeQJC2EQ_AUIBygB).
**Before you come**: You'll need the free version of [R Studio](https://www.rstudio.com/) installed; also, install knitr by doing `install.packages("knitr")` at the terminal in R Studio (if you're not sure how to do this, we'll get you set up at the start of the lesson).

Round 5 of the R Utility Belt will introduce how to make elegant, publication-quality pdfs and web-ready documents from your code, data and analysis, right from within RStudio. This lesson is suitable for beginners - all are welcome, bring your friends!

**Comment by katieannemills** [comment]
~~(psst - this lesson still needs an instructor! preferably someone more able to spell the word 'knitr' than me :)~~ thanks, @eacton!

**Comment by minisciencegirl** [comment]
Thanks to the lovely @eacton for running this session!

**Comment by eacton** [comment]
Hello!  Here is the repo for the code we will be using today -- grab the .Rmd and .txt files to follow along!
https://github.com/eacton/R-Utility-Belt-Rmarkdown

The libraries being used are also found on the README landing page.

**Comment by eacton** [comment]
Hey there!  I just wanted to leave a few resources for peeps.  I will also put these on the site's README.
For markdown: https://gist.github.com/dupuy/1855764
Knitr options: http://yihui.name/knitr/options/
And for more interactive documents: http://ggvis.rstudio.com/cookbook.html and http://shiny.rstudio.com/articles/interactive-docs.html

Thanks to everyone who came out!

**Comment by pishili** [comment]
Thank you Erica for your great workshop and sending the materials.

Cheers,
Ladan
