### ISSUE TITLE
R Utility Belt: Tidying data with tidyr and reshape2

### ISSUE THREAD

**Issue by katieannemills** [minisciencegirl/studyGroup#124]
**What**: Introduction to taming and tidying messy, unruly data into dataframes using tidyr and reshape2.
**Who**: Everyone! This lesson will be suitable for R beginners.
**When**: Friday, August 19, 1 PM - 2 PM
**Where**: Koerner Library, room 153; [map](https://www.google.ca/maps?q=koerner+library&oe=utf-8&gws_rd=cr&um=1&ie=UTF-8&sa=X&ved=0ahUKEwif7-vqnNrMAhUK2GMKHeQJC2EQ_AUIBygB).
**Before you come**: You'll need the free version of [R Studio](https://www.rstudio.com/) installed; install tidyr and reshape2 by doing `install.packages("tidyr")` and `install.packages("reshape2")` at the terminal in R Studio (if you're not sure how to do this, we'll get you set up at the start of the lesson).

@wmhall will be doing our seventh and final R Utility Belt session of the summer on tidyr and reshape2, two tools for taking imperfect, incomplete or otherwise irregular data and arranging it into tidy dataframes for use in R. This lesson is suitable for beginners - all are welcome, bring your friends!

**Comment by wmhall** [comment]
Hi!

Here is the link for today's tidyr lesson:

https://github.com/wmhall/tidyr_lesson/blob/master/tidyr_lesson.md 

I'll be using two packages: tidyr and dplyr.

Install them by typing `install.packages("tidyr")` and `install.packages("dplyr")` at the terminal in R Studio.

Thanks!

**Comment by wmhall** [comment]
Post from Hadley about NSE:

http://rpubs.com/hadley/157957
