### ISSUE TITLE
Intro to Network Analysis / June 17

### ISSUE THREAD

**Issue by katieannemills** [minisciencegirl/studyGroup#126]
**What**: Introduction to network analysis theory and implementation in R.
**Who**: Everyone! This is an intermediate-level lesson, but we'll try to help everyone stay on board.
**When**: Friday, June 17, 1 PM - 2 PM
**Where**: Koerner Library, room 153; [map](https://www.google.ca/maps?q=koerner+library&oe=utf-8&gws_rd=cr&um=1&ie=UTF-8&sa=X&ved=0ahUKEwif7-vqnNrMAhUK2GMKHeQJC2EQ_AUIBygB).
**Before you come**: You'll need the free version of [R Studio](https://www.rstudio.com/) installed; install igraph by doing `install.packages("igraph")` at the terminal in R Studio (if you're not sure how to do this, we'll get you set up at the start of the lesson).

@gvdr will be leading a short introductory session on complex network exploration and analysis in R. The idea would be to (1) introduce the basic "flow" of how network studies are done, (2) touch some maths and (3) present the basic libraries out there (igraph, ggraph, networkx). If people bring their own problem would be wonderful.

**Comment by katieannemills** [comment]
Thanks again, @gvdr! Is there anything people need to do to prepare? Perhaps how to install ggraph and networkx? Let us know!

**Comment by gvdr** [comment]
No, it will not be necessary.

P.S. It may be a good idea to bring along an analog writing and memorization support, in other words, a pad of pages for writing notes on. ;-)

**Comment by gvdr** [comment]
Wonderful people, I've prepared some intro to the intro slides. They are totally optional, but if you end up giving a look at them, it may be good. They should give an idea of what I intend to do :-)
They are [on my github](https://github.com/gvdr/201606_network_introduction/blob/master/Slides_intro_network.md)
See you!

**Comment by minisciencegirl** [comment]
Thank you @gvdr for a fantastic intro to network analysis with background music!
