### ISSUE TITLE
Fall Session Planning!

### ISSUE THREAD

**Issue by minisciencegirl** [minisciencegirl/studyGroup#128]
Hi everyone,

We had a fantastic line up of session this summer, learning all kinds of cool stuff & filling out the Utility Belt sessions (thanks @JoeyBernhardt for the awesome planning/ wrangling)

 We are getting ready to wrangle a new set of lessons for the Fall! So - what do people want to teach? What do people want to learn? 

Post suggestions here!
- New meeting time poll to come

**Comment by katieannemills** [comment]
paging:
- @ttimbers re: data fashion show
- @markjohnsonubc re: sonifying time series data
- @jrebane re: the whole bunch of awesome suggestions you made [here](https://github.com/minisciencegirl/studyGroup/issues/107#issuecomment-211728510).

Plus another R Utility Belt run, since it seemed pretty popular? Summer session filled up quick, so don't be shy!

**Comment by gvdr** [comment]
**Teaching**: I have some ideas, and would be happy to receive feedbacks:
- **Network** analysis via R. With a heavier focus on (1) visualization (with `ggraph`) and (2) how to be _tidy_ while dealing with graphs.
- **EvolutioneR**. A bird's eye introduction to evolutionary ecology using R. With birds. (tentatively covering phylogenetic packages and a selection of ROpenSci data-access packages).
- R does **Spark**. Analysing large datasets on the cloud using R and Databricks. _Aka_ pretend to be a big-data scientist without the pain of really learning stuff.

My knowledge of the three topics is in decreasing order (I am ready when you want for the first, I need some honing for the second, I am still learning the third).

**Learning**: Many, many, things. Anything related with the three mentioned topics is surely in my interest. Moreover:
- Natural Language Processing. Especially what's available to deal with the all those non-english languages.
- Big Data / Cloud Computing on R.
- All those new and juicy alternatives/complements to `make`.
- ...

**Comment by markjohnsonubc** [comment]
I'm good for something mid-October or later

On Jul 16, 2016, at 10:36 AM, Bill Mills <notifications@github.com<mailto:notifications@github.com>> wrote:
-   @markjohnsonubchttps://github.com/markjohnsonubc re: sonifying time series data

**Comment by ttimbers** [comment]
I'm very booked up for teaching for the next 8 months, so I'm a maybe until I know what the new date/time is fit the fall.

**Comment by minisciencegirl** [comment]
Please fill out this scheduling poll for the Fall semester by Wednesday, Aug 31, noon!

http://whenisgood.net/bimkgqi

Don't worry too much about the dates, but just pick the times that work for you. Thanks.
