### ISSUE TITLE
#hackyhour July 29 5pm - 

### ISSUE THREAD

**Issue by minisciencegirl** [minisciencegirl/studyGroup#129]
Hi everyone! 

We've not had a #hackyhour in a while. To wrap up a great summer of sessions, say goodbye to old friends and meet new friends, we will meet at:

Where: Koerner's Pub, UBC
When: July 29, 5 PM

Hope to see you there!

@aammd: there's no session planned for 7/29. Would you like to do the remake session at 4pm and we can head over for beers after?

**Comment by JoeyBernhardt** [comment]
@minisciencegirl I'll be sad to miss this -- I'm away at a conference for the next two Fridays. Have fun!
