### ISSUE TITLE
Remake: managing complicated projects in R

### ISSUE THREAD

**Issue by katieannemills** [minisciencegirl/studyGroup#130]
**What**: Introduction to intelligently running and re-running parts of a complicated R project using Remake.
**Who**: Everyone! This lesson will be suitable for R beginners.
**When**: Friday, July 29, 4 PM - 5 PM **note the different time this week!**
**Where**: Koerner Library, room 153; [map](https://www.google.ca/maps?q=koerner+library&oe=utf-8&gws_rd=cr&um=1&ie=UTF-8&sa=X&ved=0ahUKEwif7-vqnNrMAhUK2GMKHeQJC2EQ_AUIBygB).
**Before you come**: please try and [install remake](https://github.com/richfitz/remake#installation).

@aammd will be introducing [Remake](https://github.com/richfitz/remake), a tool for re-executing only those parts of an R project that need to be re-executed, helping to take some of the pain out of building more sophisticated R projects. All are welcome - but note the later time! We'll be adjourning to Koerner's per #129 afterwards.

**Comment by pajodu** [comment]
I will regrettably miss this due to other commitments, but look forward to the posted notes. 

Thanks for having these great workshops! 

Patrick Dubois , BSc, MA 
PhD Student, UBC Psychology 
Kenny 3522

**Comment by aammd** [comment]
https://github.com/aammd/remake-tutorial
