### ISSUE TITLE
purrr: functional programming, iteration/aggregation / August 12

### ISSUE THREAD

**Issue by jennybc** [minisciencegirl/studyGroup#131]
**What**: Functional programming, iteration and aggregation in R using purrr, taught by Jenny Bryan.
**Who**: Everyone! This is an intermediate-level lesson, but we'll try to help everyone stay on board.
**When**: Friday, August 12, 1 PM - 2 PM
**Where**: Koerner Library, room 153; [map](https://www.google.ca/maps?q=koerner+library&oe=utf-8&gws_rd=cr&um=1&ie=UTF-8&sa=X&ved=0ahUKEwif7-vqnNrMAhUK2GMKHeQJC2EQ_AUIBygB).
**Before you come**: Please install purrr: `install.packages("purrr")`; also, check out these resources:
- https://github.com/hadley/purrr
- https://cran.r-project.org/web/packages/purrr/index.html
- http://r4ds.had.co.nz/iteration.html
- http://r4ds.had.co.nz/hierarchy.html

Purrr is a package to augment R's _functional programming_ tools; functional programming is a style of programming that makes the behavior of your code easier to predict and debug. In this lesson, we'll see an introduction to purrr and functional programming in R.

**Comment by jennybc** [comment]
@minisciencegirl or @BillMills can one of you apply appropriate labels? I think it's event + intermediate. I took the liberty of just opening this issue; feel free to correct me if I overlooked some convention.

**Comment by katieannemills** [comment]
Thanks, @jennybc! Feel free to re-edit anything in the top post you like, of course.

**Comment by minisciencegirl** [comment]
Thanks @BillMills and @jennybc! The issue looks great!

**Comment by vjd** [comment]
@BillMills youtube broadcast possible?

**Comment by katieannemills** [comment]
@vjd it's speaker's choice - they'll post details here if they choose to webcast!

**Comment by ghost** [comment]
How can I join?Hangout link or on air?

**Comment by jennybc** [comment]
Is anyone who's planning to attend willing to be the person to manage some sort of hangout? To connect with @vjd and @drashti4, for example? I'd like to not be on the hook for managing that connection, but I don't mind if a few others join us remotely.

**Comment by ghost** [comment]
This is intermediate level session but I don't have much idea about R.Can I join?

**Comment by jennybc** [comment]
@drashti4 It might not make a lot of sense if you have very little knowledge of R. The "intermediate" label is genuine.

**Comment by ghost** [comment]
Okay then I am out for this session.Thank you for humble response :)

**Comment by minisciencegirl** [comment]
Here are the lesson notes for anyone interested: https://github.com/jennybc/purrr-tutorial

**Comment by jennybc** [comment]
And here's the rendered version that's easier on the eyeballs:

https://jennybc.github.io/purrr-tutorial/
