### ISSUE TITLE
STAT 545 needs more TAs

### ISSUE THREAD

**Issue by jennybc** [minisciencegirl/studyGroup#133]
I am seeking the equivalent of 1 to 2 more TAs for STAT 545 this fall:

http://stat545.com/people-help-wanted.html

Sam Hinshaw (@samhinshaw) is already signed on as a full TA, but he will need some help.

We've staffed this course with large TA teams for the past 2 years, with a core of 1 -2 lead TAs. And it works very well.

It would be awesome to have some repeat TAs from previous years!

It is possible to have a partial TA appointment (as in a fractional appointment or for only certain dates) and we have also simply done hourly in past. This means some folks who would not otherwise TA might still able to do this.

The course has gained quite a lot of visibility outside of UBC now, so this could be a positive thing for anyone wishing to build up some visible data science experience.

Alums you might know and who, I imagine, would be happy to answer questions:

@daattali @ksamuk @dchiu911 @oganm @cheny19 @eacton @npjc @MagdaPrice @jooolia @sjackman @BernhardKonrad @gloriali @aammd

**Comment by sjackman** [comment]
I can help out piecemeal. I like tidy data, automated pipelines, and long walks on the beach.

**Comment by daattali** [comment]
If you need more people to cover modules, I would gladly do one week's teaching (I realize as a non-student that would be unpaid, I'm ok with that)

**Comment by BernhardKonrad** [comment]
Do you have any use for online helpers from the south (ok with same restrictions as @daattali)?

**Comment by jennybc** [comment]
Great @sjackman I will be in touch.

@daattali @BernhardKonrad Thanks! I hate to see you do stuff that goes uncompensated. But I will let you know if the right combination of need and fit arises. It would be our gain to have you back!

@daattali The Shiny week is an obvious match for you, since you are actually still here physically right? I will look into whether there is any way to pay a guest lecturer, though I've never heard of that. So don't hold your breath.

**Comment by gvdr** [comment]
That's a really nice opportunity and I am _strongly_ interested!

How may I apply for the position?

Best,

Giulio Dalla Riva

Jennifer (Jenny) Bryan wrote:

> I am seeking the equivalent of 1 to 2 more TAs for STAT 545 this fall:
> 
> http://stat545.com/people-help-wanted.html
> 
> Sam Hinshaw (@samhinshaw) is already signed on as a full TA, but he will
> need some help.
> 
> We've staffed this course with large TA teams for the past 2 years, with a
> core of 1 -2 lead TAs. And it works very well.
> 
> It would be awesome to have some repeat TAs from previous years!
> 
> It is possible to have a partial TA appointment (as in a fractional
> appointment or for only certain dates) and we have also simply done hourly
> in past. This means some folks who would not otherwise TA might still able
> to do this.
> 
> The course has gained quite a lot of visibility outside of UBC now, so
> this could be a positive thing for anyone wishing to build up some visible
> data science experience.
> 
> Alums you might know and who, I imagine, would be happy to answer
> questions:
> 
> @daattali @ksamuk @dchiu911 @oganm @cheny19 @eacton @npjc @MagdaPrice
> @jooolia @sjackman @BernhardKonrad @gloriali @aammd
> 
> ## 
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/minisciencegirl/studyGroup/issues/133

## 

Giulio Valentino Dalla Riva

Beaty Biodiversity Reseach Centre
University of British Columbia
Vancouver, Canada

**Comment by oganm** [comment]
Having a full time commitment is probably too much for me these days but I can be a fractional TA again if there is need.

**Comment by jennybc** [comment]
@gvdr You are a post-doc right? Vs grad student? I think that probably precludes TA appt but I will check to see what's possible. Maybe there is a way, esp. if I am struggling to get enough effort through standard TAships.

**Comment by lmguzman** [comment]
Hi Jenny, I would also be able to do a fractional TA if you need.

**Comment by gvdr** [comment]
Oh, snap, yes I'm a postdoc. I am sorry, but I still fail to grasp the edu
system here :-)

Well, if there's any teaching opportunity, I'm here :-)

Thanks in any case,
G
Jennifer (Jenny) Bryan wrote:

> @gvdr You are a post-doc right? Vs grad student? I think that probably
> precludes TA appt but I will check to see what's possible. Maybe there is
> a way, esp. if I am struggling to get enough effort through standard
> TAships.
> 
> ## 
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/minisciencegirl/studyGroup/issues/133#issuecomment-243888597

## 

Giulio Valentino Dalla Riva

Beaty Biodiversity Reseach Centre
University of British Columbia
Vancouver, Canada

**Comment by jennybc** [comment]
@gvdr OK I've asked about that.

@lmguzman Will soon add you to an email thread w/ others and our grad coordinator.

**Comment by eacton** [comment]
@jennybc I can also be a fractional TA again if you need more help.

**Comment by jennybc** [comment]
@eacton OK will resend an email I've sent with other interested alums.
