### ISSUE TITLE
Fall semester "git" together!

### ISSUE THREAD

**Issue by minisciencegirl** [minisciencegirl/studyGroup#134]
Curious about study group? Want to learn R/ Python/ (insert your favorite programming language du jour) and don't know where to start? Have a cool package/ tool that you want to share with the community?

Come to the first study group meetup of the fall semester!
**Time:** Monday, September 12, 3 PM
**Place:** Koerner Library (Room 216)

We will talk about topics YOU are interested in and schedule the sessions. Come help us plan out this semester and sign up for a GitHub account if you don't have one.

Here are the dates with some potential topics. Utility Belt sessions (see #29) are aimed at beginners (and will cover various R packages including tidyr, dplyr, broom, ggplot2, stringr, lubridate etc). This semester, we are also trying something new, where we will meet to work through Hadley Wickham's Advanced R book http://adv-r.had.co.nz/. 

9/12 - GIT together
9/19 - R Utility Belt 
9/26 - Advanced R
10/3 - R Utility Belt 
10/10 - Thanksgiving
10/17 - Advanced R
10/24 - R Utility Belt 
10/31 - Co-working
11/7 - 
11/14 - 
11/21 - 
11/28 - 
12/5 - 
12/12 - 

Hope to see you all there!!

Cc: @JoeyBernhardt @tinyheero @gvdr @alyeffy @markjohnsonubc @mstrimas @morien @LeungConnie @SimonGoring @patrickwalls @jrebane

**Comment by SimonGoring** [comment]
Thanks, looking forward to it, especially working through Hadley's book!

I'd be happy giving an intro to RMarkdown & its various features.  I could also re-do the leaflet/interactive mapping lesson I did last year, and would be happy doing a "let's start your R package" talk.

**Comment by SimonGoring** [comment]
And, if there's anyone interested we could do fun & games with paleoecological data in R, but that's probably not as interesting, unless people have ideas about incorporating actual fossil records into phylogenies. . .

**Comment by morien** [comment]
That's a really fun idea, and I actually know someone who does exactly that
in Mary Berbee's lab.

**Comment by minisciencegirl** [comment]
@SimonGoring: That sounds fantastic! Really interested in leaflet/ interactive mapping, as well as your other suggestions! Feel free to slot yourself in to any time slots that suit your schedule. I think RMarkdown can definitely fit into one of the R Utility Belt session.
@morien: Want to coordinate with @SimonGoring and your friend on the paleoecological game session? (I don't work on paleoecology but this sounds like great fun!)

**Comment by JoeyBernhardt** [comment]
Hi everybody! Please post your ideas for upcoming sessions here! What do you want to learn? What do you want to share??

**Comment by evhersh** [comment]
On the general skills side of things, I'm interested in learning how to use:
- git and github (I mainly work alone, but I'm up for whatevs)
- Markdown (convince me to switch from LaTeX?)
- git/overleaf/latex collaborating, also collaborating with "MS Word only" people if you use Markdown, LaTeX, etc...
- how to us git with command line/terminal
- just more about stats in general
- best practices to keep code clean and do things the "right" way

As far as specific stats/tools, I'm gonna be using:
- general linear mixed models (lmer and lme4 packages?)

**Comment by SimonGoring** [comment]
2016/09/19 - R Utility Belt - ggplot @gvdr 
2016/10/03 - R Utility Belt - dplyr @JoeyBernhardt 
2016/10/24 - R Utility Belt - knitr/markdown @SimonGoring
????? - Daisie - Git (we'll find her name in a bit)

**Comment by SimonGoring** [comment]
@evhersh left a comment in the other thread about some of the things he'd like to see:

On the general skills side of things, I'm interested in learning how to use:
- git and github (I mainly work alone, but I'm up for whatevs)
- Markdown (convince me to switch from LaTeX?)
- git/overleaf/latex collaborating, how to us git with command line/terminal
- just more about stats in general
  As far as specific stats/tools, I'm gonna be using:
- general linear mixed models

**Comment by minisciencegirl** [comment]
This looks fantastic! Thank you @JoeyBernhardt @SimonGoring @evhersh @gvdr! I will post the schedule later this week. We could potentially nudge @patrickwalls to help us out with stats/ glm?

**Comment by pajodu** [comment]
Unfortunately, I have a regular commitment on Mondays at 3pm, so I should probably not be CCed on this list. 

I'll miss you all. Have fun! 

Patrick Dubois , BSc, MA 
PhD Student, UBC Psychology 
Kenny 3522

**Comment by gvdr** [comment]
Hi Patrick,

we are sorry to miss you :-(

Best wishes,

P.S. This is not a mailing list. You are receiving the email because you
are following the github repo, in order _not_ to receive the email
unfollow the repo or change your settings :-)

Patrick Dubois wrote:

> Unfortunately, I have a regular commitment on Mondays at 3pm, so I should
> probably not be CCed on this list.
> 
> I'll miss you all. Have fun!
> 
> Patrick Dubois , BSc, MA
> PhD Student, UBC Psychology
> Kenny 3522
> 
> From: "Amy Lee" notifications@github.com
> To: "minisciencegirl" studyGroup@noreply.github.com
> Cc: "Patrick Dubois" patrick.dubois@psych.ubc.ca, "Mention"
> mention@noreply.github.com
> Sent: Tuesday, September 13, 2016 7:49:27 AM
> Subject: Re: [minisciencegirl/studyGroup] Fall semester "git" together!
> (#134)
> 
> This looks fantastic! Thank you @JoeyBernhardt @SimonGoring @evhersh @gvdr
> ! I will post the schedule later this week. We could potentially nudge
> @patrickwalls to help us out with stats/ glm?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub , or mute the thread .
> 
> ## 
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/minisciencegirl/studyGroup/issues/134#issuecomment-246766683

## 

Giulio Valentino Dalla Riva

Beaty Biodiversity Reseach Centre
University of British Columbia
Vancouver, Canada

**Comment by minisciencegirl** [comment]
Hey @pajodu: Sorry to miss you this semester! Good luck and see you next semester. I did remove you from the Cc: up top so hopefully you won't receive emails from this thread anymore. 

Thank you @gvdr @SimonGoring and @JoeyBernhardt for teaching Utility Belt!

**Comment by SimonGoring** [comment]
FYI - I talked to @rtanglao and he's offered to write notes from the sessions (to Markdown) if we are able to record them.  @minisciencegirl could we contact someone at the library to see if we could get recording equipment?

**Comment by minisciencegirl** [comment]
Thank you @rtanglao and @SimonGoring for the suggestion! Maybe @sheryladam at the library can help us out. I will chat with her. @JoeyBernhardt and I are also meeting with the Advanced Research Computing group on campus to seek more structural support such as recording. Let me know if you want to join in on that meeting (Friday 9/23 1pm).
