### ISSUE TITLE
Tag your neighbour

### ISSUE THREAD

**Issue by SimonGoring** [minisciencegirl/studyGroup#135]
For the `git` to know each other, _let's all tag our neighbor_.
- Go ahead!

**Comment by jensculrich** [comment]
@mayho3

**Comment by ksedivyhaley** [comment]
@emwest

**Comment by AlexisBlack2g** [comment]
@dtavern

**Comment by dtavern** [comment]
@AlexisBlack2g

**Comment by mamora** [comment]
@ahofmann4 hello

**Comment by jrebane** [comment]
@tam3tree Hello!

**Comment by ahofmann4** [comment]
@mamora Hi!

**Comment by khuus** [comment]
Hey Anna! @acreuscu

**Comment by mayho3** [comment]
@jensjohnson

**Comment by tam3tree** [comment]
Hey! @jrebane

**Comment by evhersh** [comment]
On the general skills side of things, I'm interested in learning how to use:
- git and github (I mainly work alone, but I'm up for whatevs)
- Markdown (convince me to switch from LaTeX?)
- git/overleaf/latex collaborating, how to us git with command line/terminal
- just more about stats in general

As far as specific stats/tools, I'm gonna be using:
- general linear mixed models 

@mayho3 @jensjohnson

**Comment by emwest** [comment]
@ksedivyhaley

**Comment by acreuscu** [comment]
# Hey Kelsey and Vicky! @hkuus

**Comment by marcus-campbell** [comment]
@ksedivyhaley

**Comment by gvdr** [comment]
Hi, I'm here too! @JoeyBernhardt

**Comment by victoriaayala** [comment]
hi! @gvdr

**Comment by SimonGoring** [comment]
Hi @evhersh, I'm going to move your comment into the thread about upcoming sessions.  And then I'm closing this issue down.  Thanks everyone!
