### ISSUE TITLE
2016-09-19 0 Intro to `ggplot2` - Plotting in R

### ISSUE THREAD

**Issue by SimonGoring** [minisciencegirl/studyGroup#136]
An introduction to the heavily used [ggplot2](http://ggplot2.org/) package.  From diamonds, to carets to car mileage and (hopefully) beyond.  Let's let @gvdr take us for a spin with this very useful package!

**Time**: Monday, September 19, 3 PM
**Place**: Koerner Library (Room 216)

**Comment by gvdr** [comment]
Dear everybody, there are no high technical demands for the session, just have a running R version (you may want to consider RStudio as an editor) and the necessary packages. Life has recently become easier, as now we can install everything we need using the `tidyverse` package.

``` r
install.packages("devtools")
devtools::install_github("hadley/tidyverse")
```

Let us now if you have any tech problem.
