### ISSUE TITLE
2016-10-03 - R Utility Belt - `dplyr`

### ISSUE THREAD

**Issue by SimonGoring** [minisciencegirl/studyGroup#137]
Who knew pipes could be so interesting?  @JoeyBernhardt did, and she's going to walk us through (fast) clear, clean & reproducible data manipulation using the `dplyr` package for R in our second R Utility Belt Session.

**Time**: Monday, October 3, 3 PM
**Place**: Koerner Library (Room 216)

**Comment by JoeyBernhardt** [comment]
[Link for today](https://github.com/JoeyBernhardt/RStudyGroup-dplyr-lesson/blob/master/dplyr-lesson.Rmd)

also, helpful link: http://www.milanor.net/blog/aggregation-dplyr-summarise-summarise_each/
