### ISSUE TITLE
2016-10-31 - R Utility Belt - `knitr`/markdown

### ISSUE THREAD

**Issue by SimonGoring** [minisciencegirl/studyGroup#138]
Before we start, I'd just like to say how much fun your life is going to be once you've learned how to render all your hopes, your dreams, and your (R) code using a combination of [`knitr`](http://yihui.name/knitr/) and [RMarkdown](http://rmarkdown.rstudio.com/).  The opportunities for your future will be literally endless, especially if you believe in the Many Worlds Theory, in which case, your opportunities already are endless, but they'll be endlessly more enjoyable after this workshop.

**Time**: Monday, October **31**, 3 PM (**Note the change in Date**)
**Place**: Koerner Library (Room 216)

**Comment by SimonGoring** [comment]
Too optimistic?

**Comment by samhinshaw** [comment]
Just wanted to mention the issue title says Oct 10th, but the comment says Oct 3rd, the same date as #137. Will this lesson be on the same day as dplyr? Oct 10th is Thanksgiving.

**Comment by SimonGoring** [comment]
Thanks @samhinshaw, just updated the issue to fix that!

**Comment by rammy4real** [comment]
hello SimonGoring . good day. hope you are doing great sir. i would love to contribute to this. just to let you that i am a starterwith the following knowledge level
html: intermediate
css:intermediate
javascript: basic/beginner
java: basic/beginner
really do love to be part of your team. I promise to give my best and my all .
thank you sir.
rammy4real@gmail.com
