### ISSUE TITLE
Hacky Hour, Oct 21 @ 6pm

### ISSUE THREAD

**Issue by minisciencegirl** [minisciencegirl/studyGroup#140]
It's been a while since we've had a Vancouver Hacky Hour (Dec 2015?), so we think its time for another one! The date has been set for Friday, Oct 21 @ 5pm at a pub near Cambie & Broadway (Original Joe's).

There's a ton going on in the computational research community in Vancouver in Sept/Oct (4 SWC workshops, a Genomics Hackathon, the UBC R & SFU SciProg study groups have kicked off their fall semester sessions, the UBC Master's of Data Science program has started) and so we think there is tons to discuss and talk about. Furthermore - we are just a great bunch of folks, and its fun to catch up!

So we know how big of a table to get, let us know you're coming by signing up on this etherpad:
https://etherpad.wikimedia.org/p/VancouverHackyHour

Hope to see you all there!

Cheers,
@ttimbers

**Comment by ttimbers** [comment]
Hi all! Just a reminder that we're having a Hacky hour this Friday at 5pm at Original Joe's (Cambie and Broadway). Hope y'all can make it!

https://etherpad.wikimedia.org/p/VancouverHackyHour

**Comment by ttimbers** [comment]
Reservation is under my name (Tiffany Timbers)

**Comment by ttimbers** [comment]
Great to see everyone last night! Let's do this again soon!
