### ISSUE TITLE
Consider proposing a talk for the Stat Dept seminar

### ISSUE THREAD

**Issue by jennybc** [minisciencegirl/studyGroup#142]
Hi all.

Natalia Nolde (@nnolde) organizes the regular seminar in the Stat dept. She is looking for speakers, esp. for January - March 2017.

If you have a data science-y project you would like to talk about, please get in touch with her to see if it's a good fit. Yes, we have some rather technical stat talks, but we also really enjoy a mix with more applied talks. So think about it ....

**Comment by SimonGoring** [comment]
Hi @jennybc, the EarthCube Project is a really interesting initiative dealing with Big Data in the Geosciences. They have a set of Distinguished Lecturers & support their talks with up to $600 for travel/accommodation.

http://earthcube.org/info/lecturers-list

Certainly worth considering.  I can help @nnolde if there's someone in particular they'd be interested in bringing in.
