### ISSUE TITLE
R Consortium fund application

### ISSUE THREAD

**Issue by SimonGoring** [minisciencegirl/studyGroup#146]
There is a low barrier to get $150 USD from the R-Consortium through their [RC RUGS](https://www.r-consortium.org/projects/r-user-group-support-program) program.

The one limitation is that we are required to send out a quarterly email to the membership quarterly.  Are people okay with this?

I am okay with this (for the record).

**Comment by ksedivyhaley** [comment]
Sure. Do you have a plan for the grant?

**Comment by minisciencegirl** [comment]
Yes. Some ideas include:

1) Fund beer for a hackyhour social at the end of the year
2) Fund coffee/ donuts for regular co-working session
3) Fund another data science day symposium 

This will be put up to a vote, with additional suggestion welcomed!

**Comment by eacton** [comment]
I think the data science day symposium was awesome!

**Comment by gvdr** [comment]
Ok as well.

**Comment by morien** [comment]
Honestly I like all those suggestions.

**Comment by SimonGoring** [comment]
Hey all.  I started filling out the application and just want to point out the conditions for funding:

- [ ] Have R As Primary Focus (Required)

- [ ] Adhere to the [code of conduct](https://wiki.r-consortium.org/view/R_Consortium_and_the_R_Community_Code_of_Conduct) published on the R Consortium website (Required)

- [ ] Have a public website or page that provides information about meetings and the number of people attending each meeting (Required)

- [ ] Agree to acknowledge the R Consortium as a sponsor and display the R Consortium logo on the group’s website (Required)

- [ ] Agree to have its organizers group send one email per quarter to all of its members containing a message from the R Consortium (Required)

In general I'm fine with these conditions.  It seems to me the big changes would require us to add the R Consortium logo to the webpage somewhere and change our current [code of conduct](https://github.com/minisciencegirl/studyGroup/blob/gh-pages/codeOfConduct.md).  

The other change would be having to send out the quarterly email.  We don't email attendees currently, using Issues instead.  Is this something we'd be willing to change?

**Comment by gvdr** [comment]
I don't have big problems with sending around an email each quarter. So, yeah for me.

**Comment by SimonGoring** [comment]
I'm closing this issue :)
