### ISSUE TITLE
Work-along session on Thursday, May 21, 2pm-4pm

### ISSUE THREAD

**Issue by minisciencegirl** [minisciencegirl/studyGroup#15]
Anyone interested in an R work-along session on Thursday (5/21), 2pm - 4pm?

Bring any R project you are working on and join us for a productive afternoon of co-working, coding and collaborating.

Location TBD.

**Comment by jstaf** [comment]
Mayyyyybe.... I feel like someone should just book a room and then people can show up if they feel like it?

**Comment by katieannemills** [comment]
I'm in! I'm going to be trying to make heads or tails of [Shiny](http://shiny.rstudio.com/) - what is everyone else working on?

**Comment by minisciencegirl** [comment]
Andrew (@aammd) please book us a room! Thanks!

**Comment by aammd** [comment]
Done already! however we should think about getting that nice big room on the first floor of AERL.. does anyone know how?

**Comment by minisciencegirl** [comment]
@aammd: Are we able to get Biodiversity Room 225 for tomorrow?

**Comment by aammd** [comment]
CONFIRMED 225 @ 2pm tomrrow. #werk 
:memo: :coffee: :computer:

**Comment by minisciencegirl** [comment]
Thanks Andrew! 

Do we have the room for 2 hours?

**Comment by aammd** [comment]
yep!

**Comment by minisciencegirl** [comment]
Thanks everyone for a great work-along session! We will try to schedule one every month.

**Comment by katieannemills** [comment]
I had a blast, this went really well! Next time we should also encourage people to bring their friends.

**Comment by ahippman** [comment]
Yes it was great!!!! So supportive and learned some new helpful commands and ways to try to fix it, too!!!
