### ISSUE TITLE
looking for instructors & helpers for an R training in 2017

### ISSUE THREAD

**Issue by JoeyBernhardt** [minisciencegirl/studyGroup#150]
Hi all,

Jamie Rosner from UBC's Advanced Research Computing is looking for some volunteers to help with an R training session for WestGrid/Compute Canada. Is anyone interested in helping out? It'll happen in early 2017, and more details will follow!

Thanks!
J.

**Comment by ksedivyhaley** [comment]
What skill level are they looking for?

**Comment by jrosner** [comment]
Hi All,

We're most likely looking at a novice R online workshop, although the possibility also exists to teach something more advanced or for something domain specific, e.g. R for Bioinformatics, Digital Humanities, etc.
Furthermore, we're looking for 2 or 3 TA/helpers in addition to the instructor.
I'll post again as more details become available... so thanks and stay tuned!

Jamie

**Comment by morien** [comment]
I'm interested in helping, depending on the dates. I am traveling for work
a couple times in the upcoming months.

**Comment by ksedivyhaley** [comment]
I can help with a novice workshop, also depending on schedule.

**Comment by jrosner** [comment]
ok great, i'll get back with possible dates next week

**Comment by gvdr** [comment]
I'm also game (I can lead or help according to need).

I can also throw in some domain/technique specific deals:
R for Bioinformatics (Ecology / Evolution / Phylogenetics)
Network analysis in R
Zen and the Art of Null Model Designing
...

Cheers

**Comment by karimse07** [comment]
I can help
