### ISSUE TITLE
Winter/Spring Session Ideas

### ISSUE THREAD

**Issue by SimonGoring** [minisciencegirl/studyGroup#151]
Hi all, here's the place to create your wishlist of session topics.  What do you want to learn?  What do you want to teach?  Do you have a fun idea?  A graph-off?  A Pecha Kucha type thingy do?  Lightning talks?  Thunder talks?  Unsettled weather talks?

What if we all made a package together?  That sure would be fun!

Vote for a time slot that works for you here: http://whenisgood.net/zf8bk4i
@SimonGoring @JoeyBernhardt @eacton @lmguzman @morien @gvdr @wmhall @pajodu

Add your ideas below.

***Winter/Spring Session, Koerner 153, Wednesdays 3pm***

| Date | Discussion Leader | Topic |
| --- | --- | --- |
| 01/18 | everyone | Co-working: Session planning |
| 01/25 | everyone  | Co-working: [Should I stay or should I go?](https://github.com/SimonGoring/ShouldIStayOrShouldIGo) |
| 02/01 | everyone  | Co-working: [Should I stay or should I go?](https://github.com/SimonGoring/ShouldIStayOrShouldIGo) |
| 02/08 | cancelled due to illness | |
| 02/15 | @JoeyBernhardt | Utility Belt: dplyr |
| 02/22 | everyone  | Co-working: [Should I stay or should I go?](https://github.com/SimonGoring/ShouldIStayOrShouldIGo) |
| 03/08 | @eacton  | Advanced R: [Functional Programming](http://adv-r.had.co.nz/Functional-programming.html) |
| 03/15 | @minisciencegirl | Utility Belt: tidyr/ reshape2 and tidy dataframes |
| 03/22 | everyone  | Co-working: [Should I stay or should I go?](https://github.com/SimonGoring/ShouldIStayOrShouldIGo) |
| 03/29 | @QMuncaster | Advanced R: [Functionals](http://adv-r.had.co.nz/Functionals.html) |
| 04/05 | everyone | Co-working: Develop teaching material for functions |
| 04/12 | @eacton | Utility Belt: ggplot2 |
| 04/19 | everyone | Co-working: [Should I stay or should I go?](https://github.com/SimonGoring/ShouldIStayOrShouldIGo) |
| 04/26 | @minisciencegirl | Advanced R: [Non-standard evaluation](http://adv-r.had.co.nz/Computing-on-the-language.html) |
| 05/03 | everyone | Co-working: [Should I stay or should I go?](https://github.com/SimonGoring/ShouldIStayOrShouldIGo) |
| 05/10 | @SimonGoring | Utility Belt: regex and stringr |
| 05/17 | everyone  | Co-working: Ask questions, get feedback, and learn new things while working on your own projects. |
| 05/24 | @eacton  | Advanced R: [Function Operators](http://adv-r.had.co.nz/Function-operators.html) |
| 05/31 | everyone | Co-working: Ask questions, get feedback, and learn new things while working on your own projects. |
| 06/07 | @samhinshaw  | Advanced R: [Expressions](http://adv-r.had.co.nz/Expressions.html)  |

**Comment by samhinshaw** [comment]
I'm always interested in learning more about visualization, design principles, etcetera. 
Included in that could be:
- ggplot2 
    + [ggthemes](https://cran.r-project.org/web/packages/ggthemes/vignettes/ggthemes.html), [ggthemr](https://github.com/cttobin/ggthemr), cowplot
    + `theme()`
    + SVG export (the right way!)
    + [ggExtra](https://github.com/daattali/ggExtra)
- color palettes
    + RColorBrewer
    + [colourpicker](https://github.com/daattali/colourpicker)
- viz tools
    + shiny & extensions such as [shinyjs](https://github.com/daattali/shinyjs)
    + htmlwidgets
    + ggvis
    + D3.js (implementation in R?)
- basic graphic design principles

Relevant sources of knowledge and inspiration: [Tamara Munzner](https://twitter.com/tamaramunzner) & [Martin Krzywinski](https://twitter.com/mkrzywinski)

**Comment by SimonGoring** [comment]
I have a couple proposals, one that follows from @samhinshaw's and one that I've proposed in the slack channel:

1.  A graphics showcase.  We take a set of data, given a couple weeks in advance, and plot it out, using whatever tools we like.  The data should be somewhat complex, but not overly so.  People can do what they like with it, we post all code and walk through some of the examples.

2.  I'd like to do a simple package wrapping a simple API.  I suggested the giphy API, because it's funny & there's not really a practical reason for having it in R, so it's low stakes if we start working on it and give up :)  But it might be good to use as an example for a two part "Making an R Package" lesson.

**Comment by SimonGoring** [comment]
Also, something about regular expressions.  I use them lots now and I find they're super helpful.  Doing that with `stringi` might be fun.

**Comment by ahofmann4** [comment]
I would appreciate something on regular expressions. I've tried using them,
but a lesson would be really helpful!

**Comment by samhinshaw** [comment]
Love the idea of a graphics showcase, I always learn so much seeing how others decide to tackle the same issue.

I could always stand to get more practice with regex too, and I'd have to imagine we pull a relatively large group in for that. There's also some interesting interactions with [R needing extra backslashes](http://rpubs.com/jennybc/shruggie). 

I might also be worthwhile to do a session on datetime handling. I've been thinking about it recently as I hope to write some content for stat545 on the topic, but there are a lot of different things to cover:
- What is POSIX? What is the `origin`?
- durations, intervals, periods, dates, difftimes, timespans
- Date as character vs date as numeric
- Handling timezones
- `lubridate`, the tool to make this all so much less painful

**Comment by eacton** [comment]
I like the graphics showcase idea @SimonGoring and the dataviz ideas from @samhinshaw. In general, I think it would be kind of cool to post a problem that everyone could try to solve and then we talk about the different methods/code we used to tackle it. Maybe something like that would be an idea for the more intermediate R group once Hadley's Advanced R sessions are done?

**Comment by gvdr** [comment]
Depending on how the new job will fit with the meetings, I can propose something about

- [ ] networks
- [ ] parallel code
- [ ] R on the cloud
- [ ] Other languages (a Julia intro?)

The various bits are combinable (e.g., I can do a Julia intro focussing on networks, or running R parallel code on the cloud...)

**Comment by minisciencegirl** [comment]
Wow these are all great ideas @samhinshaw @eacton @SimonGoring @gvdr! 

Adding to the dataviz idea - is anyone interested in heatmaps? I know there are many ways to do heatmaps (esp with the newer package like ComplexHeatmap) but always end up using qplots. So maybe a small session on pros/ cons of various heatmap packages could be fun.

With all these proposals, we can easily fill the winter and possibly spring session. I will update this issue with a tentative schedule once we have the new time slot for next semester. Thanks everyone for the great suggestions! Keep them coming! 

==========

See the first thread for update

**Comment by ha0ye** [comment]
Hah! I'm actually trying to organize a whole quarter on data viz. for R Users Group at my institution. Tentative "syllabus": https://docs.google.com/document/d/15tQjC4Xto_udL72-1j1FX81lWW2uf6Pjqc_KE_c4k7w/edit?usp=sharing

May be a good idea to compare notes before/during/after?

**Comment by minisciencegirl** [comment]
@ha0ye: This looks like a great syllabus! We will keep you posted as we plan this semester.

**Comment by ha0ye** [comment]
@minisciencegirl Thanks. Forgot to update, but class is currently running. Github repo here: https://github.com/Open-Data-Science-at-SIO/Intro-Data-Viz-Winter-2017

**Comment by mamora** [comment]
Hi, Could someone tell me where exactly will be the meeting tomorrow? the page says Hubbs Hall 4500, but I have no idea where it is?  Thanks a lot

**Comment by ha0ye** [comment]
@mamora Sorry for the confusion. I'm not at UBC, but am running a separate / parallel class at SIO (UCSD) and trying to share info. Do stop on by if you're ever in San Diego!

**Comment by eacton** [comment]
Due to a lack of attendance for our co-working project, the remaining co-working session will be old-school stylz - hanging out while working on individual projects. If anyone wants to come and pass ideas around for the summer sessions - this can also happen these weeks. Hope to see you there!
