### ISSUE TITLE
Amassing Yuletide

### ISSUE THREAD

**Issue by gvdr** [minisciencegirl/studyGroup#152]
Dear companions,

As the holiday season approaches, we thought of getting together for some informal refreshments.

Save the date:

this Friday, 16th of December, evening time.

We'll confirm the place based on how many people intend to join us.

So, who's game?

**Comment by minisciencegirl** [comment]
So far, it looks like it will be me, @JoeyBernhardt and @daisieh

**Comment by jepa** [comment]
Hi everyone, I'm new at UBC and this group. I would like to go but I have to be somewhere at 7. If you plan to meet earlier, I'm in!

**Comment by gvdr** [comment]
So, gathering all the votes. Let's meet at 5:30 pm at the
Storm Crow Tavern
Address: 1305 Commercial Dr, Vancouver, BC V5L 3X5
for pre-dinner convivialities and warm ups.

Then we move around 7 pm to
Via Tevere
Address: 1190 Victoria Dr, Vancouver, BC V5L 4G5
for pizzas.

Note that we can not book at Via Tevere, so we'll need to go there, leave a phone number, and they'll call us back when a table is free for us.

See you soon!
