### ISSUE TITLE
R Lesson Based on BC Gov't Data?

### ISSUE THREAD

**Issue by katieannemills** [minisciencegirl/studyGroup#16]
The BC government has been releasing a bunch of environmental [data](http://www.env.gov.bc.ca/soe/) and related [code](https://github.com/bcgov) lately. I need to dig deeper into these materials, but it might be fun to explore building an R tutorial that uses some of these materials.

Anyone interested? I've talked about this briefly with @minisciencegirl and @aammd, but the more the merrier. To start, we just need to brainstorm some ideas of what we'd like to / can illustrate using these resources.

**Comment by aammd** [comment]
:+1: VERY INTO THIS was just reading up on it

**Comment by minisciencegirl** [comment]
We have no events scheduled for June yet. Why don't we meet early June and schedule a "work along" format session for longer discussion?

**Comment by katieannemills** [comment]
Sure, we could meet up and try to hash something out - good idea! I'm booked on the 4/5 for the [sprint](http://www.mozillascience.org/global-sprint-2015), but am otherwise available around then - or we could just make it a sprint project if people don't mind coming downtown - I'm good with either!

**Comment by dsemeniuk** [comment]
Count me in!

**Comment by mattsolo1** [comment]
Sounds fun

**Comment by morien** [comment]
I think this could make a really interesting lesson, I'm in too.

**Comment by ateucher** [comment]
Hey there, I'm from the [Environmental Reporting BC](www.env.gov.bc.ca/soe) team. @stephhazlitt and I are behind the [R code](https://github.com/bcgov/EnvReportBC-RepoList) put up so far. We're super excited that you're interested, so let me know what we can do to help. Also, stay tuned for a few more R repos to come soon.

**Comment by katieannemills** [comment]
awesome, let's do it - only thing to decide is, should we all get together at UBC (convenient) or hang out at Mozilla (downtown) for the global sprint on June 4/5 (meet people doing cool open science things, free snacks!) - I can set up either, let me know!

**Comment by minisciencegirl** [comment]
Hey why don’t we try late afternoon/ evening of 6/5 for this discussion at Mozilla?

**Comment by aammd** [comment]
+1 for joining the global sprint at Mozilla with this stuff!  I think that would be awesome.

**Comment by morien** [comment]
and how. that sounds like a lot of fun!

**Comment by katieannemills** [comment]
done. I'll book the event and post details once they're live. Looking forward to it!

**Comment by katieannemills** [comment]
Okay cool, this is now officially a Global Sprint project! Everybody plz direct your contributions to [the repo](https://github.com/BillMills/BCenviroLessons); couple of things to start:
- I wrote the contrib guidelines really quickly, please please suggest amendments
- Let's start by spitballing some ideas for lessons in the issue tracker, and see where things go from there.

**Comment by ateucher** [comment]
For those interested, I've opened an [issue](https://github.com/BillMills/BCenviroLessons/issues/1) in @BillMills's repo with some potential data sets that might be a good starting point.
