### ISSUE TITLE
Learn ggplot2! Beginner Friendly.

### ISSUE THREAD

**Issue by eacton** [minisciencegirl/studyGroup#162]
What: To boldy plot what no one has plotted before! Learn ggplot2 -  because everyone needs to visualize and sanity check their data at some point.
Who: Everyone! This lesson will be suitable for R beginners.
When: Wednesday, April 12, 3 - 4 PM
Where: Koerner Library, room 153.

Before you come: You'll need the free version of R Studio installed; install ggplot2 or tidyverse. 

Example: install.packages("tidyverse") at the terminal in R Studio (if you're not sure how to do this, we'll get you set up at the start of the lesson).

**Comment by SimonGoring** [comment]
@eacton Do you have links to the materials?

**Comment by eacton** [comment]
[R utility belt: ggplot2 repo ](https://github.com/eacton/R-Utility-Belt-ggplot2)

The furry_dataset.csv can be downloaded and the live coding session will from there. Thanks everyone!
