### ISSUE TITLE
Intermediate R Programming Workshop Series

### ISSUE THREAD

**Issue by ECOSCOPE** [minisciencegirl/studyGroup#163]
# ECOSCOPE is hosting an Intermediate R Programming Workshop at the end of April!

Workshop 1: Monday, April 24th, 12:00pm – 2:00pm
Workshop 2: Tuesday, April 25th, 2:00pm – 4:00pm
Workshop 3: Thursday, April 27th, 2:00pm – 4:00pm

### **About the Workshop Series**

This workshop series is going to help you use R as a programming environment, allowing you to write more complex, yet clearer data analysis code. We will teach you three fundametal concepts of R programming: functions, classes, and packages.

Functions encapsulate a sequence of computations, allowing you to separate the “what” from the details of “how”. You will learn: – the syntax of R functions – how functions can be reused and composed with your analytic workflows – guidelines for writing clear and reliable code.

Every R object has a class and many have attributes, but this mechanism works quite differently from object-oriented programming in mainstream programming languages. You will learn: • to access specific parts of an object and its attributes, • how the class affects the use of an object and how generic functions, like plot, work with different classes, and • how to create your own generic function. Packages are R’s main method for creating and sharing bundles of related functions, classes, datasets, and help pages.

You will learn:

- the structure of a package,

- how R manages libraries of installed packages,

- how they are used to share both code and analyses, and

- to create your own package and distribute it to other R users.

### Registration
[Click here.](http://ecoscope.ubc.ca/events/intermediate-r-programming-workshop-series/)

### Location
Life Sciences Institute - Room LSC 3
2350 Health Sciences Mall, Vancouver BC

### Contact
info.ecoscope@ubc.ca

**Comment by scisus** [comment]
Oh darn! This intersects with lab meetings. Hopefully there'll be another Intermediate R course like this in the summer?

**Comment by ECOSCOPE** [comment]
Hello,

As of right now we are hoping to hold an introductory R course during the summer but the majority of our courses are held during the academic year. For more information and updates about our events you can visit: http://ecoscope.ubc.ca/events/

If you have any questions please let me know.

Have a happy Wednesday,

Mandeep Nahal, MM
ECOSCOPE Program Manager

The University of British Columbia
Department of Microbiology and Immunology
Life Sciences Institute
2505-2350 Health Sciences Mall
Vancouver, BC V6T 1Z3

email: mandeep.nahal@ubc.ca<mailto:mandeep.nahal@ubc.ca>
website: ecoscope.ubc.ca<http://ecoscope.ubc.ca>










On Apr 11, 2017, at 5:59 PM, scisus <notifications@github.com<mailto:notifications@github.com>> wrote:


Oh darn! This intersects with lab meetings. Hopefully there'll be another Intermediate R course like this in the summer?
