### ISSUE TITLE
Co-working Session!

### ISSUE THREAD

**Issue by eacton** [minisciencegirl/studyGroup#165]
Co-working Sessions: May 17,  May 31, June 7, 3-4pm.
Koerner Library 153

Ask questions, get feedback, and learn new things while working on your own projects. All levels!

Ideas for summer sessions welcome!

**Comment by ttimbers** [comment]
I'll be there (at least by 3:30pm) and I'll bring some ideas for workshop sessions!

**Comment by ksedivyhaley** [comment]
This issue is from last year - do we need a new room booking?
