### ISSUE TITLE
Mozilla Global Sprint 2017

### ISSUE THREAD

**Issue by eacton** [minisciencegirl/studyGroup#166]
Hi everyone, 

We're hosting a site here at UBC for the Mozilla Global Sprint on June 1, 2017 https://mozilla.github.io/global-sprint/.  The  Global Sprint is a fun, two-day community event bringing people from around the world together to collaborate on open projects, such as developing open source software, building open tools, writing curriculum, planning events, and more.

We'd like to invite you to join us on the 1st at Koerner Library (Rm K217), from 9am-4pm.You can join in and participate, no matter your skill set or level. We’re looking for coders, designers, artists, writers, educators, students— anyone who’s passionate about the open web and collaboration. We’ve got a terrific list of projects that need help— all that’s missing is you!

For more on how you'd participate at the event, see our info page for Participants https://mozilla.github.io/global-sprint/participants/. To browse all the amazing projects you can work on during the Sprint, see our Featured Projects https://mozilla.github.io/global-sprint/projects/, and our full list of all Sprint Projects. https://github.com/mozilla/global-sprint/issues

If you're interested in attending, please register at https://ti.to/Mozilla/global-sprint-vancouver.  We have room to host 30 people.

If you have any questions about our local event, feel free to get in touch !

I hope you'll join us for the Sprint!

**Comment by eacton** [comment]
@jennybc Could you give your students a heads up about this event?

**Comment by ksedivyhaley** [comment]
I'd like to go but I've got something else going on in the morning. Would it be OK to arrive a bit late, around 11am? The main page said it's not necessary to participate in the whole event but I want to make sure I'm not messing up your planning.

**Comment by morien** [comment]
I have done this event before and it is okay to arrive later, just
coordinate with the other participants and it will be fine

**Comment by eacton** [comment]
Hey @ksedivyhaley   - yes you can show up later - totally fine as @morien said.  Please still register so we know seating. If you can watch the 2nd video here https://mozilla.github.io/global-sprint/participants/  - I know you know Github, but it is just basically how to choose and contribute to projects - that would be what you miss if you aren't there from the start in the morning.

**Comment by Ekaparna** [comment]
hey, i would like to participate but i am a beginner so i would like to know about what i have to do how the whole process will go on and also about the projects.

**Comment by SimonGoring** [comment]
Hi @Ekaparna, all the projects are posted here: https://mozilla.github.io/global-sprint/projects/  I found a few that I was interested in, but think I'll work on the CORE project.  If you find one you're interested in take a look at the Issues for the project.

For developers it's often very helpful to have beginners work through examples and contribute to the text to help clarify things that might not be clear.
