### ISSUE TITLE
Job opportunity for grad students at Arts ISIT

### ISSUE THREAD

**Issue by sanamsh** [minisciencegirl/studyGroup#168]
We are looking for a grad student or a recent grad to work on an analytics project that is underway in the UBC Faculty of Arts. Please share this with the people in your network and if you know anyone who might be interested or a good fit please let me know.

**Learning Analytics Project Assistant**
 
**Description:**
Learning analytics refers to "the measurement, collection, analysis and reporting of data about learners and their contexts for purposes of understanding and optimizing learning and the environments in which learning occurs"
In the Faculty of Arts, numerous learning analytics projects are underway to allow Deans, Heads and faculty members to make use of existing data about students, learning and teaching to better understand 'what is happening' in our classrooms, and how students learn. The goal, always, is to use available data to improve learning, teaching, and student success.
 
The project assistant will help with a particular learning analytics project and receive direct supervision from Sanam Shirazi, Research Analyst at Arts ISIT. The work may call for collaboration with the IT database developer and IT team, as well as other project stakeholders at Arts ISIT, the Arts dean’s office, and the Centre for Teaching, Learning and Technology.
 
**Total hours required: 200
Pay Rate: $30/hour
Project deliverables deadline: May 15, 2018 (can be discussed)**
 
**Qualifications:**
·        Graduate student in fields such as computer science, data visualization, cognitive science, economics, statistics or related fields. Students from other disciplines that involve data analysis and data manipulation may also be a good fit.
·        Experience with mainstream data applications and tools is required (experience with Tableau and familiarity with Python and R is preferred) 
·        Experience working with relational databases (experience with MySQL is preferred)
·        Ability to demonstrate good communication skills to foster productive relationships and collaboration with multiple stakeholders
·        Be self-directed with good time-management skills and should able to pursue tasks with light supervision.
 
 
**Responsibilities:**
·        Identify relevant data, extract, transform and clean appropriate data sets
·        Explore, analyze and visualize selected educational datasets with the goal of understanding factors that influence teaching or learning in the Faculty of Arts. Examples include student survey analysis and temporal analysis of student enrollments to find patterns.
·        Summarize and present findings to stakeholders (oral and written)
 
For inquiries, please contact: [sanam.shirazi@ubc.ca](url)

**Comment by minisciencegirl** [comment]
@sanamsh: Can I close this issue?
