### ISSUE TITLE
R study group meetings

### ISSUE THREAD

**Issue by arorahitesh** [minisciencegirl/studyGroup#170]
Hello Guys

I am a Ph.D. student at UBC and need help with R-language.
I was wondering if you guys meet up for study groups somewhere? I would like to join you guys and learn as well.

Please let me know,

Thanks
Hitesh

**Comment by ttimbers** [comment]
@arorahitesh - Looks like there has been a break in the schedule, but I am keen to get this up and going again on a regular basis! We should set-up a planning session this month and get organized!

**Comment by ttimbers** [comment]
Actually @arorahitesh - I see there have been co-working sessions in May and the next one is June 7th (https://github.com/minisciencegirl/studyGroup/issues/165). Hope to see you there.

**Comment by eacton** [comment]
Hey @ttimbers @arorahitesh  - that thread on coworking is from last year. I am in Toronto now, or I would have followed that notification with something more proactive. :P

**Comment by ttimbers** [comment]
Doh! I got my years mixed up! Let's go back to my original suggestion - how we about get together for a planning meeting? This Thursday at 3:30?

**Comment by minisciencegirl** [comment]
@ttimbers: Can you book a room at your building? I will reach out to the library folks once we've date/ time set up and book our room for us.

**Comment by ttimbers** [comment]
@minisciencegirl - ah, all the good rooms are booked up in ESB (well the ones I can book). Can we book a library room? How did you do that before? If you let me know I can do that!

**Comment by ttimbers** [comment]
@ksedivyhaley - we're continuing the conversation from #165 over here.

**Comment by ksedivyhaley** [comment]
@ttimbers, thanks for keeping me in the loop!

**Comment by minisciencegirl** [comment]
@ttimbers: Just emailed the library folks and Cc'ed you!

**Comment by minisciencegirl** [comment]
First Study Group Meeting of 2018!

I've created an event posting too for this so it should show up on our website. Hope to see everyone there!

Date: Thursday, June 7
Time: 3:30 PM to 4:30 PM 
Room: Koerner Library 216
