### ISSUE TITLE
dyplr: Filtering data if a condition is met by one of the groups

### ISSUE THREAD

**Issue by kelypliu** [minisciencegirl/studyGroup#188]
Hi there, 
I am trying to figure out how to filter data by using a condition that applies to one of the groups.
Here's my data frame:

Gene | expr | group 
------ | ----- |  ----- 
Gene1 | 0 | A
Gene1 | 51 | B
Gene2 | 51 | A
Gene2 | 51 | B
Gene3 | 0 | A
Gene3 | 0 | B
Gene4 | 0 | A
Gene4 | 51 | B

I'd like to keep the genes with at least 50 expr in at least 1 of the groups (keep Gene1, 2, and 4):

Gene | expr | group 
------ | ----- |  ----- 
Gene1 | 0 | A
Gene1 | 51 | B
Gene2 | 51 | A
Gene2 | 51 | B
Gene4 | 0 | A
Gene4 | 51 | B

Here's what I've tried:
`df %>% filter(expr>50 & group=="A" | group=="B")`
or
`df %>% filter(expr>50 & group %in% c("A", "B"))`

But returned with expr<50 filtered out:

Gene | expr | group 
------ | ----- |  ----- 
Gene1 | 51 | B
Gene2 | 51 | A
Gene2 | 51 | B
Gene4 | 51 | B

What am I doing wrong?

**Comment by sagbayani** [comment]
Perhaps using >= 50 rather than > 50?
You want to keep the 50s right?

**Comment by kelypliu** [comment]
No, I want to keep all the ones with >50 expr in either of the group.
I got what I wanted by first get the list of genes that meet the requirement, then filter the data frame with the gene name. 

`gene.sub <- df %>% filter(expr>50 $ group=="A" | expr>50 & group=="B" %>%select(Gene) %>% distinct(Gene)`
`gene.sub<-as.vector(gene.sub$Gene)`
`df.sub<-df%>%filter(Gene %in% gene.sub)`

This way I retrain the rows with expr<50 in one of the groups. 
But I feel like there's a better/faster way to do this. Any ideas?

Thanks!

**Comment by samhinshaw** [comment]
It sounds like you want `group_by()`!

**Comment by wvictor14** [comment]
```
df %>% 
  group_by(Gene) %>% 
  filter(any(expr>50))
```

**Comment by kelypliu** [comment]
‘Any’ did it.

Thanks!

Kelly Liu
Oral Cancer Research, Department of Integrative Oncology, BC Cancer Research Centre
Rm 6-114, 675 West 10th Avenue
Vancouver, BC, V5Z 1L3
E: keliu@bccrc.ca<mailto:keliu@bccrc.ca> | P: 604.675.8000x7617
________________________________
The information contained in the e-mail is intended only for the individual or entity to whom it is addressed. Its content (including any attachments) are confidential and may contain privileged information. If you are not an intended recipient you must not use, disclose, disseminate, copy or print its contents. If you receive this e-mail in error, please notify the sender by reply e-mail and delete and destroy the message.
