### ISSUE TITLE
Some things for the Fall

### ISSUE THREAD

**Issue by SimonGoring** [minisciencegirl/studyGroup#189]
Hey all, the timing was bad for me this summer, but I'd be happy to pitch in for the fall.  I have some more advanced (maybe?) level sessions I'd be happy to lead:

* Continuous Integration for your (R) Markdown papers, making sure your analysis is right every time based on [this blog post](http://www.goring.org/resources/Adding_CI_To_RMarkdown.html).
* [Spatial data with leaflet](http://www.goring.org/resources/Shiny-leaflet-tutorial.html)
* Working with (postgres and graph) databases in R
* Tips and tricks for regular expressions in R (and bash). Could work through something like [this post](http://www.goring.org/resources/regex_bash_libraries.html), where I show how to use regex to automatically install R libraries for a project.

**Comment by sagbayani** [comment]
Hi Simon,

Thanks, I am particularly interested in the first two you’ve listed here (CI for Rmarkdown, and Spatial data with leaflet), so please do keep us posted.

Cheers,
Selina

Selina Agbayani  |  Marine Mammal Research Unit, UBC  |  email: s.agbayani@oceans.ubc.ca<mailto:s.agbayani@oceans.ubc.ca>  |  LinkedIn: https://ca.linkedin.com/in/sagbayani  |   w: http://mmru.ubc.ca/personnel/selina-agbayani/

**Comment by molliejmcdowell** [comment]
I would definitely be interested in attending these sessions -- particularly 1, 3, and 4. Thanks!

**Comment by SimonGoring** [comment]
Still willing to run these, but closing this issue.
