### ISSUE TITLE
MSL Room Bookings

### ISSUE THREAD

**Issue by ksamuk** [minisciencegirl/studyGroup#19]
Looks like we might be able to book the MSL room here:

http://www.msl.ubc.ca/contact/roombooking

**Comment by minisciencegirl** [comment]
Fantastic @ksamuk. The Pharmaceutical Sciences Building also has a pretty large seminar room that we can use for larger sessions.
http://pharmsci.ubc.ca/facilities/room-and-space-rentals/make-booking

**Comment by aammd** [comment]
oh hey @daattali , did you ever figure out if this is easier for you than for people unaffiliated with MSL?

**Comment by daattali** [comment]
no i didn't look into it because I saw that somebody sent out a link that
said they can do it.  I haven't looked at that message though - was it not
doable for any person? I'll look into it if you tell me there's a need for
it :)

---

http://deanattali.com

**Comment by jkbooth** [comment]
I think only MSL dwellers can book rooms in the MSL. I could book a room if we need it.
