### ISSUE TITLE
Zoology R Club

### ISSUE THREAD

**Issue by jstaf** [minisciencegirl/studyGroup#2]
For those interested, there is a weekly R tutorial/club every Tuesday morning @ 9:30 am in Biosciences 4223. 

The Git repository for the tutorial is [here](https://github.com/kazi11/RClub).

This week (tomorrow) we will be covering [the basics of using the UNIX shell/shell scripting](https://github.com/kazi11/RClub/blob/master/learn_to_bash.sh), but we generally cover a new topic every week. If you are interested and feel up to it, everyone is totally welcome to teach a week or three!

Send me an email at stafford@zoology.ubc.ca if you wanted to be added to the email list.

**Comment by jooolia** [comment]
Oh can I get added? I thought I was on the list and received the initial e-mails, but haven't gotten anything in a while. jgustavsen@eos.ubc.ca

**Comment by jooolia** [comment]
Oh can I get added? I thought I was on the list and received the initial e-mails, but haven't gotten anything in a while. jgustavsen@eos.ubc.ca

**Comment by jooolia** [comment]
Oh can I get added? I thought I was on the list and received the initial
e-mails, but haven't gotten anything in a while. jgustavsen@eos.ubc.ca

**Comment by katieannemills** [comment]
@kazi11 that's awesome, sign me up! bill@mozillafoundation.org

Also, seeing as we're all doing the same thing - why don't we promote your events on this website? If that sounds good, @minisciencegirl can add you as a collaborator so you can add your events (instructions are in the README.md file).

**Comment by minisciencegirl** [comment]
Great idea Bill! 

Jeff I added you as a collaborator so that you can post your events.

Instructions here: https://github.com/minisciencegirl/studyGroup#how-to-launch-a-new-event

**Comment by jstaf** [comment]
Seems like a good idea, I'll add it to the website as soon as I get the chance!

**Comment by rozdakin** [comment]
No more Tuesday/9:30am meetings this semester... looking forward to taking part in the new study group though!

**Comment by minisciencegirl** [comment]
Looking forward to learning from everyone! Thanks for collaborating on this project.
