### ISSUE TITLE
R + R Markdown + Git + GitHub

### ISSUE THREAD

**Issue by jennybc** [minisciencegirl/studyGroup#21]
**Time**: Wed, 6/3, 2pm (we have the room until 3:30pm)
**Location**: UBC Life Sciences Institute #1330 

I will be speaking at a small R meeting in late June about the positive, transformative effect that R + R Markdown + Git + GitHub has had in my teaching, most especially in [STAT 545](http://stat545-ubc.github.io). I think a big win for learner and TA and instructor alike.

My talk will be much shorter than a study group meeting, which would also leave some time to just talk about mechanics, i.e. to help people actually get some of this stuff set up, today, on their own machines.

I'd love to practice this talk in front of friends. How does one get "approval" and a date? FYI I'm about to post a second such request for a different talk.

**Comment by stefaniebutland** [comment]
Would love to host this one in the Life Sciences Institute (unless Jenny wants to do it on home turf). I love the theme of impact on teaching & learning. 

I'll defer to others on etiquette / protocol on being greedy & offering to host. 

Cheers
Stefanie Butland

**Comment by katieannemills** [comment]
As per my comments on your other thread - welcome aboard! Seeing as I just suggested 3 June for your other topic, what's your 10 June look like? Or any other dates you like, you tell us.

@stefaniebutland, we can have the talk in LSI on the condition that you provide @jennybc with a bigger room than ecology 224 :)

**Comment by stefaniebutland** [comment]
Bill, how many seats do you think? LSI has diff options I can book based on date availability. 

Pls ping me at my UBC email if a date is shaping up & I haven't yet responded here

Stef

**Comment by minisciencegirl** [comment]
Thanks @stefaniebutland! We can also host a larger group (50 or more) at the Pharmaceutical Sciences building.

**Comment by katieannemills** [comment]
+1 thanks @stefaniebutland; for room size, I was going to guesstimate like 50?

**Comment by minisciencegirl** [comment]
Hi @jennybc: do you have a potential date for this talk? Thanks!

**Comment by jennybc** [comment]
Is there a certain day of week and/or time that is conventional?

**Comment by minisciencegirl** [comment]
We've been doing Wednesday afternoons mostly. Does that work? But we are really flexible and can meet whenever works for your schedule.

**Comment by jennybc** [comment]
How about Wednesday June 3rd for this one? I'm proposing June 10th for the other one. This sequence is more humane re: where I am in the necessary project and prep.

**Comment by minisciencegirl** [comment]
Sounds awesome! Would 2 pm work? I can add it to our events list!

Amy

**Comment by jennybc** [comment]
Sure. Do it!

**Comment by radaniba** [comment]
As all these events are happening at UBC, it makes it harder for outsiders (like me :) ) to commute. Plus events at 2pm-4pm are more convenient to people on campus :( 

That said, is it possible to think about a streaming channel in the room all the events happen ? that way I can at least follow what's happening remotely ?

possible ? not possible ?

**Comment by katieannemills** [comment]
@radaniba I would actually very much like to bring events to BC Cancer; @minisciencegirl, perhaps we can coordinate with VanBUG for future events?

**Comment by jennybc** [comment]
For this particular talk, I need a "workshop-y" vibe. I'd be happy to give another version in a more formal setting (better time, better place, etc.), but my motivation this go 'round is ~50% helping myself practice & develop a talk for a rather unique purpose.

**Comment by minisciencegirl** [comment]
Hi @radaniba, +1 on brining events to BC Cancer. If we have events happening is LSI, we could potentially get streaming to work.

Bill, VanBUG is breaking for the summer. The Dev team is meeting sometime in early June to organize next school year, I will bring it up at that meeting and see what we can do.

**Comment by minisciencegirl** [comment]
Hi everyone! Here is the info for this Wednesday's event:

Time: Wed, 6/3, 2pm (we have the room until 3:30pm)
Location: Life Sciences Institute #1330 
Web: minisciencegirl.github.io/studyGroup

Please note the change from our usual location. 

@jennybc: I will make sure there is a projector and hopefully UBC wifi will work well in that room. Please let me know if there is anything else you need. Thanks!

**Comment by stefaniebutland** [comment]
Life Sciences Institute location is here (via UBC Wayfinding):
http://maps.ubc.ca/PROD/index_detail.php?show=y,y,y,y,y,y&locat1=529
Room 1330 is a 40-person meeting room on ground floor with an entrance from
the West Atrium.

**Comment by jennybc** [comment]
If you want to be in a good position for any hand-on experiments, **if we go down that road (?)**, then I'd recommend:
- RStudio. Update it!
- That should get you recent `rmarkdown`, Pandoc, etc. and is primary reason this is my main install recommendation.
- Git, if you're ready to take that plunge. **Not necessary** to enjoy R Markdown, BTW.
- GitHub account, ditto

Our coverage of setup from STAT 545 is pretty good, so go there for excruciating detail. Caveat: hasn't been updated since last fall yet I don't know of anything that's horribly out of date:

http://stat545-ubc.github.io/topics.html

These topic in particular are relevant:
- [Install R and RStudio](http://stat545-ubc.github.io/block000_r-rstudio-install.html)
- [All the Git and GitHub (and RStudio) things](http://stat545-ubc.github.io/git00_index.html)
- [Test drive R Markdown](http://stat545-ubc.github.io/block007_first-use-rmarkdown.html)

**Comment by aammd** [comment]
MOVED now in room LSC 3
https://twitter.com/billdoesphysics/status/606199962234286080

**Comment by minisciencegirl** [comment]
https://github.com/jennybc/2015-02-23_bryan-fields-talk

**Comment by aammd** [comment]
Here is how you search CRAN on github!! Thanks @jennybc !
https://gist.github.com/jennybc/4a1bf4e9e1bb3a0a9b56

**Comment by morien** [comment]
Jenny, thanks so much for giving this talk! I haven't used R with markdown
or knitr before, so I learned a lot of useful things today. I have always
used emacs for coding in R, and I'm totally sold on using these tools
together now.

**Comment by jennybc** [comment]
@morien You are most welcome!

Thanks to all for being so interested and willing to discuss the content and talk prep. This was very helpful for me and I hope I managed to convey some useful info to you as well.
