### ISSUE TITLE
R + Google spreadsheets

### ISSUE THREAD

**Issue by jennybc** [minisciencegirl/studyGroup#22]
I will be speaking at [useR! 2015](http://user2015.math.aau.dk) about a package recently developed by Joanna Zhao and myself: [`googlesheets`](https://github.com/jennybc/googlesheets). I also expect us to submit to CRAN in late May or sometime in June (definitely before useR!).

It turns out the ability to hook R up to Google Sheets as a data store is pretty cool! There are many ways to feed Google Sheets with interesting data from the internet, for example. We will also demonstrate how to combine data in Google Sheets with R goodness via Shiny apps.

I'd love to practice this talk in front of friends. How does one get "approval" and a date? FYI I just posted a second such request for a different talk.

**Comment by BernhardKonrad** [comment]
Github needs a "Like" button! I look forward to how this project turned out.

**Comment by katieannemills** [comment]
@jennybc, consider yourself indefinitely approved :) - this group is community run, and absolutely everyone is welcome to take the reins for a talk.

Whatever time works for you works for us - but we've got talks for the rest of May - how does your June 3 look?

**Comment by jennybc** [comment]
June 3 looks a wee bit early? Perhaps that is the point: to force myself to procrastinate less. But maybe a week later would be better for all.

**Comment by katieannemills** [comment]
No problem! Like I said in #21, the 10th is all yours if you want it; we could push the other talk off another week (or whenever it suits you). Let us know when you know for sure - looking forward to it!

**Comment by aammd** [comment]
:+1: this sounds REALLY exciting! I'd point out that we can certainly have >1 talk/week if we want

**Comment by minisciencegirl** [comment]
So excited about this! Thanks @jennybc!

**Comment by jennybc** [comment]
I'd love to claim Wed June 10th for this. OK?

**Comment by katieannemills** [comment]
Absolutely! @minisciencegirl, can you please coordinate with Stephanie to book a room, nominally 3 PM on the 10th? Once the coordinates are confirmed, plz let us know so we can edit the top post in this thread and announce. Thanks all, very looking forward to this!

**Comment by aammd** [comment]
ping! do we have a room for this, @minisciencegirl , @BillMills et @jennybc ?

**Comment by minisciencegirl** [comment]
Yes! It's LSI 1330. I will double check with Stefanie

**Comment by aammd** [comment]
oh awesome. 3pm, yes?

**Comment by jennybc** [comment]
My calendar says LSI 1330 tomorrow June 10 at 3pm.

**Comment by stefaniebutland** [comment]
Confirmed!

Stef
