### ISSUE TITLE
New 'lessons' directory

### ISSUE THREAD

**Issue by katieannemills** [minisciencegirl/studyGroup#25]
Hey all,

Just wanted to point your attention at the new [lessons directory](https://github.com/minisciencegirl/studyGroup/tree/gh-pages/lessons) in our repo - this contains notes / links to notes for the lessons that have been taught so far that have provided them (sorry if I missed any! send a PR / ping me here!). It would be awesome if people leading demos would add to this repo as they teach, so we can keep a collection of all the great work everyone is doing.

**Comment by radaniba** [comment]
nice move, good to keep track of the lessons, can we contribute with some 'not yet scheduled' lessons ?

**Comment by katieannemills** [comment]
absolutely!
