### ISSUE TITLE
Rstudio Webinar popcorn viewing

### ISSUE THREAD

**Issue by aammd** [minisciencegirl/studyGroup#26]
Hello everyone!
Let's band together and watch an [Rstudio webinar](http://pages.rstudio.net/Webinar-June2015_Registration.html), live!

I've already registered (so no need to register yourself) and reserved our usual room in BRC 224! I can project the presentation onto the screen so we can all hear!

**Comment by aammd** [comment]
It's going to be June 10th
at :coffee: :coffee: **_8 am**_ :coffee: :coffee:

**Comment by katieannemills** [comment]
Ha! Let's do this.

**Comment by rozdakin** [comment]
I'm down

**Comment by ksamuk** [comment]
I'll be there.

**Comment by aammd** [comment]
Here are the links to all the packages that Hadley will be discussing

https://github.com/rstats-db/DBI
https://github.com/hadley/xml2
https://github.com/jeroenooms/jsonlite
https://github.com/hadley/haven
https://github.com/hadley/readxl
https://github.com/hadley/readr

Do you see that! Between them these packages can ingest all the world's common data formats. I think this is going to be a really useful seminar!

**Comment by minisciencegirl** [comment]
Sounds good!

**Comment by Lauramorillas** [comment]
I'll try to be there too!

**Comment by jstaf** [comment]
I'm actually really excited for this. (Aside from the 8am part.)

**Comment by arielframe** [comment]
I'm at the door facing the museum to get into BRC and it's locked. Can anyone let me in?

**Comment by andrebeu** [comment]
Cant find the room

**Comment by andrebeu** [comment]
Brc as in brain research centre ubc?

**Comment by minisciencegirl** [comment]
No. It's the Biodiversity Research centre. Right by the whale.

**Comment by Lauramorillas** [comment]
Can we access from our own computer or we need to go there?

**Comment by minisciencegirl** [comment]
You should be able to. I think you may need to register prior.

**Comment by myuen** [comment]
They have already reached capacity with the software they host the 
webinar.  The presentation will be made available in 48 hours.

**Comment by minisciencegirl** [comment]
Also the session is recorded, so you should be able to access it later on R Studio website. 

Or here: https://github.com/rstudio/webinars

**Comment by Lauramorillas** [comment]
Thanks!

**Comment by aammd** [comment]
Here's the slides and code from the talk !! https://github.com/rstudio/webinars/tree/master/11-Getting-Data-into-R
