### ISSUE TITLE
R packages for CodersCrowd

### ISSUE THREAD

**Issue by radaniba** [minisciencegirl/studyGroup#27]
Hello guys,

You probably know that CodersCrowd is built on top of docker images to serve code into its members. I am rebuilding the CodersCrowd docker images responsible for running R packages and was thinking this group is perfect to ask for contributions to list the most used R packages that we can think of, in order to make it available for people.

After building the Docker File I can push it back in production which means anyone can run any R code with no configuration on the browser

Any package wanted ? just let me know

Rad

![cdrcrowd_r_code](http://s12.postimg.org/ygx0vo4r1/rstat.gif)

**Comment by katieannemills** [comment]
So far, we've had lessons on:
- dplyr
- magrittr
- knitr
- ggplot2

so that's a start - R ppl, any other mission critical R packages you can think of?

**Comment by jennybc** [comment]
Are you already aware of [Rocker](https://github.com/rocker-org/rocker)? This project includes an [official R image for Docker](http://dirk.eddelbuettel.com/blog/2014/12/19/) as well as some common use cases. For example, above it looks like you're well on your way to the [Hadleyverse container](https://registry.hub.docker.com/u/rocker/hadleyverse/).

**Comment by radaniba** [comment]
Thanks @BillMills and @jennybc 

Yep I am aware of Rocker but didn't really dig into it, it sounds like a much better solution to get started with the Dockerfile already developed in Hadleyverse and I will wait a little bit while sone other suggestion keep coming here, even though it looks like an excellent start, I will literally replace the current support of R at CodersCrowd with this one.

Any interested testers when it is up and running ?

Thx

**Comment by jstaf** [comment]
You'll probably want to include `reshape2` and `biomaRt`. Those are probably the two most relevant R packages that I use a lot.

**Comment by morien** [comment]
I used limma a lot in the past. I haven't heard many people talk about it
lately though. I guess fewer people are using microarrays these days. Is
there interest in including it?

**Comment by radaniba** [comment]
Thanks @kazi11 will definitely add `reshape2` and `biomaRt`
@morien `limma` is useful I know a lot of people using it, worth adding as well, thank you for the suggestion
