### ISSUE TITLE
Using R for creating open, repeatable State of Environment indicators

### ISSUE THREAD

**Issue by stephhazlitt** [minisciencegirl/studyGroup#28]
Hi folks,

@minisciencegirl and @BillMills invited us to come and share our experience using R as a primary tool for our data work flows - getting, cleaning, analyzing and publishing environmental reporting indicators. I hope this suggested day/time works.

Cheers, Stephanie

Presentation & Discussion: Using R for creating open, repeatable State of Environment indicators

When: 3:30pm, Wedneday, June 24th
Where: Biodiversitiy Building rm 224, UBC

[Environmental Reporting BC](http://www.env.gov.bc.ca/soe/) is the Province’s web-based approach to state of the environment reporting, providing timely, open, and dynamic reports on key environmental topics. We are making, in partnership with [DataBC](http://www.data.gov.bc.ca/), the 'ingredients' -- the environmental [data sets](http://catalogue.data.gov.bc.ca/dataset?download_audience=Public) and [R code](https://github.com/bcgov) -- open and available for our audiences. We will talk about how [R](http://www.r-project.org/) has been a catalyst for enabling a more open and repeatable work flow.

Speakers: @ateucher and @stephhazlitt

**Comment by minisciencegirl** [comment]
Hi Stephanie,

This is so awesome! We are all very excited to meet you and hear about the cool stuff that’s happening @DataBC.

Once we have a room booked, I will post the event to our website: minisciencegirl.github.io/studyGroup

Thanks!

Amy

**Comment by katieannemills** [comment]
oooo I'm at a conference that day, I'm sorry I'll miss it! Will there be a hands-on component people can follow along with? I think a lot of people will be interested in this talk either way, but all the better if there's something for people to dig into. Wish I could be there!

**Comment by katieannemills** [comment]
how are we doing on that room? Would love to get this on the website and let people know soon!

**Comment by minisciencegirl** [comment]
Hi Bill,

It's going to be in our usual room in BioDiv 224. 

Thanks!

**Comment by katieannemills** [comment]
cool, I just added it to the website - time to start a-tweetin'!

**Comment by ateucher** [comment]
In addition to talking about our workflow and common tools that we use, I thought I might give a short tutorial on working with geospatial data in R, which we end up doing a lot in our work. I'll base it loosely on this [lesson](https://github.com/BillMills/BCenviroLessons/blob/master/data_exploration/explore_grizzly_data.md) and our [bcmaps](https://github.com/bcgov/bcmaps/) package.

If people want to follow along, you will need several packages installed:
- [`sp`](http://cran.r-project.org/web/packages/sp/index.html) - This should install with no problems on any platform with `install.packages("sp")`
- [`rgdal`](http://cran.r-project.org/web/packages/rgdal/index.html) and [`rgeos`](http://cran.r-project.org/web/packages/rgeos/index.html) - These package requires the gdal and geos libraries to be installed on your system. 
  - If you're on Windows (and usually on a Mac), you should be able to just install them with
     `install.packages(c("rgdal", "rgeos"))`; the required libraries will be included. 
  - It _should_ also just work on the Mac, but not always. If it doesn't work you will need to install gdal on your system. If you use [Homebrew](http://brew.sh/), you can install gdal by typing `brew install gdal` in a terminal window. If you don't use Homebrew, you can try following the instructions [here](http://tlocoh.r-forge.r-project.org/mac_rgeos_rgdal.html) (disclaimer - I haven't tried it).
  - If you're on Linux, you will have to figure out the best way to install the dependencies. @aammd might have some tips?
- [`bcmaps`](https://github.com/bcgov/bcmaps/) - This isn't available on CRAN, but can be installed using the [`devtools`](https://github.com/hadley/devtools/) package:

``` r
install.packages("devtools") # if not already installed

library(devtools)
install_github("bcgov/bcmaps")
```

**Comment by ateucher** [comment]
This could contribute to the R Utility Belt, as @stephhazlitt mentioned [here](https://github.com/minisciencegirl/studyGroup/issues/29#issuecomment-114555029).

**Comment by minisciencegirl** [comment]
Thanks for the detailed instructions, @ateucher!

**Comment by ateucher** [comment]
Thanks everyone for the great chat yesterday. The lesson we worked through on spatial data is [here](https://github.com/ateucher/BCenviroLessons/blob/ubc-rstats/data_exploration/explore_grizzly_data.md).

To follow-up, here are few good resources on using R for geospatial work:
- A good, pretty comprehensive tutorial here: https://github.com/Robinlovelace/Creating-maps-in-R
- This is a really nice guide on [Coordinate Reference Systems](https://www.nceas.ucsb.edu/~frazier/RSpatialGuides/OverviewCoordinateReferenceSystems.pdf) and how they are used in R
- The [R Spatial Task View](http://cran.r-project.org/web/views/Spatial.html) - overview of the slightly overwhelming number of packages for working with spatial data (although a quick scan makes me think it's a bit out of date)
- If you work with spatial data on the web, geojson is a common format. I've been helping out a bit with an rOpenSci package called [geojsonio](https://github.com/ropensci/geojsonio) for converting to/from geojson and other formats
- [R Spatial Tips](http://spatial.ly/r/)
