### ISSUE TITLE
The R Utility Belt

### ISSUE THREAD

**Issue by katieannemills** [minisciencegirl/studyGroup#29]
So - in [this super scientific twitter survey](https://twitter.com/billdoesphysics/status/609099324601937920), I asked what people thought would make up a good 'beginner's toolkit' for general scientific programming in R. The most popular answers\* (in descending order) were:
- ggplot2 ([thanks](https://gist.github.com/kazi11/22fac11fecd5dd5121b2) @kazi11 )
- dplyr + magrittr ([thanks](https://github.com/ksamuk/dplyr_magrittr_demo) @ksamuk )
- stringr + lubridate
- multcomp + `lm()` + `glm()`
- tidyr + reshape2 ([thanks](http://remi-daigle.github.io/tidyr_reshape2_lesson/) @remi-daigle )
- knitr + rmd (thanks @eacton )

(\* a few new items tacked on since the twitter survey - this will continue to evolve based on this discussion!)

We've hit a bunch of those already at UBC (go team!) - I'd like to have a go at the rest of the list. If we get a routine down for all of these, that'll make a nice 8(ish)-session intro to R we can run for newcomers in a semester, with plenty of room to inject topic-specific lessons like we've had from @jennybc, @rozdakin, and the forthcoming bioconductor lesson, open sessions etc.

So, a few questions and to-dos if you're interested:
- **Making / Finding Lessons**: the UBC team has made three fantastic lessons (linked above) for this material already; making the rest is one option, but I bet there are tutorials on all of these out there somewhere that we can remix, too. If you have a favorite or if you write your own, please add a link here! Also, don't be shy to recommend alternatives; for example, I think @remi-daigle will be combining reshape2 and tidyr into one lesson for [the SFU group](https://ttimbers.github.io/studyGroup/) next month.
- **Running these lessons**: if you use any of these packages, please jump in to run a session! At UBC, we're going to be doing an R-focused Software Carpentry workshop at the end of July, and I'd love to be able to follow that up with these sessions afterwards. For our sister groups (nudge nudge, @mbonsma @ttimbers @dataopenspace ), if you're looking for session ideas, consider having a go at this list and letting us know how it goes; or, make your own menu on whatever topic your community would like, and tell us about that, too.
- **Ideas & criticisms**: and as always, what does everyone think? Does this list make sense? What would you change? All feedback is good feedback!

**Comment by rozdakin** [comment]
What about basic regression analyses? (base R, but using bits and pieces from packages like multcomp)

Also: lattice (opinions on ggplot2 v lattice <a href="http://stackoverflow.com/questions/2759556/r-what-are-the-pros-and-cons-of-using-lattice-versus-ggplot2">here</a>)

**Comment by ttimbers** [comment]
+1 to basic stats in R. The input and output are not super intuitive to
beginners, and a lesson on this could be useful. I'd say in that lesson we
should cover lm(), glm() and yes, the multcomp package. If you learn these
3 things you can do a lot.

Cheers,
Tiff

**Comment by remi-daigle** [comment]
+1 to basic stats in R for me too! Once the beginners understand the basic formula (I found this non-intuitive when first learning) for the stats analysis in lm() or glm(), it becomes alot easier to transition to a different test on their own.

Yes, as @BillMills mentioned, I am planning a lesson combining tidyr and reshape2 since I find them complementary if not repetitive in terms of function (Although I will likely (re)discover some of the finer differences as I prepare the lesson). Can you think of any reason not to combine them?

Cheers,
Remi

**Comment by katieannemills** [comment]
ok cool, sounds good! That sounds pretty generically important, so let's add it to the list. I'd like to keep it to _about_ 8 things (13 week semester == 8 scheduled lessons + 5 flex slots), but some of them might get combined into single lessons; speaking of...

@remi-daigle: nope no specific reason at all not to combine tidyr + reshape2; in fact they sound like they make a lot of sense together. I'll repeat my eternal generic advice of not cramming too much into one solitary hour and going slow enough to make sure your students are keeping up and having a chance to work on some challenge problems - but we can split them up later if what you have planned ends up being too tight. Looking forward to it!

(edit: now that I look at it a bit, stringr+lubridate look like they could go together too, in a text munging lesson)

**Comment by jstaf** [comment]
I might suggest adding aov(), t.test(), and TukeyHSD() to the "basic stats" lesson. Those are probably the most relevant tests for biology.

**Comment by aammd** [comment]
I'd love to work on a stringr lesson. We've really been getting along well lately :sweat_smile:

**Comment by katieannemills** [comment]
@kazi11 yes, awesome! I would however package those up in a bio-specific list (which I'd also very much like your input on) - the idea is, we have a core list (this one) that spans disciplines as much as possible, and other modular ones people can mix in to flavour it for their specific field.

@aammd awesome, that would be fantastic :D

**Comment by stephhazlitt** [comment]
Another modular list could be around spatial/mapping tools in R (some useful/core packages: rgeos, rgdal, maptools, rastor). Likely a useful toolkit to many scientists re: data visualization and spatial analyses and for many you can do it all in R (e.g. no need to move into GIS tool environment). I am just learning and find that unlike many areas this is one with less on-line help available. Just a thought.

**Comment by katieannemills** [comment]
@stephhazlitt awesome, that's a fantastic start for a GIS list. I'm going to pull together field-specific lists shortly, and this will definitely be a starting point for GIS. Thanks!

**Comment by remi-daigle** [comment]
@stephhazlitt yeah! I was just talking to @BillMills about this last week, I have also been doing alot of GIS/mapping in R recently and I'm really finding it useful and powerful. I'd love to work on this lesson as well whenever it happens!

**Comment by stephhazlitt** [comment]
@BillMills I forgot to include the sp package in the list!

**Comment by ateucher** [comment]
I don't want to hijack the thread and make it all about spatial, but the short tutorial we ran through yesterday is [here](https://github.com/ateucher/BCenviroLessons/tree/ubc-rstats/data_exploration), and a follow-up comment with some other resources is [here](https://github.com/minisciencegirl/studyGroup/issues/28#issuecomment-115326265).

**Comment by katieannemills** [comment]
These are awesome ideas! I just made a new thread for figuring out a spacial module, which would be an awesome awesome first add-on module - great work!

Back to the 'core topics' list above, it looks like we might have:
- @aammd on stringr
- @remi-daigle on tidyr + reshape2

Which leaves us still to figure out:
- plyr
- lubridate
- multcomp + `lm()` + `glm()`

Remember, we can grab lessons on these from out there on the web, if people have ones they like; no need to write them all ourselves! The only guideline to shoot for is 1 hour long with lots of hands-on opportunities.

**Comment by radaniba** [comment]
I think this is relevant to this issue (if anyone is interested in creating a big infographic out of this issue ? maybe ?)

Refs : 

[Powerful R libraries for data analysis ](http://discuss.analyticsvidhya.com/t/download-the-complete-list-of-powerful-r-libraries-for-data-analysis/2624) (checkout the pdf attached in the article, there is a nice table in page 2)

![infographics123](https://cloud.githubusercontent.com/assets/1666443/9125162/8d5640de-3c52-11e5-935a-f4564590c58f.jpg)

**Comment by katieannemills** [comment]
@radaniba whoa that's awesome! This is a great '++' resource for the Utility Belt; like if people want to carry on past the 8(ish) lessons in the Belt, this is a great way forward.

**Comment by dataopenspace** [comment]
Awesome! These lessons look great. We plan to discuss them at our Study Group. We have a lot of total beginners so I've been introducing them to the basics first.

**Comment by katieannemills** [comment]
@dataopenspace that's awesome, let me know how I can help, and if there are lessons / webcasts / other materials I can help share back with the rest of the Study Group community! As you can see, in the very top post in this thread, a bunch of the Utility Belt lessons still need links to notes / lesson plans behind them, so if you teach any of these topics and would like to share, please let me know!

**Comment by dataopenspace** [comment]
@BillMills Absolutely. That sounds great!

**Comment by minisciencegirl** [comment]
Hey Bill, should we resurrect this issue and update based on some of the stuff we've covered this summer?

**Comment by katieannemills** [comment]
@minisciencegirl absolutely! I would love to see people lead sessions on all the units we haven't covered yet; what updates did you have in mind?

**Comment by minisciencegirl** [comment]
I am going to try out some bioconductor tools for my genomics work. Just saw this link too https://www.bioconductor.org/help/workflows/ and thought it might be interesting. @kazi11 @ttimbers @eacton @rozdakin @eacton: would love some help with this if you are able and would love any input.

The other thing that I realized is we have had some great sessions on lattice/ggplot2, loops, making packages etc that we can include in the utility belt if people are open to sharing their lessons.

**Comment by tinyheero** [comment]
Coursesa has a bioconductor course:

http://kasperdanielhansen.github.io/genbioconductor/

Looks really good. Might be worth going through this and then running a few sessions about it after.

**Comment by minisciencegirl** [comment]
Wow this looks amazing @tinyheero!! Wanna help me with some of this stuff?

**Comment by tinyheero** [comment]
Sure. Need to go through all the material myself first. Maybe in a month or two we can run some session.

**Comment by minisciencegirl** [comment]
Sounds good - same here. We should also loop in @ksamuk re GenomeRanges

**Comment by jstaf** [comment]
I could potentially do something on `reshape2` (reshaping, handling data), but have no idea how `tidyr` works. 

A little bit of commentary regarding Bioconductor- there's a few packages advertised as being able to perform really heavy-duty stuff like process sequencing alignments/BAM files, but they're extremely slow relative to some of the non-R tools out there that do the same thing. Don't use them if speed is an issue (we're talking extra days worth of computer time here).

**Comment by lmguzman** [comment]
Hey @BillMills so what is going on with this? how are the sessions running?

**Comment by katieannemills** [comment]
We're waiting for a hero to emerge and lead sessions on the other topics not yet covered (hint hint nudge nudge :) - looking forward to seeing them all done!

**Comment by lmguzman** [comment]
nudge nudge received :) but I thought it was a series that was going to be give on a "continuous" basis. What are the topics that are left to be done? (Sorry the thread is messy and there is lots of info :S)

**Comment by katieannemills** [comment]
Right! It's as continuous as any volunteer project (so, like, we continue when someone feels like it :) - I've been linking the notes to lessons that have been done on the top post of the thread as they happen, so the ones left are:
- plyr
- stringr
- multcomp + lm() + glm()
- lubridate

And perhaps knittr since we did that once, but don't have any notes from it.

**Comment by minisciencegirl** [comment]
Hey @kazi11: Do you want to do a co-teaching session on reshape2 and tidyr? @jennybc has a great #STAT545 lecture on tidying data and we can use library(EDAWR) as our messy dataset. Late November works for me if that schedule works?

@aammd & @lmguzman: Are you guys interested in running a session on stringr/ lm()/ glm() sometime in late November or December??

**Comment by lmguzman** [comment]
Yeah, I can do december. Maybe the week after the 4th, or is that too late?

**Comment by minisciencegirl** [comment]
That’s perfect timing! Thanks Melissa!

**Comment by jstaf** [comment]
I might be able to do one on reshape2 sometime in late November/early December depending on thesis scheduling (if someone else does the tidyR part). I'll keep you updated if the timing works out!

**Comment by katieannemills** [comment]
@kazi11 awesome, let's do just before @lmguzman's around then!

**Comment by jstaf** [comment]
Okay, I'll look at the schedule and see what works. If no one's available for tidyR, I may just cover some general-purpose data handling tricks (logical indexing, regular expressions, etc.).
