### ISSUE TITLE
Gitter or Slack for this group

### ISSUE THREAD

**Issue by radaniba** [minisciencegirl/studyGroup#30]
Most of the time I want to share things that are relevant to this group but these are not issues. It would be great if we can use Slack or Gitter for live discussion

I use slack for CodersCrowd (coderscrowd.slack.com) if people want to try it please email me and I will send invitations

Gitter is good too, but Slack has more features

Any move in that direction ?

Cheers

**Comment by katieannemills** [comment]
+1 gitter if people are interested in a chat room (slack is great, but it's just one more thing to sign into).

**Comment by katieannemills** [comment]
closing re: #46
