### ISSUE TITLE
Lattice vs ggplot

### ISSUE THREAD

**Issue by lmguzman** [minisciencegirl/studyGroup#35]
Where: Biodiv 224 
When: Wednesday 8th of July @ 3pm
Dependencies: 

``` r
install.packages('lattice')
install.packages('ggplot2')
install.packages('gapminder')
```

Im going to go over the grammar and syntax of both ggplot and lattice, do a practice plots and talk about the differences/advantages or each.

**Comment by katieannemills** [comment]
Thanks for this, @lmguzman! Let us know if / when there are notes available, lots of people will totally be into this.
