### ISSUE TITLE
Data for Docs: just an introduction 

### ISSUE THREAD

**Issue by lomaxboydphd** [minisciencegirl/studyGroup#36]
Hi R Gurus, 

So excited to have found your group. I'll be visiting Vancouver on a year long fellowship to work with the National Film Board on developing approaches to use open data in documentary storytelling. The NFB is doing amazing interactive work and I think it's time to use live data in the creative process. I'll be producing a series of mini-documentaries using a combination of ethnographic approaches and social network analytics (R!) to better understand how the public learns about science. Hope learn more about your group! Go #openscience! 

~ Lomax

**Comment by katieannemills** [comment]
Hi @hackmyscience 

Welcome to Vancouver and to Study Group - what an awesome project! Did you see the [summer project](https://github.com/mozillascience/studyGroup/issues/16) I proposed for Study Groups worldwide? I'm challenging everyone to come up with ways to use and learn about open data, and this sounds like a great example of that. A few questions to get things started:
- have you identified the data you want to use yet?
- any guesses on what R packages or strategies you want to use to do your network analysis? (we can figure this out together, too).
- (maybe for a bit down the road) it would be interesting to think about what kind of tool, data format or other strategy would make doing projects like this as convenient as possible for filmmakers.

When are you getting to Vancouver? You should definitely come meet people at [Hacky Hour](https://github.com/minisciencegirl/studyGroup/issues/34) if you're in town (sadly I won't be but everyone else will) - let me know what you think!

**Comment by lomaxboydphd** [comment]
Go excited to have found your R Study Group in Vancouver. The sumer project
drive sounds like a great community initiative; will there be a similar one
in the Fall or will the summer projects be ongoing?

Let me go ahead an answer your questions point by point:
- In terms of data, there are several options that I would like to
  explore, including (1) twitter connections that are probably available
  through the API, (2) hyperlink connections between topical blog posts, and
  (3) survey-based data that I may collect during the course of my research.
- The R packages 'igraph' and 'statnet' perform the heavy lifting for
  the social network analysis part, but translating their outputs into a form
  that can readily interpreted by a web browser is an issue I would love
  community feedback on.
- Filmmakers, especially those with a social issue focus, are
  very interested in measuring the impact of their projects AND they are
  starting to venture into the interactive online space, where the
  web browser is the new artistic canvas. The opportunities to combine data
  with other visual media in a dynamic and 'live' way are endless. This
  was the major motivation behind my Fulbright to work with the interactive
  team at the NFB. Tools that enable the easy collection, analysis, and
  visual rendering of data are the three pillars that artists are going to
  care about. For instance, I am interested in public risk perceptions of
  science. What if I could create a workflow that analyzed influence networks
  online for how information flows across twitter. This connectivity map
  could be  integrated into a larger documentary project that explored
  community stories around, say GMOs or evolution of climate change, or
  vaccination. The data visualization would be live, interactive, and more
  than just data representation - it could exploratory and provide novel
  insights into how communities share information across time. Lots more is
  possible with live environmental data for projects that explore climate
  issues. The point is that data in documentaries no longer has to be static,
  let it live, and liberate the databases!

Okay, I've gone on long enough. Thanks for your thoughtful email. I look
forward to connecting with your group when I arrive in Sept!

All my best,
Lomax

On Sat, Jul 4, 2015 at 1:09 PM, Bill Mills notifications@github.com wrote:

> Hi @hackmyscience https://github.com/hackmyscience
> 
> Welcome to Vancouver and to Study Group - what an awesome project! Did you
> see the summer project
> https://github.com/mozillascience/studyGroup/issues/16 I proposed for
> Study Groups worldwide? I'm challenging everyone to come up with ways to
> use and learn about open data, and this sounds like a great example of
> that. A few questions to get things started:
> - have you identified the data you want to use yet?
> - any guesses on what R packages or strategies you want to use to do
>   your network analysis? (we can figure this out together, too).
> - (maybe for a bit down the road) it would be interesting to think
>   about what kind of tool, data format or other strategy would make doing
>   projects like this as convenient as possible for filmmakers.
> 
> When are you getting to Vancouver? You should definitely come meet people
> at Hacky Hour https://github.com/minisciencegirl/studyGroup/issues/34
> if you're in town (sadly I won't be but everyone else will) - let me know
> what you think!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/minisciencegirl/studyGroup/issues/36#issuecomment-118535062
> .

## 

_Lomax Boyd, PhD_
Website: lomaxboyd.com
Twitter: lomaxboyd
Skype: lomax.boyd

**Comment by jennybc** [comment]
Hi @hackmyscience,

An early welcome to Vancouver and to our R community!

Your project sounds really interesting. I'm away for a couple of weeks but look forward to meeting you when I return. I know @gaborcsardi, the developer of igraph, so could maybe help with some sort of collaboration or whatnot. Another local you should connect with is @rich-iannone who has created the excellent and beautifully documented [DiagrammeR](http://rich-iannone.github.io/DiagrammeR/) package for viewing graphs. Personally, I'm quite interested in helping to connect things together and construct effective workflows. So perhspa there's some common ground and interests in here somewhere.

Cheers, Jenny

**Comment by lomaxboydphd** [comment]
Hi Jenny,

Thanks so much for your message and suggestions. The DiagrammeR package
looks incredibly awesome. It's javaScript aspects make it seems like it
would play well with any browser-rendered projects, which at the NFB
Interactive Studio will be all of them! I'm very excited about
the opportunity to bring these techniques into a production environment so
that something beautiful, visceral, and informative can be created.

I too am quite interested in bringing an informatic workflow approach to
our projects, which are traditionally locked in the editing suite and
rolled out for posterity. I think the ability to have dynamic integration
with ever-changing information sources will be well received in
the socially-oriented filmmaker community.

Looking forward to connecting with everyone is September.

All my best,
Lomax

On Sat, Jul 4, 2015 at 4:26 PM, Jennifer (Jenny) Bryan <
notifications@github.com> wrote:

> Hi @hackmyscience https://github.com/hackmyscience,
> 
> An early welcome to Vancouver and to our R community!
> 
> Your project sounds really interesting. I'm away for a couple of weeks but
> look forward to meeting you when I return. I know @gaborcsardi
> https://github.com/gaborcsardi, the developer of igraph, so could maybe
> help with some sort of collaboration or whatnot. Another local you should
> connect with is @rich-iannone https://github.com/rich-iannone who has
> created the excellent and beautifully documented DiagrammeR
> http://rich-iannone.github.io/DiagrammeR/ package for viewing graphs.
> Personally, I'm quite interested in helping to connect things together and
> construct effective workflows. So perhspa there's some common ground and
> interests in here somewhere.
> 
> Cheers, Jenny
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/minisciencegirl/studyGroup/issues/36#issuecomment-118551072
> .

## 

_Lomax Boyd, PhD_
Website: lomaxboyd.com
Twitter: lomaxboyd
Skype: lomax.boyd

**Comment by katieannemills** [comment]
hi @hackmyscience,

Great, sounds good - since you've got some packages as well as some technical goals pretty well articulated there, we can try to find some people to lead lessons on those tools; this project could lend itself well to a work-along or even a focused sprint, too. We'll pull some things together in the fall when you arrive, looking forward to it.

**Comment by lomaxboydphd** [comment]
Hi Bill,

I wanted to touch base with you as I'll be arriving in Vancouver in just a
few weeks! Although my Fulbright Fellowship is technically for 10 months, I
feel like the time is going to zip by.

How would you like to proceed with setting up a time for scheduling those
work-alongs or focused sprints you mentioned? I'm not sure how your groups
prefers to work and schedule things, but I am extremely excited to work
with everyone on this "experiment" in new media and data science. A
collaboration of this kind has never been done to my knowledge.

Jenny Bryn also generously suggested a few names that could lend some
valuable insight. I could also write up a little summary statement if you
think that would be helpful.

Cheers,
Lomax

On Mon, Jul 6, 2015 at 1:40 PM, Bill Mills notifications@github.com wrote:

> hi @hackmyscience https://github.com/hackmyscience,
> 
> Great, sounds good - since you've got some packages as well as some
> technical goals pretty well articulated there, we can try to find some
> people to lead lessons on those tools; this project could lend itself well
> to a work-along or even a focused sprint, too. We'll pull some things
> together in the fall when you arrive, looking forward to it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/minisciencegirl/studyGroup/issues/36#issuecomment-118935524
> .

## 

_Lomax Boyd, PhD_
Website: lomaxboyd.com
Twitter: lomaxboyd
Skype: lomax.boyd

**Comment by katieannemills** [comment]
let's start with #48 - the creator of DiagrammeR will be leading a session at UBC on Sept 25, which will be an opportunity for you to check out that tool as well as meet some people and talk more about how to move forward. Looking forward to it!

**Comment by jennybc** [comment]
Let's plan something around this talk .... before or after
cc @rich-iannone

**Comment by minisciencegirl** [comment]
beer at Koerner's?

**Comment by rich-iannone** [comment]
Beer at Koerner's? Hells yeah!

**Comment by jennybc** [comment]
@hackmyscience You in?

**Comment by lomaxboydphd** [comment]
I'm in!

On Sat, Sep 19, 2015 at 11:53 AM, Jennifer (Jenny) Bryan <
notifications@github.com> wrote:

> @hackmyscience https://github.com/hackmyscience You in?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/minisciencegirl/studyGroup/issues/36#issuecomment-141682963
> .

## 

_Lomax Boyd, PhD_
Website: lomaxboyd.com
Twitter: lomaxboyd
Skype: lomax.boyd

**Comment by lomaxboydphd** [comment]
Hi all,

Not sure if I'm gonna be able to make it tonight, I vastly underestimated
the commute time from Gastown.

On Sat, Sep 19, 2015 at 10:59 PM, Lomax Boyd, PhD lomax.boyd@gmail.com
wrote:

> I'm in!
> 
> On Sat, Sep 19, 2015 at 11:53 AM, Jennifer (Jenny) Bryan <
> notifications@github.com> wrote:
> 
> > @hackmyscience https://github.com/hackmyscience You in?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/minisciencegirl/studyGroup/issues/36#issuecomment-141682963
> > .
> 
> ## 
> 
> _Lomax Boyd, PhD_
> Website: lomaxboyd.com
> Twitter: lomaxboyd
> Skype: lomax.boyd

## 

_Lomax Boyd, PhD_
Website: lomaxboyd.com
Twitter: lomaxboyd
Skype: lomax.boyd

**Comment by rich-iannone** [comment]
Come anyway! It don't matter if you're late.
