### ISSUE TITLE
Index redirection broken

### ISSUE THREAD

**Issue by radaniba** [minisciencegirl/studyGroup#39]
Hello folks

just tried to display the index of http://minisciencegirl.github.io/ and it give a nice 404 page

![screen shot 2015-07-13 at 4 01 52 pm](https://cloud.githubusercontent.com/assets/1666443/8662841/c0cfde30-2978-11e5-9902-6e67cfc0d271.png)

cheers

Rad

**Comment by ttimbers** [comment]
You need to add the /studyGroup

This should work: http://minisciencegirl.github.io/studyGroup/

**Comment by radaniba** [comment]
Thanks @ttimbers 

Yes I know but wanted to point that some redirection should be added to index in case people just want to land on the homepage :)

**Comment by katieannemills** [comment]
See [this issue](https://github.com/mozillascience/studyGroup/issues/11) - gold star for anyone who solves this :)

**Comment by radaniba** [comment]
Ok ! I have a solution for this one
I forked the studygroup from @mozillascience, personnalized the `_config.yaml` to see the changes on radaniba.github.io/studyGroup
then I created a repo called radaniba.github.io :) and pushed an index.html into it with one line

```
<meta http-equiv="refresh" content="0; url=http://radaniba.github.io/studyGroup" />
```

That's it :) 

now if you visit radaniba.github.io you will be redirected automatically to the `studyGroup`

Cheers

Rad
