### ISSUE TITLE
How to use knitr

### ISSUE THREAD

**Issue by aammd** [minisciencegirl/studyGroup#4]
for reproducible documents and fun

**Comment by eacton** [comment]
I can do the session for this as a combined Rmd and knitr intro... I could do it in mid-May. :)

**Comment by katieannemills** [comment]
@eacton that's awesome! Once you know just when you'd like to do it, have a go at [the instructions](https://github.com/minisciencegirl/studyGroup#how-to-launch-a-new-event) to list a new event, let me know if something doesn't work!

**Comment by katieannemills** [comment]
Thanks @eacton! So it's going to be:

Where: [Biodiversity Research Center](https://www.google.ca/maps/place/Beaty+Biodiversity+Research+Centre+Loading+Bay/@49.263285,-123.2493821,17z/data=!4m3!3m2!1s0x0000000000000000:0xfd602268fd4b8181!4b1), UBC, room 224
When: May 13, 2015, 3 PM

Is the time correct? Are we going to install knitr together or should we do it beforehand? Thanks again!

**Comment by aammd** [comment]
I've reserved the room!

**Comment by eacton** [comment]
Thanks for booking the room, Andrew!

Thanks for the reminder, Bill.  Everyone can install beforehand:
install.packages("knitr")

**Comment by eacton** [comment]
Hey guys and gals,
In addition to install.packages("knitr"), go to file->new file->R markdown it will give you a prompt and install the following packages for you 'yaml', 'htmltools' and 'rmarkdown' - or you can do this through install.packages if you prefer.  (I like to type less!)

I am going to demo knitting to html, as well as to pdf.  The above is all you need to install for html.  If you want to be able to knit to pdf you need a couple more things, which requires a few minutes and a computer restart.

install.packages('installr')
installr::installr() - choose pandoc, then repeat and choose MikTex (MikTex will install a few dependencies which you can say yes to individually or altogether based on prompts)
restart computer!

That should be it!  See you tomorrow!

**Comment by jstaf** [comment]
It looks like `installr` and `MikTex` are Windows-only. 

For Ubuntu/Debian Linux it looks like you can install `pandoc` and TeX support through the terminal with the following commands:

```
sudo apt-get install pandoc
sudo apt-get install texlive
```

**Comment by eacton** [comment]
Thanks for trouble-shooting for the non-Windows folks!

**Comment by rozdakin** [comment]
Mac users can install from these sites, I think:
pandoc https://github.com/jgm/pandoc/releases/tag/1.13.2
mactex https://tug.org/mactex/

I don't know if this is best or whether it's all you need, just that the other install methods didn't work on my Mac

hmm... just realized mactex is 2.4 GB so keep that in mind

**Comment by morien** [comment]
Just realized I'm double booked this afternoon. Sad I'll miss this one.

**Comment by katieannemills** [comment]
awesome job today @eacton - if possible, please throw a link to your notes up here; I'm happy to help write up if you like!
