### ISSUE TITLE
Data Munging with dplyr and plyr

### ISSUE THREAD

**Issue by minisciencegirl** [minisciencegirl/studyGroup#42]
**Start time**: 3 PM Pacific time, August 12
**Live stream URL**: TBD (check back ~10 minutes before kickoff!)

**Comment by minisciencegirl** [comment]
@alyeffy will show us how to manipulate data frames using various R packages. We will host this event in LSI at UBC, on Wednesday, 3PM, August 12, 2015.

**Comment by katieannemills** [comment]
@alyeffy, the SFU team was wondering if we could webcast this lesson, since we ended up talking about dplyr here today during our make lesson - it's your call, let me know if I can help set up!

**Comment by alyeffy** [comment]
@BillMills Sure, I'm okay with webcasting this, and yes I would like help with setting up if possible still!

**Comment by katieannemills** [comment]
@alyeffy wonderful, thanks! I'll be there a few minutes early to get you set up.

**Comment by alyeffy** [comment]
Hi everyone,
If you haven't already, please try to install the following packages before the lesson today:

``` r
install.packages(c("plyr", "dplyr", "gapminder"))
```

Thanks!

**Comment by alyeffy** [comment]
The code we will be working along with today can be found here:
[Data Munging Code](https://github.com/alyeffy/data_munging_lesson)
See you soon :)

**Comment by alyeffy** [comment]
Live webcast URL:
http://www.youtube.com/watch?v=ymTJg7ybox4

**Comment by katieannemills** [comment]
Great session, @alyeffy, thanks! Let us know if there are notes we can link to. Thanks again!
