### ISSUE TITLE
display on mobile not that responsive

### ISSUE THREAD

**Issue by radaniba** [minisciencegirl/studyGroup#45]
I visited the studyGroup on my Nexus and found out that there is a small bug in the display, pretty sure it is a bootstrap class to be adjusted :mag: 

![screenshot_2015-07-15-18-39-04](https://cloud.githubusercontent.com/assets/1666443/8713994/e85c4076-2b24-11e5-9021-2f2574e4b088.png)

Cheers

Rad

**Comment by katieannemills** [comment]
lulz, thanks @radaniba - migrating this issue upstream.
