### ISSUE TITLE
Heatmap fun!

### ISSUE THREAD

**Issue by minisciencegirl** [minisciencegirl/studyGroup#47]
Our first event at BC Cancer Agency!! Come learn how to make heatmaps with Fong!

d3heatmap package: https://github.com/rstudio/d3heatmap

Notes/ Rmd script: https://github.com/tinyheero/R-Heatmaps

Time: September 8, 2015, 5:30pm
Room: BCCA (Dorothy Lam Room)

**Comment by tinyheero** [comment]
Ahh cool. Excited for this. I think heatmaps will be one component of it. The topic will be on gene expression profiling in cancer. So we'll definitely generate heatmaps. Probably cover topics on differential gene expression. Volcano plots, etc.

**Comment by katieannemills** [comment]
date / time / room? Looking forward to this, glad to be at BC Cancer!

**Comment by tinyheero** [comment]
I think Amy just updated the first message to include this information.

**Comment by minisciencegirl** [comment]
Yep! :)

Thanks again Fong!!

**Comment by tinyheero** [comment]
Is it common for people to bring their laptops to actually try out the code?

**Comment by minisciencegirl** [comment]
Hi Fong,

Yes. We tend to do code-along type of session so people can code along with you.

Let us know what packages we need as well as we can install them ahead of time.

Cheers,

Amy

**Comment by tinyheero** [comment]
Ok cool. Ok I'll send out a list of packages by Thursday.

Thanks!

**Comment by pssguy** [comment]
Could you confirm meeting details please 

```
 On Sunday, July 26, 2015 12:48 PM, Fong Chun Chan <notifications@github.com> wrote:
```

 I think Amy just updated the first message to include this information.—

**Comment by tinyheero** [comment]
Time and location remain the same as before:

Time: September 8, 2015, 5:30pm
Room: BCCA (Dorothy Lam Room)
Topic: Generating Heatmaps from Gene Expression Data

**Comment by pssguy** [comment]
Tx. I seem to have mislaid the email with that on. Do you have a site which lists future meetings? 

```
 On Tuesday, September 1, 2015 12:07 PM, Fong Chun Chan <notifications@github.com> wrote:
```

 Time and location remain the same as before:Time: September 8, 2015, 5:30pm
Room: BCCA (Dorothy Lam Room)
Topic: Generating Heatmaps from Gene Expression Data—

**Comment by minisciencegirl** [comment]
Check out this site for event listing: http://minisciencegirl.github.io/studyGroup/

There is a link for you to subscribe to the google calendar at the bottom right corner of the page.

Alternatively, you can “watch" this github repo (top right) and open issues to suggest any future events: https://github.com/minisciencegirl/studyGroup

Cheers!

**Comment by tinyheero** [comment]
The github repo containing the code/slides for this event can be found here:

https://github.com/tinyheero/R-Heatmaps

I am almost finished the tutorial/workshop. I'll update accordingly with R packages that need to be installed before the workshop.

**Comment by tinyheero** [comment]
I've finished packaging up the repository for this event/workshop now:

https://github.com/tinyheero/R-Heatmaps

The workshop will contain coding exercises that participants can run through during the workshop to generate heatmaps first hand. So please feel free to bring your laptops and complete the "Preparation for the Workshop" section ahead of time so that the coding exercise will work for you.

See you all tomorrow!

**Comment by tinyheero** [comment]
Webcast link:  

https://plus.google.com/events/chgh222e19gj64k2u8ih1vjphnk

**Comment by katieannemills** [comment]
Hey @tinyheero, thanks for doing this! Is there a recording of the webcast somewhere? Let me know and I'll add it to our youtube channel!

**Comment by tinyheero** [comment]
Unfortunately, the webcast didn't work. I might actually do this again because some people who couldn't make it reached out to me asking if I could run it again. Maybe in the near future :)
