### ISSUE TITLE
Making graphics with the "ggplot2" library - Tues., 5/19, 2:30PM

### ISSUE THREAD

**Issue by kemarshall** [minisciencegirl/studyGroup#5]

**Comment by katieannemills** [comment]
Yes! I will totally come to this - who wants to lead?

**Comment by jstaf** [comment]
I can do it. I actually already have [a tutorial](https://github.com/kazi11/RClub/blob/master/ggplot2_tutorial.R) written up from awhile back.

**Comment by katieannemills** [comment]
@kazi11 nice, thanks! have a go at [the instructions](https://github.com/minisciencegirl/studyGroup#how-to-launch-a-new-event) for listing a new event on the website, and let me know if they go ok.

**Comment by rozdakin** [comment]
Looking forward to this!

**Comment by minisciencegirl** [comment]
Me too!

**Comment by ahippman** [comment]
I would definitely make an effort to come!!!! Just made my first plots with ggplot but would love to expand on them!!!

**Comment by jstaf** [comment]
Ok, so I was thinking we could do this on May 13. Going to add it to the webpage later this weekend if there are no objections.

Based on the scheduled events so far, it looks like we are settling in to the schedule where we do a tutorial every week on Wednesdays?

**Comment by katieannemills** [comment]
@kazi11 Wednesday afternoon seems to work for people - but don't feel obliged! Other times will give people who can't do Wednesday a chance to participate too, so best to do what works for you. Really looking forward to this, thanks for jumping in!

**Comment by jstaf** [comment]
I'm going to move this tutorial 1 hour earlier to work with some other stuff in my schedule that day (now it's at 2pm). Is someone able to book a room? (Alternatively, can someone show me where the BioDiv room booking website is?)

**Comment by jstaf** [comment]
Booked Biodiversity 224 for the tutorial. New time is 2:30 pm on Tuesday May 19th.

You will only need the ggplot2 package for this tutorial.

``` r
install.packages("ggplot2")
```

**Comment by Holert** [comment]
Hi all, I would love to come to this event, but I only have very basic R knowledge to begin with. Is the tutorial also understandable for absolute R beginners?

**Comment by jstaf** [comment]
@Holert - Well, that's the goal. There's really nothing to lose by showing up, right? If anything, make sure you understand how to use basic functions and refer to columns in a dataframe.

This kind of stuff:

``` r
functionOutput <- exampleFunction(arg1, arg2)
dataframe$columnYouWantToUse
```

Also, I was apparently just kidding when I said `ggplot2` was the only dependency. Everyone should also get these:

```
install.packages("scales")
install.packages("cairo")
install.packages("RColorBrewer")
install.packages("ggthemes")
```

I only demo each one for a line or two, so no one is required to get them, but it'll be useful for showing what they do. Each package gives some improved plotting capabilities, like the ability to handle out-of-bounds values (`scales`) or render higher-quality output images (`cairo`).

**Comment by jstaf** [comment]
Okay, after going through this tutorial a few different ways, it became very clear that we'll need to follow along an example script that I've written instead of "coding along." The main reason for this is the sheer amount of typing that creating plots requires (this way we don't have to manually enter every single line while going through examples).

The tutorial's script is located [here](https://gist.github.com/kazi11/f7374ede42461a71f445).

This is a long script, and there is no way we are going to get through all of it. The goal is to understand the basics of how the package works. The script is heavily commented and will make a nice guide if you need to refer back to it.

See you all tomorrow!

**Comment by ClaireA** [comment]
Just saw this and just in time to attend this workshop!

**Comment by minisciencegirl** [comment]
Awesome collection of codes from @jennybc on #ggplot2
http://shinyapps.stat.ubc.ca/r-graph-catalog/

Documentations for #ggplot2: 
http://docs.ggplot2.org/current/

Also, here is how to tidy up your data.frame
http://cran.r-project.org/web/packages/tidyr/vignettes/tidy-data.html

**Comment by jennybc** [comment]
I have my own ggplot2 tutorial materials here:

https://github.com/jennybc/ggplot2-tutorial

**Comment by jstaf** [comment]
For the curious (and for those who couldn't make it), [here is the completed script](https://gist.github.com/kazi11/22fac11fecd5dd5121b2) from yesterday's tutorial. I've added a few more descriptions of common errors to the end. 

Also, Andrew brought this up yesterday and it's pretty funny (basically a collection of spectacularly failed ggplot2 plots that people have posted): [Accidental aRt](http://accidental-art.tumblr.com/).
