### ISSUE TITLE
Problem-solving with biomaRt

### ISSUE THREAD

**Issue by jstaf** [minisciencegirl/studyGroup#52]
Google hangout on air: [Webcast](https://plus.google.com/events/ca9v6dii91kapaqici7cmtqcgk4)
Etherpad for notes and questions: https://etherpad.mozilla.org/ubcstudygroup-biomart-aug19

[**biomaRt**](http://bioconductor.org/packages/release/bioc/html/biomaRt.html) is a web-interface package for R that lets you retrieve information from online databases like Ensembl. It's stupidly powerful.

I figured I'd run a tutorial on how to use `biomaRt`, and focus on using this package to solve real-world problems. We are going to focus on genomics applications, but a lot of what we're going to do (like dealing with weird formats and ugly datasets) applies to other disciplines as well.

We are going to:  
- Learn to parse and export complicated data formats like GTF2 in R 
- Learn how to browse online databases like Ensembl, Interpro, and Vectorbase in R
- Retrieve whatever annotations we want for genes from (nearly) any experimental organism
- Produce genomics reference files (like BED) file from scratch
- Retrieve all genes in a genome that perform a particular function
- Retrieve the DNA sequences for a set of genes and export them as FASTA files
- Learn to interconvert between different type of gene IDs (we are going to convert IDs in a GTF2 file)
- Access archived (but still potentially useful!) data 

This may seem like a lot to cover in an hour, but these are all simply variations of the same `biomaRt` commands, which makes working with the package really fast and easy.

You will want to have the `biomaRt` and `stringr` packages before coming. They can be installed with:

``` r
install.packages("stringr")
source("http://bioconductor.org/biocLite.R")
biocLite("biomaRt")
```

You will also want to download the scripts and data we will be working with from the repository [here](https://github.com/kazi11/biomaRt_tutorial) beforehand.

When: 3pm August 19
Where: Biodiversity 224

Hope to see you there!

**Comment by minisciencegirl** [comment]
Thanks Jeff!! This looks fantastic!! I will definitely be there. :-)

**Comment by jstaf** [comment]
I've added a link to the OP with the data and scripts we will be going through. Cheers!

**Comment by minisciencegirl** [comment]
Hi Jeff, 

Would you be open to webcasting this session?

Let me know and we can try to set it up.

Amy

**Comment by jstaf** [comment]
Why not? Let's do it.

**Comment by jstaf** [comment]
Closing- I've added a link to the webcast in the demo repository.
