### ISSUE TITLE
PSA: R packages and reproducibility

### ISSUE THREAD

**Issue by jstaf** [minisciencegirl/studyGroup#53]
# R packages and reproducibility...

Here's a "fun" story on about doing reproducible analyses in R that happened to me today. Hopefully seeing this saves someone else from a huge headache later on...
### The problem:

I'm writing up my thesis right now, and a lot of it depends on an analysis of RNA sequencing data that I did a while back. Anyhow, I recently have been rerunning the "R parts" of the analysis to get specific values like the exact number of upregulated/downregulated genes (that I hadn't written down earlier). The weird thing is, the number of significantly regulated genes (and other results) kept coming back as different from the earlier results I had saved on my computer. I had 331 significantly regulated genes before, and now there were 307. Why?
### Was it random number generation?

At first, I thought it had something to do with random number generation (statistical tests that use it are slightly different on each iteration unless you specify a specific starter value), but regardless of which values I told the number generator to start at, I always got the same, different answer than before. 

Side note: you can set the seed for R's random number generator with `set.seed()`.
### Was it the code/data?

So maybe I had changed the sequencing analysis code or something like that by accident? I double-checked my  code and starting data against the stored copies in version control and everything was identical to what I ran a year ago. 
### Was it somehow the computer?

Out of desperation, I booted up the ancient copy of R I had installed on an OS I don't normally use on my laptop, and re-ran the code with the same random number seed as before. Now there were 389 differentially expressed genes, which was even weirder than before (I had either 331 or 307 genes). Maybe it had something to do with the computer? So I went and turned on my desktop computer at home and ran the analysis there with the same code, starting data, and random number seed. I was back to 331 genes.
### Or was it the R package?

After doing a lot of running back and forth between all 3 versions of R, I noticed that the versions of `DESeq2` (the R package I was doing the analysis with) were different (versions 1.1.21, 1.4.5, and 1.6.3). I updated the version of `DESeq2` to the verrrryyyyy latest version on one computer (1.8.1), and now I had 324 significant genes. Anyhow, after digging through the `DESeq2` version release notes and source code on Github for the last 2 hours, it looks like they were changing the statistics in the package slightly between each version, giving me different results every time even though my code and starting data was exactly the same. 

So by simply updating my R packages, I was changing my data. Ugh.
# 
### What's the moral of the story?

If you want an analysis to be reproducible later (and avoid the nightmare described here), you should use a package managment system like [packrat](http://rstudio.github.io/packrat/), which happens to be built into RStudio. If you use `packrat` it will apparently keep track of which package versions you use for a project and let you use different versions for different projects (so situations like I've described here will never happen).

**Comment by rozdakin** [comment]
Thanks Jeff! Had no idea there were packages to do this.

**Comment by jennybc** [comment]
Another thing I do is break the analysis into bits, each getting a script, with the only communication being through output files, that then become inputs. So that, if I have to revisit something like this and cannot reproduce the entire S/W environment, at least I can "drop in" at an intermediate stage and carry on from there.

**Comment by jennybc** [comment]
As for packages that help, in addition to packrat, there are also [switchr](https://cran.r-project.org/web/packages/switchr/index.html) and [checkpoint](https://cran.r-project.org/web/packages/checkpoint/index.html).

**Comment by jstaf** [comment]
Interesting, Jenny, I will check those out!

And yeah, I have the same approach to an analysis, with separate scripts for separate jobs.

**Comment by jennybc** [comment]
I have a really sad story along these lines with Affy array data that was normalized with one version of rma and then, by the time we were writing the paper, i never could recreate the environment and re-run the analysis alpha to omega. It all worked out but it made a real impression on me. This is an important issue.

**Comment by ivyleavedtoadflax** [comment]
I had a similar problem. I wrote my entire PhD thesis using [knitr](http://yihui.name/knitr/) and LaTeX. Lots of code, and lots of dependencies that I was foolishly not keeping track of. Now without investing a serious amount of time into it, I currently cannot reproduce the whole document due to changes in a couple of key packages (fortunately, I don't have to...). A hard lesson learnt; I now use [checkpoint](https://cran.r-project.org/web/packages/checkpoint/index.html) with absolutely everything and like @jennybc suggests, save out the occasional intermediate .Rds file at key points in the analysis.

**Comment by benmarwick** [comment]
A more comprehensive option is to use a Docker image to capture almost the entire computational environment. 

Using a Docker file you can specify the OS, the version of R, package versions, and versions of external dependencies. 

@cboettig and @eddelbuettel have done a lot of pioneering work with Docker and R in their rocker project: https://github.com/rocker-org/rocker

**Comment by eddelbuettel** [comment]
As I was CC'ed here (by @benmarwick, howdy): I object to the title of the post.  

You have not demonstrated that 7000 CRAN are buggy.  You have experienced (at great personal pain, I am sure) a _buggy behaviour in one package_ whose output was bad.  But there is a story here about a single apple and a whole orchard, and I would like to speak up for the orchard.  That is all.  So please do not imply that any and all R packages are bad for reproducibility.  You got bitten by a bug in a one package. That sucks, and hurts. And is why we fix packages and add tests. But we don't throw out R for it.

**Comment by jstaf** [comment]
@eddelbuettel - Just to clarify, the title of this post was not to imply that all R packages are somehow buggy (because they aren't). The title is just to emphasize that you need to keep track of which R package versions you are using if you intend to reproduce a workflow. There's not really any way to know beforehand if a package's version will cause an issue until it actually does.

Making matters worse, it's currently extremely tough to obtain a set of archived packages if you don't have them already. Bioconductor and CRAN have two completely different package installation systems and getting archived versions is different for each repository. In this case, it's not even especially clear to me how to reproduce a Bioconductor package's version aside from somehow guessing which version of R will install the correct Bioconductor release with `biocLite()`. There's also that movement now towards skipping CRAN/Bioconductor entirely and installing R packages directly from source code repositories with `devtools::install_xxxx()`.

R desperately needs a [Gradle-like](https://gradle.org/why/robust-dependency-management/) dependency management system. Opening up some old Java source code that you haven't touched in years? No problem- just grab the relevant JDK, point your IDE at the `build.gradle` file, and it sets up your project perfectly and even downloads/installs the same version of the dependencies that you used years ago (doesn't even matter where they're from). Need a set of older packages to reproduce an old R environment on a new computer? Unless you already saved the packages somehow, you're in trouble. 

Whether we want to admit it or not, there's certainly a discussion to be had about reproducing an R analysis environment. And thanks for the great tips people, keep them coming!

**Comment by eddelbuettel** [comment]
Seems like you may like [switchr](https://cran.r-project.org/web/packages/switchr/index.html) which works with they call GRAN archive snapshots, see [this blog post](http://blog.revolutionanalytics.com/2014/08/gran-and-switchr-cant-send-you-back-in-time-but-they-can-send-r-sort-of.html).
