### ISSUE TITLE
vegan

### ISSUE THREAD

**Issue by katieannemills** [minisciencegirl/studyGroup#54]
Co-working session to learn vegan: Wednesday, November 18, 2015, 3pm, BioDiv 224

Webcast/ Google hangout with @gavinsimpson: Wednesday, November 25, 2015, 3pm, BioDiv 224

EDIT: Using this etherpad for questions for next week. go to the bottom: 
https://etherpad.wikimedia.org/p/UBC-R_vegan-work-along

So, my pal @naupaka just helped run an [awesome looking workshop](https://github.com/gavinsimpson/esa-advanced-vegan-2015) on ~~population~~ community ecology using the `vegan` package; @lmguzman @aammd and other ecology folks, what do we think of this? Any interest in pulling out a lesson from this?

**Comment by naupaka** [comment]
Hi all - technically it was focused on community ecology (versus population ecology), but at any rate the materials for the two workshops we ran (intro and advanced) are all CC-BY and available on GitHub (the intro repo is [here](https://github.com/naupaka/esa_intro_vegan_2015) and the advanced one, made by @gavinsimpson, is [here](https://github.com/gavinsimpson/esa-advanced-vegan-2015)).

**Comment by aammd** [comment]
I was present for the teaching of that; it was a nerdy _tour de force_ and was totally awesome.

**Comment by aammd** [comment]
I'd like to suggest that interested parties here at UBC get together and study the slides as provided. we could take 1.5 to 2 hours. I'm thinking that everyone would read the slides first, then show up with one or more of the following:
- answers to the challenges/activities posed in @naupaka or @gavinsimpson's slides. 
- Your own dataset that you'd like to try this on
- further examples drawn from the Vegan guide/literature/ etc

If we take notes on what kind of format works for us, then we would also end up with a pattern that other study groups could follow. More importantly, we'd all get to sharpen our distance-metric-based multivariate community analysis skills. :hocho:

**Comment by katieannemills** [comment]
+1 to that - a combination of independent work with periodic troubleshooting get togethers is exactly how some other groups have operated in the past, and it seemed to go really well for them! Is there an open dataset somewhere for curious physicists to take a swing at?

**Comment by aammd** [comment]
let's do it! I'll email a link to this issue round to some of the other community ecologists who are interested. ( cc @mattbarbour34) 
re: datasets, sure there are lots! some even come rolled into vegan. Species occurrence datasets are as numerous as, uh, muons in a femtosecond (?)

**Comment by mabarbour** [comment]
Count me in!

**Comment by katieannemills** [comment]
Cool - shall we stick a deadline on this for added motivation? I don't see anything booked on the 15th.

**Comment by gavinsimpson** [comment]
If I can be of any assistance do let me know; my slides for the advanced vegan workshop were put together assuming a human presenter to fill in from the prompting info on some slides. If some things are not clear feel free to email me or if managing this via Github flag me using @gavinsimpson.

**Comment by jooolia** [comment]
I would love to participate in this. :) Was stalking the tweets and github
repo, so would be fun to discuss in person. I am away until Sep 18th, so if
it could work, I would vote for a date during the week of September 21st. I
have/know of some interesting microbial datasets that could be of interest.

Julia

**Comment by minisciencegirl** [comment]
Ooo I really want to be here for this session as well.  I will be away the week for 9/21-9/26. @BillMills: I think we are doing the journal club on 9/16 and DiagrammeR on 9/30. Is there any way to run this session in early October?

**Comment by jooolia** [comment]
I think that would be excellent! I think @aammd should also be back then
too?

**Comment by aammd** [comment]
i shall!!

**Comment by minisciencegirl** [comment]
Hey guys, should we revitalize this session? Would Wednesday November 18th work for everyone interested in this? Cc: @jooolia @morien @aammd @aammd @mattbarbour34

**Comment by aammd** [comment]
I like the idea! November should be a good time for me. 
I know that @dsrivast was also interested, and @lmguzman too

**Comment by lmguzman** [comment]
Sounds great :)

**Comment by morien** [comment]
Absolutely. I'd love to help with this session, since I'll be using vegan
for a project I'm just getting started with. November 18th will work just
fine.

Hey guys, should we revitalize this session? Would Wednesday November 18th
work for everyone interested in this? Cc: @jooolia
https://github.com/jooolia @morien https://github.com/morien @aammd
https://github.com/aammd @aammd https://github.com/aammd @mattbarbour34
https://github.com/mattbarbour34

**Comment by mabarbour** [comment]
Hi all,

I’ll just be heading out of town that day. Were you guys planning on posting code/notes on github? I’d especially be interested in whether you guys go over using Gavin’s ‘permute’ package for analyzing complex experimental designs in with vegan.

Matt

**Comment by jooolia** [comment]
Hi!

Sounds good to me.

Also potentially of interest: @lmguzman https://github.com/lmguzman has
organized a reading group for Numerical Ecology. See the github repo:
https://github.com/lmguzman/MultivariateStatsUBC

**Comment by gavinsimpson** [comment]
Hi all,

If it would be of interest, at some point, I'd be happy to give a little
session on permute + vegan over hangouts/skype with examples of doing the
more complex experimental designs etc. Just let me know if you want to
arrange something.

G

On 15 October 2015 at 00:21, Matt Barbour notifications@github.com wrote:

> Hi all,
> 
> I’ll just be heading out of town that day. Were you guys planning on
> posting code/notes on github? I’d especially be interested in whether you
> guys go over using Gavin’s ‘permute’ package for analyzing complex
> experimental designs in with vegan.
> 
> Matt
> 
> > On Oct 14, 2015, at 11:14 PM, morien notifications@github.com wrote:
> > 
> > Absolutely. I'd love to help with this session, since I'll be using vegan
> > for a project I'm just getting started with. November 18th will work just
> > fine.
> > 
> > Hey guys, should we revitalize this session? Would Wednesday November
> > 18th
> > work for everyone interested in this? Cc: @jooolia
> > https://github.com/jooolia @morien https://github.com/morien @aammd
> > https://github.com/aammd @aammd https://github.com/aammd
> > @mattbarbour34
> > https://github.com/mattbarbour34
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/minisciencegirl/studyGroup/issues/54#issuecomment-148158986
> > 
> > .
> > —
> > Reply to this email directly or view it on GitHub <
> > https://github.com/minisciencegirl/studyGroup/issues/54#issuecomment-148292214
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/minisciencegirl/studyGroup/issues/54#issuecomment-148293109
> .

## 

Gavin Simpson, PhD

**Comment by katieannemills** [comment]
@gavinsimpson gavins That would be amazing! How would you feel about doing it as a hangout on air, so lots of people could tune in over youtube?

@minisciencegirl, when's a good time?

**Comment by gavinsimpson** [comment]
@BillMills Hangouts On Air is fine with me :)

**Comment by minisciencegirl** [comment]
Ooo that sounds awesome @gavinsimpson! How about November 25 at 3pm? 

This will give us time to go over the notes on 11/18 first and bring questions for the google hangout session. Thanks @gavinsimpson!

**Comment by gavinsimpson** [comment]
@minisciencegirl I can make that. Was that 3pm PST?

**Comment by minisciencegirl** [comment]
Yes!

**Comment by gavinsimpson** [comment]
@minisciencegirl OK, thanks. I'll actually need to confirm that with my Better Half as that's usually a day she works late and I pick up my kids.

**Comment by minisciencegirl** [comment]
@gavinsimpson: we can change date/ time if there is a better time for you. Thanks!

**Comment by gavinsimpson** [comment]
Argh, sorry I forgot to reply; we're good to go on the 25th if that is still OK for people?

**Comment by minisciencegirl** [comment]
Hi @gavinsimpson: definitely! Thank you for doing this!

**Comment by katieannemills** [comment]
heya - do we have a google hangout (or whatever) link for people to sign into for this? Time to tweet, let me know!

**Comment by gavinsimpson** [comment]
I've set up a Hangouts on Air event.
1. The Hangouts One Air is: https://hangouts.google.com/call/ousdwjqjntjdzeh5noiujsus6ua
2. The YouTube page is: http://youtu.be/73-pVMH1R2Q

If your prefer to do this on a different hangout/channel then just send me the link - either way is fine with me,

**Comment by gavinsimpson** [comment]
Materials[^1] for this afternoon's webcast are [here](https://github.com/gavinsimpson/UBCVeganStudyGroup)

[1:] I still need to prune some slides and finish the last example

**Comment by minisciencegirl** [comment]
This is fantastic Gavin! Thank you!

Amy
