### ISSUE TITLE
PSA: Making your code faster

### ISSUE THREAD

**Issue by jstaf** [minisciencegirl/studyGroup#57]
I came across these links while optimizing some code the other day and figured it might be useful to share. The MATLAB articles have a lot of carry-over to R aside from some language specific stuff that I'm not so sure about in R (like the column versus row memory storage/script versus function bits).

[Why R is a slow language](http://adv-r.had.co.nz/Performance.html)

[How to optimize R code (doing stuff to big datasets with base R)](http://quanttrader.info/public/FasterRCode.pdf)

[Optimizing your programs' speed with better memory usage (MATLAB)](http://www.mathworks.com/company/newsletters/articles/programming-patterns-maximizing-code-performance-by-optimizing-memory-access.html)

[General programming tips (MATLAB)](http://www.mathworks.com/help/matlab/matlab_prog/techniques-for-improving-performance.html?refresh=true)

**Comment by katieannemills** [comment]
Excellent lesson fodder here - I think @rozdakin did a performance-focused lesson a while back, could be cool to combine that material together with this next time we want to do a benchmarking lesson.
