### ISSUE TITLE
Looking for a TA for STAT545!

### ISSUE THREAD

**Issue by minisciencegirl** [minisciencegirl/studyGroup#58]
Hi #UBC #rstats!

Interested in sharing your R knowledge, work with a dynamic teaching team and get paid? 

STAT545 is looking for a teaching assistant for the fall semester: https://stat545-ubc.github.io/people-help-wanted.html

Please send your email application to: Jenny Bryan jenny@stat.ubc.ca with “STAT 545 TAship” in the subject line!

**Comment by jennybc** [comment]
Hi @minisciencegirl, can you close this? Thanks, we're all set.
