### ISSUE TITLE
How to use dplyr/magrittr - May 06th, 3PM, BioDiv 224

### ISSUE THREAD

**Issue by ksamuk** [minisciencegirl/studyGroup#6]
Come learn about the game-changing libraries dplyr and magrittr! dplyr provides tools for elegant manipulation of data frames employing the "split-apply-combine" approach. magrittr provides an implementation of a unix-like "pipe" operator. Together: cosmic data wrasslin' powers!

Where: [UBC BioDiv 224](https://www.google.ca/maps/place/Beaty+Biodiversity+Museum/@49.263276,-123.251007,18z/data=!3m1!4b1!4m2!3m1!1s0x548672ca074d9db1:0x551432468a9f8fc3)
When: May 06 at 3PM
Who: @ksamuk and @aammd

**Comment by katieannemills** [comment]
Sounds great! Care to walk us through a demo?

**Comment by ksamuk** [comment]
I'd be happy to! Perhaps @aammd would like to help out as well? I was thinking May 6th unless the ggplot tutorial was going to be that day.

**Comment by katieannemills** [comment]
Nice! When you pick a date, have a go at [the instructions](https://github.com/minisciencegirl/studyGroup#how-to-launch-a-new-event) for listing a new event - @aammd already did this for today's lesson, so he can help out if something is weird / doesn't work. Thanks, I can't wait!

**Comment by aammd** [comment]
@ksamuk omigosh yes yes definitely!!! `magrittr` is my favourite thing that is inside of a computer.

``` r
andrew %>%
  gets_excited() %>%
  starts_talking()
```

**Comment by minisciencegirl** [comment]
Should we install these packages before hand?

**Comment by jstaf** [comment]
There's really no reason not to.

**Comment by aammd** [comment]
``` r
install.packages("magrittr")
install.packages("dplyr")
```

**Comment by ghost** [comment]
```
install.packages("dplyr")
# pulls in "magrittr" as a dependency, so no need to install separately.
```

**Comment by jooolia** [comment]
Link to repo for demo: https://github.com/ksamuk/dplyr_magrittr_demo
