### ISSUE TITLE
Introduction to Python

### ISSUE THREAD

**Issue by katieannemills** [minisciencegirl/studyGroup#62]
**When:** October 7, 3:30 PM
**Where:** UBC main campus, [Biodiversity Building Room 224](https://www.google.ca/maps/place/Beaty+Biodiversity+Museum,+Vancouver,+BC+V6T+1Z4/@49.2634989,-123.2502185,17z/data=!3m1!4b1!4m2!3m1!1s0x548672c9f84be123:0x1c431143106eb830?hl=en)
**Audience:** This lesson is aimed at people with _no previous coding experience_. Bring your friends for the best possible experience!
**Lesson Notes**: https://github.com/BillMills/python-lesson-notebooks/blob/master/intro-python-1.ipynb
**Etherpad**: https://etherpad.wikimedia.org/p/ubc-studygroup-python-Oct7

I'll be leading a first introduction to Python covering variables and functions, suitable for people with no experience programming. If you've been looking to get started using Python in your research, this is the lesson for you! We'll also help you get Python set up on your computer as part of this lesson.
### Setup Instructions

Before you come, try setting up Python on your laptop using the [instructions here](https://store.continuum.io/cshop/anaconda/); choose Python 3.4 (but if you already have python 2 installed, that's fine too). Anaconda is a collection of python tools and packages most popular in scientific computing; choose the free option for your operating system from the link above. If you get stuck on any of these steps, don't worry - **show up 15 minutes early** and we'll help get you set up.

**Comment by katieannemills** [comment]
Experienced pythonistas & instructors - I need some helpers to come out and help get people unstuck if they have trouble installing anaconda and/or jupyter. Let me know if you can make it!

**Comment by jstaf** [comment]
Hey Bill, this is great! Thanks for doing this!

**Comment by katieannemills** [comment]
ping on helpers - @lmguzman and other python folks, can you make it that afternoon? I anticipate lots of help needed particularly with installation issues; let me know if you can drop in!

**Comment by lmguzman** [comment]
Hey Bill, sure, ill be there :)!

**Comment by katieannemills** [comment]
Awesome, thanks @lmguzman!

**Comment by lmguzman** [comment]
Hey @BillMills do you have any link of a lesson you will follow?

**Comment by katieannemills** [comment]
@lmguzman https://github.com/BillMills/python-lesson-notebooks/blob/master/intro-python-1.ipynb

**Comment by morien** [comment]
I was gonna come to this but I'm a fool and I left my laptop at home today! Still worth coming?

**Comment by jstaf** [comment]
For those looking for a Python equivalent of RStudio, [PyCharm](https://www.jetbrains.com/pycharm/) is pretty great (it includes stuff like a Python console, command-line shell, git, code-checking, a really nice debugger, and inline access to Python documentation). There's also a Python plugin for [IntelliJ IDEA](https://www.jetbrains.com/idea/) that gives IDEA all the Python features PyCharm has, but it's a little trickier to setup. 

The two most helpful hotkeys if you decide to use one of those programs are Alt+Shift+E (run whatever you've got highlighted in the Python console) and Ctrl+Q (view documentation).

**Comment by katieannemills** [comment]
hey @morien, sorry you couldn't make it - I just added the notes to the top post, check them out and come next time! We did variables and functions today, and we're going to do if/else and loops in two weeks (event listing forthcoming).

@kazi11 - yes! I hear many good things about PyCharm, thanks for the link!
