### ISSUE TITLE
Co-working Session

### ISSUE THREAD

**Issue by katieannemills** [minisciencegirl/studyGroup#63]
**When**: September 23, 3 PM - 5 PM
**Where**: UBC main campus, [Biodiversity Building Room 224](https://www.google.ca/maps/place/Beaty+Biodiversity+Museum,+Vancouver,+BC+V6T+1Z4/@49.2634989,-123.2502185,17z/data=!3m1!4b1!4m2!3m1!1s0x548672c9f84be123:0x1c431143106eb830?hl=en)
**Audience**: Absolutely everybody, beginners welcome!

A whole bunch of people have been asking me lately how to improve their coding skills - the number one best way is to collaborate and get feedback from others! Come hang out for a couple of hours to work on your own projects, get input from your colleagues, and discover useful new things. **All fields, projects, languages and skill levels very welcome!**

I understand that there will also be donuts :)

**Comment by katieannemills** [comment]
can some nice person please book Biodiv 224 for this (also for #62)? Thanks!

**Comment by rozdakin** [comment]
Done and done.
...and I booked that room for us for Wednesdays 3:00-5:00PM from Oct 7 to Dec 16

**Comment by katieannemills** [comment]
Awesome, thanks @rozdakin!
