### ISSUE TITLE
Journal Club: Open Access & Open Data

### ISSUE THREAD

**Issue by katieannemills** [minisciencegirl/studyGroup#64]
**Where:** UBC Beaty Biodiversity Bldg, Room 224 ([map](https://www.google.com/maps/place/Beaty+Biodiversity+Research+Centre+Loading+Bay/@49.2641002,-123.2488292,16z/data=!4m5!1m2!2m1!1sbeaty+biodiversity+building+ubc!3m1!1s0x0000000000000000:0xfd602268fd4b8181))
**When:** October 14, 3 PM
**Reading:** please read the two papers on open science, linked below! **All are welcome**, bring your questions and ideas!

Hi all,

Journal club was pretty fun the last time we did it - are people interested in another go? Here are a couple of papers to check out:
- [Effects of open access publishing (high energy physics)](http://arxiv.org/ftp/arxiv/papers/0906/0906.5418.pdf)
- [Data Reuse (genomics)](https://peerj.com/articles/175/)

~~When would people like to meet up?~~ <-- see above for time and place.

cc @minisciencegirl @rozdakin @eacton

**Comment by rozdakin** [comment]
Yes! And those two would be awesome. 
I am flexible, except Monday afternoons are out for me.

**Comment by minisciencegirl** [comment]
Should we keep Wednesday as our usual meet-up time?

**Comment by katieannemills** [comment]
Sure, we could pick a Wednesday - I'm good whenever!

**Comment by rozdakin** [comment]
How about Oct 14? I know we have the room from 3-5PM, though I'm not sure if we have a workshop planned...

**Comment by eacton** [comment]
sounds good!

**Comment by katieannemills** [comment]
Cool, let's do it - I've listed the event, see you then!
