### ISSUE TITLE
Work-along session on Wednesday, Oct 28, 3pm - 5pm

### ISSUE THREAD

**Issue by minisciencegirl** [minisciencegirl/studyGroup#66]
**Where**: [Biodiv 224, UBC](https://www.google.ca/maps/place/Beaty+Biodiversity+Research+Centre+Loading+Bay/@49.2634552,-123.2509937,19z/data=!4m2!3m1!1s0x0000000000000000:0xfd602268fd4b8181)
**When**: Oct 28, 3-5 PM
Come have some cookies and work on your coding projects - R, Python and others all welcome!

**Comment by minisciencegirl** [comment]
Hi @rozdakin @mwpennell: will you guys be around for work-along today? I've been plotting some phenotype data onto phylogenetic trees, but running into problems modifying the final figure - would love some help if you guys are free. Cheers!

**Comment by SimonGoring** [comment]
I was going to come today to say hi and work on a Shiny/leaflet app, but like looking at phylogenies.

**Comment by minisciencegirl** [comment]
Woot! Looking forward to it.

**Comment by rozdakin** [comment]
I probably can't make it (in the middle of an experiment).
Will try to see if I can get someone to cover.
