### ISSUE TITLE
tune in to Ropensci community call

### ISSUE THREAD

**Issue by aammd** [minisciencegirl/studyGroup#67]
Does anybody want to try to tune into the Ropensci community call tomorrow? If there is interest I could try to call in on my laptop and we can have another listening party!

The subject is [assertr](https://github.com/tonyfischetti/assertr) which looks **_awesome**_ 

9 am tomorrow in Biodiv (room TBA)

All info @ ropensci/commcalls#7

**Comment by sckott** [comment]
w00t, plz do

**Comment by aammd** [comment]
Closing now, but I am here to tell you that `assertr` is, indeed, awesome and is a part of the future, so get in.

don't worry @BillMills, once my thesis is in I'll UtilityBelt it right up :joy_cat: :
