### ISSUE TITLE
Introduction to Python, Part 2

### ISSUE THREAD

**Issue by katieannemills** [minisciencegirl/studyGroup#68]
**When:** October 21, 3:30 PM
**Where:** UBC main campus, [Biodiversity Building Room 224](https://www.google.ca/maps/place/Beaty+Biodiversity+Museum,+Vancouver,+BC+V6T+1Z4/@49.2634989,-123.2502185,17z/data=!3m1!4b1!4m2!3m1!1s0x548672c9f84be123:0x1c431143106eb830?hl=en)
**Audience:** This lesson is aimed at people with _no previous coding experience_. Bring your friends for the best possible experience!
**Lesson Notes**: https://github.com/BillMills/python-lesson-notebooks/blob/master/intro-python-2.ipynb
**Etherpad**: TBD

This lesson will continue where we left off [last time](https://github.com/minisciencegirl/studyGroup/issues/62) - then, we covered variables and functions in Python; this time, we'll talk about lists, for loops and logical conditions. Once we've completed this lesson, we'll have the basics we need to dive into the world of scientific Python packages and tools.
### Setup Instructions

Before you come, try setting up Python on your laptop using the [instructions here](https://store.continuum.io/cshop/anaconda/); choose Python 3.4 (but if you already have python 2 installed, that's fine too). Anaconda is a collection of python tools and packages most popular in scientific computing; choose the free option for your operating system from the link above. If you get stuck on any of these steps, don't worry - **show up 15 minutes early** and we'll help get you set up.

**Comment by minisciencegirl** [comment]
So excited! Thanks!!!

**Comment by katieannemills** [comment]
Hi folks - the notes for yesterday's lesson are here: https://github.com/BillMills/python-lesson-notebooks/blob/master/intro-python-2.ipynb

Please try working through the 'Conditions' section, and if you get stuck, post a question here, or come to the [coworking session on the 28th](https://github.com/minisciencegirl/studyGroup/issues/66) - see you then!
