### ISSUE TITLE
Python - Pandas

### ISSUE THREAD

**Issue by lmguzman** [minisciencegirl/studyGroup#69]
When: November 4th, 3:30 PM
Where: UBC main campus, Biodiversity Building Room 224
Audience: This lesson is aimed at people with a little bit of coding experience.
Lesson Notes: https://github.com/lmguzman/PythonLessons/blob/master/Intro%20to%20Pandas.md
Etherpad: TBD

Setup Instructions

Pandas comes with the Anaconda installation. Before you come, try setting up Python on your laptop using the instructions https://www.continuum.io/downloads; choose Python 3.4 (but if you already have python 2 installed, that's fine too). Anaconda is a collection of python tools and packages most popular in scientific computing; choose the free option for your operating system from the link above. If you get stuck on any of these steps, don't worry - show up 15 minutes early and we'll help get you set up.

**Comment by cedricmiao** [comment]
Sorry I'm new to this- is this session aim to talk about how to use pandas in Python?

**Comment by katieannemills** [comment]
Welcome @cedricmiao - yes it is! @lmguzman will be introducing pandas in python - the details are up to her, but you've got the right idea. I hope you can make it out on Wednesday!

**Comment by cedricmiao** [comment]
it's been awhile since I went to UBC... i tried to google map the location, is Beatty Biodiversity research center the place we are meeting today?

**Comment by lmguzman** [comment]
Yeah, room 224

**Comment by lmguzman** [comment]
@BillMills Just added the notes from yesterday :)

**Comment by katieannemills** [comment]
@lmguzman awesome, thanks! you're in the directory: https://github.com/mozillascience/studyGroupLessons/issues/57
