### ISSUE TITLE
R practice session - April 22nd, 3PM, BioDiv 224

### ISSUE THREAD

**Issue by morien** [minisciencegirl/studyGroup#7]
I will be giving a practice lesson very similar to Andrew's talk the previous week. will update this with more info before the end of the week.

**Comment by katieannemills** [comment]
Listed this on the website (http://minisciencegirl.github.io/studyGroup/) - let me know if anything needs to change, thanks for doing this!

**Comment by morien** [comment]
Hi everyone, just a quick update for tomorrow's session. You'll need R 3.1 or greater, and an up to date copy of Rstudio. We're using the gapminder dataset and it requires R 3.1

That's all. See you at 3PM tomorrow!

**Comment by jennybc** [comment]
Hmm… I guess I am to blame for the R >= 3.1.0 requirement! For a dataset?!? I think that was boilerplate from `devtools::create()`. In any case, having a rather current version R is generally a good idea :smiley:.

**Comment by dartdog** [comment]
For those of us not so familiar with UAB, Where is the Bio Diversity center (room 224), Which building and parking ideas?

**Comment by katieannemills** [comment]
Here's a [map](https://www.google.ca/maps/place/Beaty+Biodiversity+Research+Centre+Loading+Bay/@49.2631996,-123.2503983,18z/data=!4m7!1m4!3m3!1s0x548672c9f84be123:0x1c431143106eb830!2sBeaty+Biodiversity+Museum,+The+University+of+British+Columbia,+Vancouver,+BC+V6T+1Z4!3b1!3m1!1s0x0000000000000000:0xfd602268fd4b8181) - not sure about parking tho, anyone else?

**Comment by morien** [comment]
There is a parkade on health sciences mall across from the UBC hospital.
It's pretty expensive but I think that's as good as you'll get on campus.

You can also park for free in Point Grey and take the bus in. I park on
16th avenue sometimes.
