### ISSUE TITLE
SWC Instructor Training

### ISSUE THREAD

**Issue by katieannemills** [minisciencegirl/studyGroup#70]
**Edit: Draft application open here, due Nov 18**: http://pad.software-carpentry.org/UBC-instructor-training

Hey folks - applications are open for a round of SWC instructor training: http://software-carpentry.org/blog/2015/10/call-for-instructor-training.html

Anyone interested in some teacher training + certification to teach SWC? These applications get submitted as a group, and I've got a couple other nodes around town that might be interested in this - let me know if you're interested so we can all apply as a group.

**Comment by SimonGoring** [comment]
I'd definitely be interested, presuming we'd be doing it in Vancouver.  I'm out of town in the middle of December, but otherwise am flexible.

**Comment by ksamuk** [comment]
I am also very interested in this.

**Comment by jstaf** [comment]
This sounds awesome! Count me in.

**Comment by joeyklee** [comment]
Hi!

I can’t say that I fulfill all the criteria for being “qualified”, but I’m keen to do this! Sign me up. 

-J

**Comment by wmhall** [comment]
Hi Bill, I would also be interested in doing this.
Thanks!

**Comment by daattali** [comment]
Any idea what the format of the "course" is? Is it just watching videos for 8 hours for 2 days?

**Comment by lmguzman** [comment]
So I'm doing the one that is currently running for two months one hour per week, and its an instructor online, the lecture is given through bluejeans so you can see and listen to the instructor. But its heavily based on ether pad, where the whole class interacts that way. Taking notes together and asking questions. Right now they give us some homework through piazza (but Im not sure how that would work for two days). So if its entirely online, I would guess is something similar to this.

**Comment by katieannemills** [comment]
Awesome, I'm glad so many people are interested! re: format, it'll be similar to what @lmguzman describes, except the Vancouver group will assemble at a physical location to do group activities. There's enough people on this thread to do a site at UBC in all likelihood.

I'll pull a draft application together tonight, and share it on this thread with further instructions - thanks for jumping in, SWC Instructor Training is a great intro to teaching in general, I find it relevant to way more than just SWC.

**Comment by katieannemills** [comment]
Okay folks, here's an etherpad where we can pull together our application:
http://pad.software-carpentry.org/UBC-instructor-training

There are a few steps to go through (including making a pull request to a repo - if you aren't familiar with this, I'll help you out), so don't leave it to the last second - applications must be in Nov 18.

I'll be at UBC Wednesday for [this session](https://github.com/minisciencegirl/studyGroup/issues/69) if you want to chat about this before / after - let me know!

**Comment by mstrimas** [comment]
This sounds cool. If I haven't actually taken the course myself can I still be part of the instructor training. I'm fairly familiar with most of the tools covered, though I'm certainly not an expert.

**Comment by katieannemills** [comment]
@mstrimas totally okay to have not taken the course, no problem! It's definitely not required to have had anything to do with SWC before - just curious if anyone has!

**Comment by eacton** [comment]
Interested! Thanks, Bill!

**Comment by jstaf** [comment]
Went ahead and added myself to the application!

**Comment by daattali** [comment]
~~Part of the instructions say~~

~~> People who wish to teach Software Carpentry must submit a small pull request to a specified GitHub repository.~~

~~Does anyone know what github repo this is referring to?~~

edit: nevermind, I now see that the instructions for that are in the survey

**Comment by ksamuk** [comment]
@BillMills, thanks again for organizing this. I filled out the etherpad, survey, and submitted my PR to training prep repo. Let me know if there's anything else I can do to help out. Looking forward to it!

**Comment by aammd** [comment]
It seems to me that many people in this thread would enjoy participating in all or part of the SWC instructor retreat happening next weekend. The Etherpad for the event is here:

https://etherpad.wikimedia.org/p/swc-instructor-retreat-2015-vancouver

There will be SWC instructors giving practice lessons, discussing teaching techniques, etc. It's going to be a lot of fun!

**Comment by owensgl** [comment]
I'm really interested in doing this workshop, I've added myself to the document.

**Comment by katieannemills** [comment]
Great stuff, all - has everyone filled out the survey from step 2 on the etherpad? Don't forget!

Also: @kazi11, have we / can we book 224 all day for those two days (dec 7/8)? We should get a room together before we hand in.

**Comment by ksamuk** [comment]
Looks like 224 has quite a bit of activity booked on those days. How many people are we in total? I went ahead and booked 225 (the smaller room) for both days. It has a projector and can comfortably fit about 10 (might be able to squeeze in a couple more).

**Comment by katieannemills** [comment]
@ksamuk that's perfect, 10 should be fine; I think we're about 5 now, with a few more to finish the paperwork - might be a bit cozy, but that's fine. Thanks!

**Comment by katieannemills** [comment]
Hi folks,

Just fyi, SWC [posted some clarifications](http://software-carpentry.org/blog/2015/11/clarifications-about-call-for-instructor-training.html) to this process, as well as an [updated blog post](http://software-carpentry.org/blog/2015/10/call-for-instructor-training.html) - none of this really changes anything, except for a hard cap at 10 people (which is how big our room is, anyway); there's 5 signed up so far, so get your details on [the etherpad](http://pad.software-carpentry.org/UBC-instructor-training) if you want one of the remaining spots!

**Comment by katieannemills** [comment]
Hey again all - remember, this application is due next week! **Please have your details in by 5 PM Monday** - I will wrap things up on Tuesday and submit.

**Comment by katieannemills** [comment]
**and now that I actually look at the etherpad, we're at capacity for this event; thanks all for signing up! Still though, I'll wait until Tuesday to submit, so make sure your details are correct and complete.

**Comment by katieannemills** [comment]
Alright, applications away - I'll let you all know how things turn out.

**Comment by katieannemills** [comment]
Hi folks - unfortunately, UBC's application for Instructor Training was rejected by the Mentorship Committee, despite broad support from committee membership.

The problem was trainer bandwidth; there's just nowhere near enough people currently qualified to teach Instructor Training to meet demand.

Please don't take this as a reflection on your application; this is a resources problem. SWC is eager to work with you; furthermore, I have personally taught scientific programming around the world, and can confidently say that the UBC team is one of the best groups I have ever worked with. I will remind SWC of that, again, the next time training becomes available.

**Comment by ksamuk** [comment]
Hi Bill. That's really unfortunate to hear, as I think we were all really looking forward to the training. Anyway, thanks for all your hard work putting together this application and advocating for us with SWC.

**Comment by eacton** [comment]
Bummer. Thanks for your efforts, Bill - we really appreciate it.

**Comment by jstaf** [comment]
:( ... In the same boat as everyone else, really wanted to do this!

**Comment by LeungConnie** [comment]
Thanks Bill for all your effort in putting this together though! Much
appreciated!

Connie

**Comment by owensgl** [comment]
Thanks for all your work Bill! Hopefully we can get Instructor Training at UBC in the future.

**Comment by SimonGoring** [comment]
I've said before that I wouldn't want to be in any club that would have me as a member, but in this case I did want to be in the club.  It sounded like a good club.
