### ISSUE TITLE
reshape2 + tidyr + general data wrangling

### ISSUE THREAD

**Issue by jstaf** [minisciencegirl/studyGroup#72]
`reshape2` is a very handy R package that lets you reformat your data really easily. It makes formatting your data for stats functions, plotting with `ggplot2`, and using `plyr`/`dplyr` wayyyyyyy easier. We're going to also cover some really handy data handling tips like logical indexing and how to use R's `grep()` function as well. 

The tutorial from the week before this one is on the `vegan` package. Our examples, on the other hand, will focus exclusively on meat. We will attempt to answer several critically important questions that I know many of you have probably been struggling with for some time:  
- Why is bacon the best food ever?
- What is pretty much the unhealthiest thing you can possibly eat? (hint: this is a continuation of the previous question)
- How many calories are in average-sized serving of manatee? 
- What is the most superior meat?

To find out, you'll need to come to this tutorial...

Where: Biodiversity 224
When: December 2 @ 3pm
[Repository with tutorial materials](https://github.com/kazi11/reshape2_tutorial)

Run this in R before the tutorial to install the packages we will need:

``` r
install.packages("reshape2")
install.packages("stringr")
```

**Comment by katieannemills** [comment]
huzzah!

**Comment by jennybc** [comment]
😄🐖

Curious: @kazi11 what's your stance re: `tidyr`? I find it to be a nice interface to a subset of `reshape2`, which, honestly, I never really mastered.

**Comment by SimonGoring** [comment]
The reason paleoecologists like Bacon is that it's one of the first age-depth modeling tools that takes a Bayesian approach to modeling sediment accumulation (Blaauw and Christen, 2011).  It comes on the heels of Clam, and is soon to be superseded by another package called BLT.

https://projecteuclid.org/euclid.ba/1339616472

Either way, reshape2 is one of the key packages for me, along with ggplot2 and spdep/rgdal/raster.

**Comment by rozdakin** [comment]
Looking forward to this!

ditto @jennybc ... I find tidyr way easier for going long <--> wide

**Comment by jstaf** [comment]
@jennybc - I've never actually used tidyr (reshape2 works fine, why switch?), so I don't want to comment too much on it. 

That said, I don't like re-learning how to do everything every time Hadley Wickham comes up with a new package, so I just stick with base R, some Bioconductor packages, and what I've found to be the most useful stuff from the "Hadleyverse" (ggplot2/reshape2/stringr). The reason I like the base R stuff is that it has a lot of carryover with Matlab and more traditional programming languages (which makes it way easier to switch between them). 

However, if Hadley suddenly felt like reinventing image/video analysis in R... well, let's just say I would be a very happy person. (That's pretty much the main reason I still feel absolutely forced use Matlab...)

**Comment by jennybc** [comment]
The two main functions of `tidyr` are `gather()` and `spread()`, which are `reshape2::melt()` and `reshape2::cast()`. Early on, they were literally wrappers around `reshape2` functions, I think, but that is no longer true. In any case, I find that students (and I!) find the UI of those two functions -- most especially `spread()` -- more intuitive than their `reshape2` ancestors. But of course functionally it does not matter and `reshape2` does more than `tidyr`. Just thought I'd ask.

**Comment by jstaf** [comment]
I've read through the `tidyr` docs and examples a few times before, but `reshape2` always seems easier to me for whatever reason (especially the wonderful `melt()` function). To each, their own, I guess...

**Comment by minisciencegirl** [comment]
Hey @kazi11 , I thought we have something scheduled for 11/25 - vegan part 2. Let me update the schedule a bit. But can we run this beginning of Dec? I can show those two functions in tidyr during the session and maybe we can have a group challenge with these two packages?

**Comment by jstaf** [comment]
Hmmm... I didn't see it on the website schedule so I just went and took the next available date. The beginning of December also works. 

Adding in tidyr could also be pretty useful, as several people here seem pretty keen on that package. Perhaps you could teach the tidyr stuff right after I introduce the reshape2 stuff, and then we have everyone try to do the same data aggregation/reshaping stuff on the final example problem?

Maybe the tutorial could go something like this:
- Handling/filtering data using logical indexing
- reshape2
- tidyr
- Example problem that people can solve using both reshape2 and tidyr

Anyhow, added you as a collaborator on the tutorial repo.

**Comment by minisciencegirl** [comment]
Good suggestion on the flow for the tutorial. 

The schedule is my fault - need to update a few things that were deeply embedded in the issues.

Thanks!!

**Comment by jstaf** [comment]
Edited the OP to reflect the new time for the tutorial: December 2 @ 3pm in Biodiversity 224.

**Comment by katieannemills** [comment]
Thanks, @kazi11! I am in Germany so I will miss this one, but do please post the notes!

**Comment by minisciencegirl** [comment]
@kazi11: speaking of image analysis in R, have you seen this http://www.openmicroscopy.org/site/products/omero and the R package https://t.co/KFoPLI7tyS? Personally never used it, but someone mentioned it to me over Twitter.
