### ISSUE TITLE
Hacky Holiday Party for the Vancouver Study Groups?

### ISSUE THREAD

**Issue by minisciencegirl** [minisciencegirl/studyGroup#73]
_Edit_

**What**: Hacky Hour Holiday Party!
**When**: Friday, December 18. 6PM
**Where**: [Charlatan, Commercial Dr x Grant](https://www.google.ca/maps?q=charlatan+pub+vancouver&oe=utf-8&gws_rd=cr&um=1&ie=UTF-8&sa=X&ved=0ahUKEwjJxYuC0-PJAhUFxGMKHXDWCLcQ_AUIBygB)

Let's get together to wrap up 2015 with a get-together for everyone involved (or just interested) in the scientific programming and open science community here in Vancouver. All are welcome, bring your friends! Let us know who's coming on [this etherpad](https://etherpad.wikimedia.org/p/VancouverHackyHour) so we know how many tables to grab. See you then!  

_end edit_

Hi everyone, 

Let's get together for a #hackyhour Holiday Party on Friday, Dec 18, 6pm!

Any suggestion for a good location that's between UBC, SFU, BCCA and downtown? Perhaps St. Augustine on Broadway/Commercial?

@BillMills @ttimbers 

Hope to see you all there!!

Amy

**Comment by ttimbers** [comment]
@minisciencegirl LOVE that idea! Let's do it! #hackyhour Holiday Party on Friday, Dec 18, 6pm at the Charlatan on Broadway/Commercial!

**Comment by rozdakin** [comment]
I'm down!

**Comment by ttimbers** [comment]
OK, got this event listed on the Vancouver Hacky Hour etherpad: https://etherpad.wikimedia.org/p/VancouverHackyHour

@minisciencegirl please send this around when you promote and ask people to sign up, then we know how many seats we need to reserve!

**Comment by morien** [comment]
Sounds great! I'm in!

**Comment by jstaf** [comment]
Definitely going in my calendar!

**Comment by katieannemills** [comment]
Awesome, let's do it!

**Comment by minisciencegirl** [comment]
@rozdakin @kazi11 @jooolia: Will you guys be able to join us at #Hacky Holiday Party? Do you mind signing up to the etherpad for reservation purposes?

**Comment by morien** [comment]
Sorry everybody, I have to back out. :[

An old friend is coming to visit (on very short notice!), so I can't make
it any more.

**Comment by ttimbers** [comment]
Hey all! Couldn't get a reso at St Augustines, so we're going to be at the Charlatan instead. Got a reso for 12 at 6pm. Details and location are updated on the etherpad: https://etherpad.wikimedia.org/p/VancouverHackyHour

See you tomorrow!

Please spread the word about the change of venue @BillMills @minisciencegirl @aammd

**Comment by katieannemills** [comment]
np np, event updated; see you all there!
