### ISSUE TITLE
Python Pandas 2 and more!

### ISSUE THREAD

**Issue by lmguzman** [minisciencegirl/studyGroup#74]
When: December 9th, 3:30 PM
Where: UBC main campus, Biodiversity Building Room 224
Audience: This lesson is aimed at people with a little bit of coding experience.
Lesson Notes: https://github.com/lmguzman/PythonLessons/blob/master/Numpy!.md
Etherpad: TBD

Setup Instructions

Pandas comes with the Anaconda installation. Before you come, try setting up Python on your laptop using the instructions https://www.continuum.io/downloads; choose Python 3.4 (but if you already have python 2 installed, that's fine too). Anaconda is a collection of python tools and packages most popular in scientific computing; choose the free option for your operating system from the link above. If you get stuck on any of these steps, don't worry - show up 15 minutes early and we'll help get you set up.

**Comment by katieannemills** [comment]
Thanks, @lmguzman! I'll be there, I love pandas  :panda_face:  :microscope:

**Comment by SimonGoring** [comment]
Thanks, will try to make it!
