### ISSUE TITLE
Introduction to Docker (Feat. Rocker)

### ISSUE THREAD

**Issue by katieannemills** [minisciencegirl/studyGroup#75]
**What:** A very first introduction to reproducible research using [Docker](https://www.docker.com/)
**When:** Wednesday, December 16, 3.30 PM
**Where:** [UBC main campus, beaty biodiversity bldg room 224](https://www.google.ca/maps/place/Beaty+Biodiversity+Museum,+Vancouver,+BC+V6T+1Z4/@49.264052,-123.2514953,17z/data=!4m2!3m1!1s0x548672c9f84be123:0x1c431143106eb830)
**Who:** Everyone! No previous experience with docker required, bring your friends.
**Setup:** Please install docker on your machine before the meetup (see the Getting Started link in the top right of [the Docker homepage](https://www.docker.com/).) Also, **you need to install the `ropensci` Rocker image beforehand**; this is a 3 GB download, so please don't leave it till you get there! To do so:
- on mac or windows, open the 'Docker Quickstart Terminal' that was installed along with Docker (it'll look like a regular terminal window); or on linux, just open a terminal window.
- then at the prompt, do:

```
mkdir rocker-tutorial
cd rocker-tutorial
docker run rocker/ropensci
```

And the image will download itself. When it's done, it'll look like it's just hanging with a message like `exit status 0; expected` - kill it with `ctrl-c` and you're all set up! If you have trouble, post in this thread.

**Webcast links:** 
- Youtube: http://www.youtube.com/watch?v=NBrQbkZ3Lzw
- Live hangout: https://plus.google.com/events/cdc7k8eq7toupogcclcgdhoqn3c

**Notes:** https://github.com/BillMills/Rocker-tutorial/
**Etherpad:** https://etherpad.wikimedia.org/p/UBC_Rocker_20151216

Docker is a tool for taking code and dependencies and packaging them up in a container that can be easily shared and re-run by others; no more fighting with installation, dependencies and operating systems! This is an example of what people are calling _containerization_, a powerful new strategy for making our research more reproducible. In this session, we'll work through some basic examples of how to use Docker together, with some science-themed examples.

**Comment by joeyklee** [comment]
+1 so good! Nice one @BillMills

**Comment by tinyheero** [comment]
So sad I am not going to be able to make this :(

**Comment by jennybc** [comment]
I am also sad to miss this. Hopefully we can revisit in 2016 sometime.

**Comment by katieannemills** [comment]
Hey folks,

Update: when researching this talk, I found out there are a bunch of resources for running R in Docker, which I thought might be interesting for this R-heavy group; but to do so, everyone needs to install the dependencies (all 3 GB) of them **before the tutorial** - it's a big download, if we all pound UBC wifi at once things will not go well. Have a look at the updated setup instructions in the top post, and let me know if anything goes wrong. See you all Wednesday!

**Comment by jooolia** [comment]
Gonna try hard to make it to this. Looks really cool Bill!

Not sure if anyone else is running linux but I installed Docker using my package manager and I had to start Docker myself before I could get the ropensci image: 

```
sudo service docker start
sudo run rocker/ropensci
```

I installed docker version 1.8.2 and I guess this is fixed in 1.9 (https://github.com/docker/docker/issues/15620)

**Comment by katieannemills** [comment]
ah, thanks @jooolia! Linux folks, please see above :)

**Comment by samhinshaw** [comment]
Unfortunately I just removed Linux from my chromebook, is docker run entirely from command line?  I can SSH into my workstation but haven't been able to get remote desktop working properly.

**Comment by katieannemills** [comment]
@samhinshaw no but that's the beauty of it - you can run this from any OS: mac, windows or linux :) @jooolia was just pointing out what you might need to do if you have a linux box; see the top post for instructions on getting set up anywhere.

**Comment by katieannemills** [comment]
@samhinshaw oh hmmm, after a bit of googling it seems chromebooks have their own google-specific OS; TIL, sorry about that. Anyway, Docker can indeed be run completely from the command line on your workstation, but the demos I have planned run RStudio in the browser, which might be a bit of a hiccup if you can't tunnel your workstation's browser window to your laptop. That said, nearly all the work will happen in the command line; I think you can still get all the Docker concepts even if you miss out on interacting with RStudio.

**Comment by samhinshaw** [comment]
@BillMills Sorry, I should've clarified, thank you!

**Comment by katieannemills** [comment]
@samhinshaw although, now that I think about it more, you might not miss out on even the RStudio; Docker is going to broadcast RStudio at an IP attached to whatever machine its running on (so, your workstation) - assuming no firewall jiggery-pokery, there's no reason you can't use your chromebook's browser to point at that IP and interact with RStudio on your workstation that way. The magic of the internet!

**Comment by jstaf** [comment]
@jooolia - Thanks, that was very helpful!

If any Linux users get the "Error response from daemon: attempt to write a readonly database" error (I moved the docker install to a different drive and symlinked to it), just restart the Docker service and it _should_ start working again.

**Comment by jstaf** [comment]
That was great @BillMills ! I sent you a pull request with a note on using Docker on Linux (long story short, every time you use `docker`, you must use `sudo`).

**Comment by katieannemills** [comment]
Thanks man! Merged.
