### ISSUE TITLE
IPython tutorial?

### ISSUE THREAD

**Issue by SimonGoring** [minisciencegirl/studyGroup#77]
Hi all, I've been using IPython, but I'm pretty sure I'm using it at the lowest level :)

I'd really get a lot out of a talk on how people use it, which features they use, how they output it into different formats.

Is this something we could arrange?

**Comment by katieannemills** [comment]
Absolutely! It's almost time for a new semester, which means it's almost time for a new poll on what topics people want lessons on. I'll make sure this gets added to the list - meanwhile, if there are any ipython pros out there, step on up to lead this session!
