### ISSUE TITLE
Sessions for 2016

### ISSUE THREAD

**Issue by katieannemills** [minisciencegirl/studyGroup#78]
Hey everyone, it's almost time for a new semester, which means it's time for new session ideas! **Please add suggestions for sessions you would like to attend or lead to this thread.**

A few have already come up:
- Objects in Python (group favorite after the last python session)
- the IPython interpreter (thanks @SimonGoring / see #77 )
- a git / github help session (in partnership with @jennybc + stat 545 / see [this issue](https://github.com/STAT545-UBC/Discussion/issues/218#issuecomment-161382291))

Add your requests here! All tools, languages, and topics welcome - anything that has anything to do with computing for science or open science / open data practices!

**Comment by mstrimas** [comment]
How about cloud computing on services like AWS, Google Cloud, and Digital Ocean. I was able to set up an AWS EC2 instance with an RStudio Server that I've been using; however, I'm totally lost as to all the options these services have to offer and don't feel like I'm using it even remotely effectively.

**Comment by Lauramorillas** [comment]
Hi all, 

what about methods to import high quality Figures from R? I am having issues duing this from Rstudio  when plots are complex and multi-panel.……

Laura Morillas
Postdoctoral fellow, 
Department of Earth, Ocean and Atmospheric Sciences,
University of British Columbia

**Comment by jennybc** [comment]
:+1: to what @mstrimas said.

**Comment by jstaf** [comment]
@Lauramorillas - export all the figures as PDFs. Looks way nicer when trying to put your plots in other projects, as the vectorized art scales better. Also the `cairo` package is a higher-quality plot renderer, especially on Windows (R on Windows makes really grainy plots without `cairo`).

**Comment by minisciencegirl** [comment]
@Lauramorillas: +1 on @kazi11 suggestion with cairo. @jennybc also has written a great tutorial on how to export figures: https://stat545-ubc.github.io/block017_write-figure-to-file.html 

For some publication quality images, I found RSvgDevice to work quite well for me.

If none of these options work, we will start our co-working session back up in January -  hope to see you there.

**Comment by katieannemills** [comment]
@mstrimas @jennybc A cloud session would be awesome! I've just started using EC2 + S3 for my ocean science project, it's been a big hit; also, we can combine this easily (or so they promise) with the Docker stuff I'll be teaching this week for easy deployments - so yeah, let's do it! Happy to help out, or feel free to take it away yourself. My big concern is the hardest part of EC2 is the spectacularly baroque setup process - we should put our heads together on how to get people through that as painlessly as possible.

@Lauramorillas @kazi11 @minisciencegirl sounds like a tutorial on figure generation is in order! A coworking session could be good to as @minisciencegirl said, to work out some of the fiddly details; but going through @jennybc's tutorial could be a great session.

Great ideas all, keep them coming!

**Comment by aammd** [comment]
continuing my desire to unite my overenthusiasm with Machiavellian cunning, I'd like to contribute a lesson on making assertions about data. featuring either:
`assertr` or `assertthat`

**Comment by aammd** [comment]
Also a lesson on `remake`, which i love, an which at least a few other people in the department have used.

**Comment by katieannemills** [comment]
hooray @aammd! Looking forward to both!

**Comment by katieannemills** [comment]
Hey folks,

Happy new year! Time to cobble together a plan for the next few weeks. To do:
- Let's try and pull together several weeks of bookings. I'm thinking a tutorial session every second week, a work-along on the off weeks, and a hacky hour end of January. We've got a couple sessions roughly lined up here to fill in the first few tutorial sessions; @aammd, still into assertions? @lmguzman, I know you have more python you wanted to lead; @mstrimas, still interested in cloud? I could help out with that session. Those three alone + 3 workalongs in between get us to the middle of February; what dates do people want? (and do we still want Wednesday afternoons?)
- Once those few weeks are booked, we can send a big email blast around to everyone at UBC asking for more ideas and sessions; I'd like to have those half-a-dozen bookings first so people can see a big runway of things to jump in on first. @minisciencegirl, I'm counting on your big list of emails for this, and everyone else to pull in their departments, too!
- @lmguzman, our R-SWC is coming up in a couple weeks; how are we doing on prep? I'd love to be able to announce that and the early Study Group lineup by end of next week (Jan 8).

Working with you all last year was awesome, and I think we've learned enough from that to have our best semester ever right now. Let me know!

**Comment by lmguzman** [comment]
Hey @BillMills Happy New Years!

In terms of timing, I personally can't do Wednesday's afternoon anymore since I'll be in class. If any other time suits people I would really appreciate that! 

About Python, yes I want to do a couple more sessions, but for me they would have to be anytime after the 21 of January.

The workshop, I contacted scheduling services and I enquirerd about the booking for the 29-30. They told me they weren't going to process it until term is back, so I will let you know early next week but I will have it ready before the 8th for sure.

**Comment by minisciencegirl** [comment]
Happy New Year everyone! 

Thanks @BillMills for jump-starting the new semester. I am on it re email blast.  Also, let's not forget the awesome potential instructor list put together by @joeyklee before the holidays. 

@joeyklee: Let me know what I can help with contacting potential instructors!

**Comment by aammd** [comment]
Hello @BillMills and everyone!
yup, I'm still into teaching assertions! I would also love to do one on [remake](https://github.com/richfitz/remake)

**Comment by mstrimas** [comment]
Hey @BillMills, yes, I'd still be interested in something on cloud computing and could definitely use some help with it. I'm slowly putting together some notes on this.

**Comment by joeyklee** [comment]
Hi @minisciencegirl,

Thanks! Yes, that is on my list of to-do’s. I will followup with you in another email thread :)

-J

**Comment by SimonGoring** [comment]
I could do a pretty straightforward leaflet or leaflet/shiny workshop.

**Comment by katieannemills** [comment]
Awesome, thanks all! These all sound fantastic. Has everyone seen the survey to pick a meeting time for the new semester: https://github.com/minisciencegirl/studyGroup/issues/79

Please fill in your availability there by **end of business Thursday** so we can pick the best time, book some rooms and get a schedule going. Thanks again, all these sessions sound great!

**Comment by tinyheero** [comment]
I would be interested in teaching a bioconductor workshop.

**Comment by markjohnsonubc** [comment]
I'm keen to attend a workshop on leaflet and/or leaflet/shiny

On Jan 5, 2016, at 12:52 PM, Simon <notifications@github.com<mailto:notifications@github.com>> wrote:

I could do a pretty straightforward leaflet or leaflet/shiny workshop.

**Comment by minisciencegirl** [comment]
Hey @tinyheero: Which bioconductor packages are you thinking of? (DESeq2 perhaps??)
Also check out some ideas from https://github.com/minisciencegirl/studyGroup/issues/17

@ksamuk: interested in teaming up with @tinyheero?

**Comment by ksamuk** [comment]
@minisciencegirl: Possibly! I'm not sure of my availability this semester (will find out soon). I think I could do a demo of VariantAnnotation if people are interested.

@tinyheero: Any idea what Bioconductor packages you'd want to cover in your workshop?

**Comment by jennybc** [comment]
What's with all the tiny and mini people here? 😜

**Comment by tinyheero** [comment]
@ksamuk @minisciencegirl I was thinking of doing some like GenomicRanges, GenomicAlignment. Basically, the core stack of Bioconductor. Though I don't really know how much content there is. Might have to be over several sessions?

**Comment by minisciencegirl** [comment]
Most likely a fear of “adulting"!

**Comment by SimonGoring** [comment]
Isn't that why we all stay in academia?

**Comment by katieannemills** [comment]
OK team, as concluded in #79, we are meeting **Mondays at 1** for the next four months. This Monday is maybe a little quick to pull a lesson together for (unless someone has something ready to go?), so maybe we can just do a co-working session / hang out if anyone wants to chat, and have our first lesson on **Monday, January 18**. Also, this semester, let's try alternating lessons and co-working sessions week to week. In which case, we're looking for lessons on:
- January 18
- February 1
- February 15
- February 29
- March 14
- ~~March 28~~ holiday
- April 4
- April 18

All the sessions proposed sound great - start calling dibs on the day you want from the list above! Would be cool to fill in a few of the sooner dates with the ideas above, so we can show off a schedule in the email blast next week. Thanks all, looking forward to all your sessions!

**Comment by rozdakin** [comment]
fyi for Jan 25 I had to change our room booking to the smaller room next door (rm 225) to accommodate another event. 

So we have room 224 from 1:00-3:00PM every Monday <i>except</i> Jan 25th when we have room 225.

**Comment by katieannemills** [comment]
no problem, thanks @rozdakin! Also everyone, don't forget to pick a date for your session - I'll be in 224 1-3 today (see #80) if you want to discuss in person, or just call out your date here!

**Comment by SimonGoring** [comment]
March 28th is Easter Monday.  I assume that's a holiday at UBC.

**Comment by katieannemills** [comment]
ah, thanks @SimonGoring! We'll push the schedule back by a week then.

**Comment by ghost** [comment]
Hi there,I previously requested for a session on github [#Issue 218](https://github.com/STAT545-UBC/Discussion/issues/218) in Jenny's STAT545 class. I was just curious to know if it could be added to your schedule please..Thanks!

**Comment by minisciencegirl** [comment]
Hi @gjahesh: Of course! I think @jennybc and @BillMills were talking of a fairly informal setup - maybe over beers one afternoon at Koerner's pub. @jennybc & @BillMills: what's your schedule like in January? I can get in touch with Koerner's about reserving a table.

**Comment by jennybc** [comment]
I'd prefer to react to specific dates. But I have two more trips coming up in January and none really in February. So prefer February.

**Comment by minisciencegirl** [comment]
Hi @gjahesh: Do you want to find a few dates in Feb that work for you and fellow STAT545 students interested in learning more GitHub? I can help with finding location and final scheduling. I just opened an issue for this session (see Issue #96)

**Comment by katieannemills** [comment]
@gjahesh yep, I am still totally in for this - but +1 to February, I too, like @jennybc, am hilariously slammed for the rest of the month :)
