### ISSUE TITLE
New meeting time survey

### ISSUE THREAD

**Issue by katieannemills** [minisciencegirl/studyGroup#79]
Hey folks, since lots of us have new schedules for the new semester, let's have a go at re-assessing when a good time for our weekly, 1-hour meetups should be. Please highlight your available times in this poll: http://whenisgood.net/yswp9c2 - note that the calendar day doesn't matter, just the day of the week for our usual thing. See you all soon!

**Comment by katieannemills** [comment]
Reminder  - everyone please fill in the times you're available for our weekly Study Group meetup in the survey linked above by **end of business Thursday** (January 7), so we can get a schedule going - thanks!

**Comment by katieannemills** [comment]
Alright, the most popular times in descending order are:
1. Thursdays 9 AM
2. A 4-way tie between Mondays at 9 or 1; Wednesday at noon; or Friday at 9.

@aammd @lmguzman @rozdakin, can you try and book 224 for 2 hours starting at one of those times every week through April? Whichever one works will be the final time. Thanks all!

**Comment by morien** [comment]
I didn't vote for Wednesdays at noon but I'll vote for it now if that makes
a difference. Can't make 9 am any day of the week.

**Comment by lmguzman** [comment]
But Wednesday's at noon is the zoology seminar. 
Can we do Monday at 1 then?

**Comment by katieannemills** [comment]
The difference between first place and second place was a whopping one whole vote - any of the times listed are fair picks, and mostly comes down to when we can get a room. Let us know!

**Comment by rozdakin** [comment]
Ok, I have booked room 224 for Thursdays 9:00-11:00am up until the end of April, with the exception of Jan 21 when there was another booking at that time.

If anything changes, please let me know!

**Comment by minisciencegirl** [comment]
@BillMills: I can't make it for Monday or Thursday at 9 because of lab meetings. Is there any way to do Monday at 1??

**Comment by mstrimas** [comment]
I TA all morning on Thursday, so I second Monday at 1.

**Comment by katieannemills** [comment]
How about it @rozdakin - thanks for getting the Thursday booking, but is Monday / 1 available? Seems like it might work slightly better.

**Comment by rozdakin** [comment]
Done and done! We have room 224 for Mondays, 1:00-3:00pm, from Jan 11 to April 25 (no exceptions this time).

**Comment by minisciencegirl** [comment]
Woot thanks Roz!!

**Comment by katieannemills** [comment]
Awesome, done and done - thanks all!
