### ISSUE TITLE
How to run Cytoscape from R for network visualization?

### ISSUE THREAD

**Issue by jooolia** [minisciencegirl/studyGroup#8]
I think it seems possible: https://github.com/idekerlab/cy-rest-R

I might be interested in leading a little tutorial, but perhaps someone else has experience with this and would be willing to team up? 

Cytoscape: http://www.cytoscape.org/

**Comment by jstaf** [comment]
Ooh, this would be super cool. I've used Cytoscape before (the [ClueGO plugin](http://apps.cytoscape.org/apps/cluego)), but never done anything through R. Not sure how helpful that would be.

**Comment by jooolia** [comment]
Cool! Ok perhaps I could try to draft a little tutorial and get your thoughts (and any other interested parties. :)) on it as it progresses? For me I would imagine presenting something the week of May 18th or June 1st, would you be around to help a bit with the tut sometime around then?

**Comment by jooolia** [comment]
Will work on the tutorial over here: https://github.com/jooolia/R_cytoscape_tutorial

**Comment by minisciencegirl** [comment]
I am definitely interested in this!

**Comment by jooolia** [comment]
Hi! I'd finally like to revive this! :triumph:  @minisciencegirl if there is still interest could I bump the co-working session March 21st to run a tut? Would expect cytoscape to be installed, but my idea would be to cover Cyrest setup, sending networks from R to Cytoscape, manipulating network styles and layout.

**Comment by minisciencegirl** [comment]
Definitely! I think @eacton and I are definitely still interested.

**Comment by jooolia** [comment]
-- edit --
**Where**: [UBC Beatty Biodiversity Bldg](https://www.google.ca/maps/place/Beaty+Biodiversity+Museum,+Vancouver,+BC+V6T+1Z4/@49.2634989,-123.2524072,17z/data=!3m1!4b1!4m2!3m1!1s0x548672c9f84be123:0x1c431143106eb830), room 224
**When**: 1 PM, March 21
-- edit --

Hi gang!

Here's more info about the tutorial for tomorrow. The tutorial will live in this repository: https://github.com/jooolia/R_cytoscape_tutorial

There are quite a few things to install. Please do your best to install these things beforehand and if you run into any problems I can try to help. 

We will run through a basic example of creating a network in R, sending the network to Cytoscape and layering on some metadata. 

# More details:

## Installation for running Cytoscape from R tutorial:

 Requirements:
- Java 8 (http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html)
- Cytoscape 3.2.1 or later (http://www.cytoscape.org/download.php)
- CyREST (used to communicate between Cytoscape and R): 
  - Start Cytoscape
  - Apps → App Manager
  - Select cyREST
  - Click install
- R packages: RJSONIO and igraph
  - from R run: `install.packages(c("RJSONIO", "igraph"))`

## Tutorial plan:

There are lots of great ways to make simple networks in R. A non-exhaustive list includes:
- Diagrammer https://github.com/rich-iannone/DiagrammeR
- igraph http://igraph.org/r/
- ggraph (https://github.com/thomasp85/ggraph)

This tutorial is aimed at:
- Cytoscape users interested in running/automating the creation and manipulation of Cytoscape networks using R.
- R users interested in examining more complex networks in an exploratory way 
- R users interested in visualizing networks with metadata.

The tutorial will: 
- Get R and Cytoscape "talking"
- Build a small network in R
- Send the network to Cytoscape
- Give a brief tour of the network in Cytoscape
- Style network visualization using network properties and metadata
