### ISSUE TITLE
Mini R conferences might interest some of you guys

### ISSUE THREAD

**Issue by pssguy** [minisciencegirl/studyGroup#81]
https://docs.google.com/forms/d/1Of4z1F0pzdVs1nZVXgOongcwRv87caGFGzaZBc3aUwg/viewform?c=0&w=1

**Comment by katieannemills** [comment]
yes! this looks awesome, thanks for the reminder! I am totally in to help throw a Study Group x satRday event here in Vancouver. Do you know where we can stay on top of developments in this program?

**Comment by pssguy** [comment]
I just filled in the form. I guess they are waiting to get enough interest to approach consortium for some financial support - so may take a while

**Comment by pssguy** [comment]
Here's a comprehensive rundown
http://stephlocke.github.io/RSaturday-proposal/isc-proposal.html#interested-parties
