### ISSUE TITLE
Co-working Session / January 25

### ISSUE THREAD

**Issue by katieannemills** [minisciencegirl/studyGroup#83]
### note the change of room for this week only! We are next door, in biodiv 225.

**What**: co-working session: work on your current coding project, ask for help and feedback from friendly people
**When**: Monday, January 25, 1 PM
**Where**: [UBC Main Campus, Biodiversity Bldg Rm 225](https://www.google.ca/maps/place/Beaty+Biodiversity+Museum,+Vancouver,+BC+V6T+1Z4/@49.2634989,-123.2524072,17z/data=!3m1!4b1!4m2!3m1!1s0x548672c9f84be123:0x1c431143106eb830)
**Who**: absolutely everyone! Beginners especially welcome!

Let's meet up Monday at 1 to work on our projects together, get help from each other, and talk about what everyone's up to. **All disciplines, languages and skill levels very welcome!**

**Comment by Frikster** [comment]
Is there an end time?

**Comment by katieannemills** [comment]
Heya @Frikster - co-working sessions usually go for about 2 hours. Hope to see you there!
