### ISSUE TITLE
Assertions in R / February 1

### ISSUE THREAD

**Issue by katieannemills** [minisciencegirl/studyGroup#84]
**What**: introduction to making assertions in R
**When**: Monday, February 1, 1 PM
**Where**: [UBC Main Campus, Biodiversity Bldg Rm 224](https://www.google.ca/maps/place/Beaty+Biodiversity+Museum,+Vancouver,+BC+V6T+1Z4/@49.2634989,-123.2524072,17z/data=!3m1!4b1!4m2!3m1!1s0x548672c9f84be123:0x1c431143106eb830)
**Who**: absolutely everyone! Beginners especially welcome!
**Webcast link**: http://youtu.be/9ROL8b8wtfE

@aammd will be introducing assertions in R - details forthcoming.

**Comment by tinyheero** [comment]
Will this be webcasted?

**Comment by aammd** [comment]
I don't see why not!

**Comment by katieannemills** [comment]
Cool, thanks @aammd - @tinyheero et al, check the top post in this thread shortly before the meetup to find the URL. See you then!

**Comment by aammd** [comment]
Data for today (i hope this works!) are [here](https://dl.dropboxusercontent.com/u/8127636/gapminder_2016.csv)

**Comment by SimonGoring** [comment]
Will we be able to stream this?

**Comment by aammd** [comment]
link to the video  http://youtu.be/9ROL8b8wtfE

**Comment by tinyheero** [comment]
Thanks watching it right now.

**Comment by tinyheero** [comment]
Great stuff thanks man!

**Comment by aammd** [comment]
why thank you @tinyheero and everyone who tuned in!

**Comment by wmhall** [comment]
@aammd kaggle datasets: https://www.kaggle.com/datasets

**Comment by JoeyBernhardt** [comment]
thanks @aammd this was great! super useful!
