### ISSUE TITLE
Co-working Session / February 8

### ISSUE THREAD

**Issue by katieannemills** [minisciencegirl/studyGroup#85]
**What**: co-working session: work on your current coding project, ask for help and feedback from friendly people
**When**: Monday, February 8, 1 PM
**Where**: [UBC Main Campus, Biodiversity Bldg Rm 224](https://www.google.ca/maps/place/Beaty+Biodiversity+Museum,+Vancouver,+BC+V6T+1Z4/@49.2634989,-123.2524072,17z/data=!3m1!4b1!4m2!3m1!1s0x548672c9f84be123:0x1c431143106eb830)
**Who**: absolutely everyone! Beginners especially welcome!

Let's meet up Monday at 1 to work on our projects together, get help from each other, and talk about what everyone's up to. **All disciplines, languages and skill levels very welcome!**

**Comment by jennybc** [comment]
FYI this is a stat holiday: Family Day. And Vancouver School Board has made the next day a district wide Pro-D day = no school. So people with kids might have ... kids. Or go away for the 4-day weekend.

**Comment by katieannemills** [comment]
I am _terrible_ at looking at calendars - let's cancel unless anyone absolutely has their heart set on coming in on the long weekend, and put off the text editor fashion show until the next co-working. Objections?

**Comment by katieannemills** [comment]
No objections then - cancelled. See you next time!
