### ISSUE TITLE
Introduction to Broom (#rstats) / February 29

### ISSUE THREAD

**Issue by katieannemills** [minisciencegirl/studyGroup#86]
**What**: Introduction to using Broom in R to clean up messy data into easy-to-use dataframes.
**When**: Monday, February 29, 1 PM
**Where**: [UBC Main Campus, Biodiversity Bldg Rm 224](https://www.google.ca/maps/place/Beaty+Biodiversity+Museum,+Vancouver,+BC+V6T+1Z4/@49.2634989,-123.2524072,17z/data=!3m1!4b1!4m2!3m1!1s0x548672c9f84be123:0x1c431143106eb830)
**Who**: absolutely everyone! Beginners especially welcome!

Will is going to walk us through an introduction to Broom - details forthcoming!

**Comment by wmhall** [comment]
HI Everyone, 

Here is the [link](https://github.com/wmhall/broom_lesson/blob/master/broom_lesson.md) to my `broom` lesson.

We will be using the `broom` package along with `gapminder`, `dplyr`, and `ggplot2`. I'll go over how to install these packages at the start of the lesson but if you already know how, go ahead and install them before the lesson.

**Comment by lmguzman** [comment]
Ahh, Im sad im missing this :disappointed:

**Comment by katieannemills** [comment]
This is awesome, thanks @wmhall!

**Comment by minisciencegirl** [comment]
Great tutorial @wmhall!! Wish I knew about broom three months ago. :-)
