### ISSUE TITLE
Co-working Session / February 22

### ISSUE THREAD

**Issue by katieannemills** [minisciencegirl/studyGroup#87]
**What**: co-working session: work on your current coding project, ask for help and feedback from friendly people
**When**: Monday, February 22, 1 PM
**Where**: [UBC Main Campus, Biodiversity Bldg Rm 224](https://www.google.ca/maps/place/Beaty+Biodiversity+Museum,+Vancouver,+BC+V6T+1Z4/@49.2634989,-123.2524072,17z/data=!3m1!4b1!4m2!3m1!1s0x548672c9f84be123:0x1c431143106eb830)
**Who**: absolutely everyone! Beginners especially welcome!

Let's meet up Monday at 1 to work on our projects together, get help from each other, and talk about what everyone's up to. **All disciplines, languages and skill levels very welcome!**

**Comment by aammd** [comment]
How about we combine this co-working with the Text Editor Fashion Show?  #95 
As you're working you can put your computer on the project for a bit and show us your favourite text editor tricks

**Comment by Frikster** [comment]
Is there not going to be a co-working session on February 8th?

**Comment by katieannemills** [comment]
@Frikster correct! It's a holiday - this co-working on the 22nd will be our next one, with a Pandas lesson on the 15th before that. See you then!

**Comment by Frikster** [comment]
Oh right! Totally forgot lol.
