### ISSUE TITLE
~~Plotting in Python / April 18~~ cancelled, returning this summer :)

### ISSUE THREAD

**Issue by katieannemills** [minisciencegirl/studyGroup#92]
**What**: an introduction to scientific plotting in Python.
**When**: Monday, April 18, 1 PM
**Where**: [UBC Main Campus, Biodiversity Bldg Rm 224](https://www.google.ca/maps/place/Beaty+Biodiversity+Museum,+Vancouver,+BC+V6T+1Z4/@49.2634989,-123.2524072,17z/data=!3m1!4b1!4m2!3m1!1s0x548672c9f84be123:0x1c431143106eb830)
**Who**: absolutely everyone! Beginners especially welcome!

@lmguzman will be introducing plotting in python - details forthcoming!

**Comment by SimonGoring** [comment]
Hi, just posted in the main scheduling thread, but isn't this a holiday?

**Comment by katieannemills** [comment]
Right you are! thanks @SimonGoring.

**Comment by katieannemills** [comment]
Hey folks - sorry for the late notice, but we're going to rebook this one for later in the summer - maybe a bit after our [SWC Python Workshop](http://billmills.github.io/2016-05-17-UBC/) (which there's still room to sign up for!)
