### ISSUE TITLE
Co-working Session / April 11

### ISSUE THREAD

**Issue by katieannemills** [minisciencegirl/studyGroup#93]
**What**: co-working session: work on your current coding project, ask for help and feedback from friendly people
**When**: Monday, April 11, 1 PM
**Where**: [UBC Main Campus, Biodiversity Bldg Rm 224](https://www.google.ca/maps/place/Beaty+Biodiversity+Museum,+Vancouver,+BC+V6T+1Z4/@49.2634989,-123.2524072,17z/data=!3m1!4b1!4m2!3m1!1s0x548672c9f84be123:0x1c431143106eb830)
**Who**: absolutely everyone! Beginners especially welcome!

Let's meet up Monday at 1 to work on our projects together, get help from each other, and talk about what everyone's up to. **All disciplines, languages and skill levels very welcome!**

**Comment by allisonubc** [comment]
Any chance of having one of these this week, or next week?

**Comment by katieannemills** [comment]
April 11 is our next slot, but if the clock is ticking, I'd be happy to try and get something sorted for you - let me know what's up!

**Comment by allisonubc** [comment]
Thanks! Yes, the clock is definitely ticking. I have a lot of data, some quantitative, some qualitative, some dates, some dependent variables, and potentially some correlated ones too. I am having difficulty getting started in R as I have a lot of research questions. Sounds like I might be able to tackle a bunch in a multiple regression, but I am having trouble dealing with the qualitative (text based) variables. 

I can basically make myself available anytime this week (Tuesday?) if someone is willing to help me out :)

**Comment by katieannemills** [comment]
Good to e-meet you, @allisonubc! Hopefully some folks on this list who are better at R than me can help out - in any case, I'll be on campus Tuesday, and we can take a swing. Do please be aware though: **anything you put on github is public**, so if there are privacy concerns with your data, best to hold back until we can chat. Hope to see you soon!

**Comment by allisonubc** [comment]
Ok thanks, any suggestions of whom to contact? I think we met at a session last fall. I was trying to get filemaker data into R.

**Comment by lmguzman** [comment]
What time are you meeting on tuesday?

**Comment by allisonubc** [comment]
Anytime works for me

**Comment by lmguzman** [comment]
Im free around 4pm if you want

**Comment by allisonubc** [comment]
Thank you, yes I can be there. Where should we meet? In the biodiv building?

**Comment by katieannemills** [comment]
@lmguzman knows a billion times more R than me; I'm going to defer to the master :)

**Comment by lmguzman** [comment]
yeah, Ill be in biodiv 207

**Comment by allisonubc** [comment]
great, I'll see you there tues at 4 -- thanks!
