### ISSUE TITLE
Text Editor Fashion Show

### ISSUE THREAD

**Issue by aammd** [minisciencegirl/studyGroup#95]
Yes! I think we should try something like this. Everybody just takes turns at the projector, showing a few basic things in their favourite Text Editor. I am thinking of the "Beyond Rstudio" options, but even some advanced level Rstudio tips would be great!

What do you think, and what editor could you show? I could show some Sublime Text (though I have a lot to learn)

**Comment by katieannemills** [comment]
Yep I'm all sublime all the time too - can't say I use it with any kind of dexterity though.

**Comment by jennybc** [comment]
You had me at "fashion show". 👗👠

Though I am more often in RStudio now, I still have a few emacs tricks up my sleeve. Use it as my file manager, rectangular editing, quick repeatable keyboard macros.

**Comment by aammd** [comment]
Alternate title: "Text Editor Cantrips for the Beginning Wizard". Though I do love the idea of a runway battle with @BillMills 
Perhaps we could roll this into the 8 Feb workalong ( #85 ) ?

**Comment by lmguzman** [comment]
Nice, it would definitely go along with your new years resolution!

**Comment by katieannemills** [comment]
Sure, why not? x-post there to let people know!

**Comment by daisieh** [comment]
I'd love to show off BBEdit.
Daisie

On Tue, Jan 12, 2016 at 4:41 PM, Bill Mills notifications@github.com wrote:
Sure, why not? x-post there to let people know!

—
Reply to this email directly or view it on GitHub
[https://github.com/minisciencegirl/studyGroup/issues/95#issuecomment-171112344] .[https://github.com/notifications/beacon/ABvjkBSZDj4_j-7ZEyAqwsMiFNapDfNSks5pZZS-gaJpZM4HDoQR.gif]

**Comment by SimonGoring** [comment]
I'm pretty comfortable with RStudio, but as I move into coding more HTML & Python (& consider Julia) I'd really like to see a breadth of editors.

**Comment by minisciencegirl** [comment]
+++1

**Comment by tinyheero** [comment]
I would love to demonstrate Vim and the Vim-r-plugin (basically replaces RStudio).

**Comment by aammd** [comment]
@tinyheero at last, the champion for Vim is revealed! 
Nobody is on gedit or Notepad++ ?

**Comment by radaniba** [comment]
@aammd What is the status if this issue

**Comment by aammd** [comment]
@radaniba : status on this issue is currently set to "awesome" and "stylish" :sunglasses: :dancer: 

It will be occurring on 22 Feb , see #87

**Comment by daisieh** [comment]
Sad, I will be in Florida at an OpenTree thingo on that date. Have fun without me!

**Comment by jstaf** [comment]
Very late to the party here, but I've been trying to get good with vim lately. The main thing it's got going for is that it's the only thing guaranteed to be on any system you work on (especially if you're working remotely on a server/cluster with no display).

If you enter `/text_I_want_to_find` in command mode (hit `ESC`), vim will find that text in a document and take you there.

**Comment by jennybc** [comment]
I did some damage at Value Village today. Wear basic pieces tomorrow so you can layer these beautiful items on top. Is anyone else bringing some fashion?

**Comment by aammd** [comment]
:tophat:

**Comment by morien** [comment]
My lab meeting tomorrow is cancelled. I think I can actually make it out to
this. V exciting!

**Comment by katieannemills** [comment]
Did anyone leave a mac -> VGA adapter in the room? I have it if you're looking for it~
