### ISSUE TITLE
Git and GitHub Galore!

### ISSUE THREAD

**Issue by minisciencegirl** [minisciencegirl/studyGroup#96]
A number of students in @jennybc STAT545 class have expressed interest in learning more about Git and GitHub (Cc: @gjahesh, @BattaLiu, @hamid-omid, @zhamel, @min110, @wmhall, @JoeyBernhardt). See issue #78.

If you guys can figure out couple of dates that work for you in February, we can set this event up!

**Comment by joeyklee** [comment]
Hi All,

I’m working with the Mozilla Science Lab to put together a github workshop(s) come mid Feb. The first github workshop will most likely happen during reading break as part of the UBC library’s reading week activities (http://about.library.ubc.ca/2014/02/13/reading-week-activities-at-ubc-library/ http://about.library.ubc.ca/2014/02/13/reading-week-activities-at-ubc-library/). I’m not sure it is posted yet.

We can certainly reuse and remix those resources once they are done!
-J

**Comment by ghost** [comment]
Thanks @minisciencegirl . I have put up a poll [here](http://doodle.com/poll/pvd5fdqvpigrxc6v#table) and updated [issue#218](https://github.com/STAT545-UBC/Discussion/issues/218) :)

**Comment by katieannemills** [comment]
So it looks like Tuesday, February 9 is the unanimous winner from @gjahesh's poll - I can do this if it's later in the afternoon (like 4 onwards). Shall we make it official? Where at?

**Comment by jennybc** [comment]
Tues Feb 9 4pm or later looks workable to me too. I assume I'm still in the mix here?

**Comment by katieannemills** [comment]
@jennybc yes please! Do we still want to try the pit / koerners? I'm good with any / all.

**Comment by jennybc** [comment]
OK I put it on my calendar.

**Comment by daisieh** [comment]
I put it in my calendar too!

**Comment by minisciencegirl** [comment]
Lovely #Git Folks! I've made a reservation for 12 - 14 people at Mahoney's.

Time: Tues, Feb 9, 5pm.

The reservation is under my name. I may be a bit late since I have a meeting right up until 5pm.

**Comment by jennybc** [comment]
Are we going to attempt to project or just sit around with laptops?

**Comment by katieannemills** [comment]
I thought we'd just chat & circulate, keep things simple - see you all there!
