### ISSUE TITLE
Google Calendar for the group is empty

### ISSUE THREAD

**Issue by Frikster** [minisciencegirl/studyGroup#97]
Hi, from what I can see https://calendar.google.com/calendar/embed?src=minisciencegirl@gmail.com

the google calendar for the group is currently empty. After I add the calendar to my own it is likewise empty as expected. I use google calendar daily to remind me where to go 15 minutes before an event so it would be very helpful for me if this could be fixed, thanx!

**Comment by minisciencegirl** [comment]
We are currently working on the script to update the calendar. Hopefully the issue will be resolved soon. Thanks

**Comment by katieannemills** [comment]
This looks sorted to me - thanks @minisciencegirl!
