### ISSUE TITLE
Helpers for R workshop in LSC!

### ISSUE THREAD

**Issue by alysekh** [minisciencegirl/studyGroup#99]
Hi all,
Ecoscope - a microbial ecology training program - is looking for helpers for a series of R workshops this month! A chance to sharpen your skills and help others, and maybe learn a few new tricks from some seasoned instructors :)
Taking place in LSC3, several two hour workshops over two weeks.
Here is a link: http://ecoscope.ubc.ca/events/introduction-to-r-workshop-series/ 
Unfortunately we are currently oversubscribed but are in desperate need of helpers, even if it's just for one session.
please contact Zaira at zaira.petruf@ubc.ca
Thanks!!
P.S. hope posting here is ok!

**Comment by minisciencegirl** [comment]
Closing this issue - let me know if you are still looking for help for this workshop.
